import JXG from 'jsxgraph';
import * as THREE from 'three';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const E=()=>window.ELDILabEngine,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ctx=null,board=null,resize=null,controls=null,disposeScene=null,sceneExport=null,tab='functions';
const $=id=>ctx?.root.querySelector('#'+id),state=()=>ctx.profile().labWork||=(E().normalize()),fmt=v=>Number.isFinite(v)?Number(v.toFixed(4)).toLocaleString('bs-BA'):'nije definisano';
const modes={functions:'Funkcije',triangle:'Konstrukcije',solid:'Tijela i mreže',dihedral:'Diedri',algorithms:'Algoritmi',history:'Moji radovi'};
function freeView(){if(board){JXG.JSXGraph.freeBoard(board);board=null;}resize?.disconnect();resize=null;controls?.dispose();controls=null;disposeScene?.();disposeScene=null;sceneExport=null;}
function destroy(){freeView();ctx=null;}
function save(){ctx?.save?.();}
function boardAt(id,box=[-7,6,7,-6]){board=JXG.JSXGraph.initBoard(id,{boundingbox:box,axis:true,text:{display:'internal'},showCopyright:false,showNavigation:true,keepaspectratio:true,pan:{enabled:true},zoom:{enabled:true,wheel:true},defaultAxes:{x:{strokeColor:'#8697b2',ticks:{label:{strokeColor:'#71849e'}}},y:{strokeColor:'#8697b2',ticks:{label:{strokeColor:'#71849e'}}}}});resize=new ResizeObserver(()=>{const el=$(id);if(el&&board)board.resizeContainer(el.clientWidth,el.clientHeight,true);});resize.observe($(id));sceneExport=()=>board.renderer.svgRoot.cloneNode(true);return board;}
function range(id,label,value,min,max,step=.1){return `<label>${label} <output id="${id}-value">${value}</output><input id="${id}" type="range" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;}
function render(){freeView();const s=state();tab=s.mode;ctx.root.innerHTML=`<div class="lab-heading"><div><p class="eyebrow">ELDI LAB / ISTRAŽI · KONSTRUIŠI · OBJASNI</p><h1>Matematika u pokretu.</h1><p>Svaka promjena ima značenje. Pomjeraj, mjeri i sačuvaj svoje istraživanje.</p></div><span class="lab-local">Lokalno · 2D / 3D</span></div><div class="row lab-tabs" role="group" aria-label="Laboratoriji">${Object.entries(modes).map(([k,v])=>`<button data-lab-mode="${k}" class="${tab===k?'primary':''}">${v}</button>`).join('')}</div><div id="lab-content"></div><p id="lab-status" role="status"></p><details class="lab-notes card"><summary>Moje objašnjenje i izvoz</summary><label>Postupak / zapažanja<textarea id="lab-notes" maxlength="6000">${esc(s.notes)}</textarea></label><div class="row"><input id="lab-name" maxlength="120" placeholder="Naziv istraživanja" aria-label="Naziv istraživanja"><button id="lab-save">Sačuvaj verziju</button><button id="lab-export">Izvezi JSON</button><label class="lab-import">Uvezi JSON<input id="lab-import" type="file" accept=".json"></label><button id="lab-svg">Slika SVG</button><button id="lab-png">Slika PNG</button><button id="lab-print">Štampaj</button></div></details>`;
 ctx.root.querySelectorAll('[data-lab-mode]').forEach(b=>b.onclick=()=>{s.mode=b.dataset.labMode;save();render();});
 ({functions,triangle,solid,dihedral,algorithms,history})[tab]();
 $('lab-notes').oninput=()=>{s.notes=$('lab-notes').value;save();};
 $('lab-save').onclick=()=>{const scene=structuredClone(s);delete scene.saved;const name=$('lab-name').value.trim()||modes[tab];s.saved.unshift({name,date:new Date().toISOString(),scene});s.saved=s.saved.slice(0,30);save();$('lab-status').textContent='Sačuvano: '+name;};
 $('lab-export').onclick=()=>ctx.exportFile('ELDI-laboratorij.json',JSON.stringify({format:'ELDI-LAB-1',work:E().normalize(s)},null,2),'application/json');
 $('lab-import').onchange=async()=>{try{const f=$('lab-import').files[0];if(!f)return;if(f.size>2000000)throw Error('Najviše 2 MB.');const data=JSON.parse(await f.text());if(data.format!=='ELDI-LAB-1')throw Error('Nepoznat format laboratorija.');const next=E().normalize(data.work);ctx.profile().labWork=next;save();render();}catch(e){$('lab-status').textContent=e.message;}};
 $('lab-svg').onclick=()=>exportImage(false);$('lab-png').onclick=()=>exportImage(true);$('lab-print').onclick=()=>ctx.print?.();
}
async function exportImage(png){try{if(!sceneExport)throw Error('Na ovom prikazu nema slike za izvoz.');const svg=sceneExport();svg.querySelectorAll('foreignObject').forEach(node=>node.remove());svg.setAttributeNS('http://www.w3.org/2000/xmlns/','xmlns','http://www.w3.org/2000/svg');const text=new XMLSerializer().serializeToString(svg);if(!png)return ctx.exportFile('ELDI-'+tab+'.svg',text,'image/svg+xml');const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'})),img=new Image();try{await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url;});const canvas=document.createElement('canvas');canvas.width=Math.max(1000,img.width*2);canvas.height=canvas.width*img.height/img.width;const p=canvas.getContext('2d');p.fillStyle='#ffffff';p.fillRect(0,0,canvas.width,canvas.height);p.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(ok=>canvas.toBlob(ok,'image/png'));if(!blob)throw Error('Prikaz nema ispravne dimenzije za izvoz.');const link=document.createElement('a'),download=URL.createObjectURL(blob);link.href=download;link.download='ELDI-'+tab+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(download),1000);}finally{URL.revokeObjectURL(url);}}catch(e){$('lab-status').textContent=e.message||'Slika nije mogla biti izvezena.';}}
function functions(){const s=state();$('lab-content').innerHTML=`<div class="lab-layout"><div><div id="lab-board" class="lab-board"></div><div id="lab-numeric" class="lab-result"></div></div><aside class="lab-panel"><h2>Moje funkcije</h2>${s.expressions.map((v,i)=>`<label>f${i+1}(x)<input id="lab-expression-${i}" value="${esc(v)}" maxlength="300" placeholder="npr. sin(x) ili 1/x"></label>`).join('')}<button id="lab-plot" class="primary">Nacrtaj funkcije</button><p class="muted">x, a, b, c, pi; + − * / ^; sin, cos, tan, sqrt, abs, exp, ln, log. Uglovi su u radijanima.</p>${['a','b','c'].map(k=>range('lab-param-'+k,k,s.params[k],-10,10)).join('')}<label>Vrijednost x<input id="lab-at-x" type="number" value="1" step="0.1"></label><div id="lab-values"></div></aside></div>`;
 const b=boardAt('lab-board');let graphs=[],functions=[];const colors=['#28b9aa','#bc86ea','#e4a14b'];
 const sample=()=>{const x=+$('lab-at-x').value;$('lab-values').innerHTML=functions.map((fn,i)=>fn?`<p>f${i+1}(${fmt(x)}) = <strong>${fmt(fn(x,s.params))}</strong></p>`:'').join('')+'<table><thead><tr><th>x</th>'+functions.map((fn,i)=>fn?'<th>f'+(i+1)+'</th>':'').join('')+'</tr></thead><tbody>'+[-2,-1,0,1,2].map(v=>'<tr><th>'+v+'</th>'+functions.map(fn=>fn?'<td>'+fmt(fn(v,s.params))+'</td>':'').join('')+'</tr>').join('')+'</tbody></table>';};
 function plot(){try{const parsed=[0,1,2].map(i=>$('lab-expression-'+i).value.trim()),next=parsed.map(x=>x?E().compile(x):null);graphs.forEach(g=>b.removeObject(g));graphs=[];functions=next;s.expressions=parsed;next.forEach((fn,i)=>{if(fn)graphs.push(b.create('curve',[x=>x,x=>fn(x,s.params),()=>b.getBoundingBox()[0],()=>b.getBoundingBox()[2]],{curveType:'functiongraph',strokeColor:colors[i],strokeWidth:2.5,name:'f'+(i+1)}));});b.update();sample();const range=b.getBoundingBox(),zeros=next[0]?E().roots(x=>next[0](x,s.params),range[0],range[2]):[],cross=next[0]&&next[1]?E().roots(x=>next[0](x,s.params)-next[1](x,s.params),range[0],range[2]):[];$('lab-numeric').textContent='Numerički pronađene nule f1: '+(zeros.map(fmt).join('; ')||'—')+' · Presjeci f1 i f2 (x): '+(cross.map(fmt).join('; ')||'—')+'. Pretraga vidljivog intervala ne garantuje sve nule.';$('lab-status').textContent='Grafikoni i numeričke vrijednosti su osvježeni.';save();}catch(e){$('lab-status').textContent=e.message;}}
 $('lab-plot').onclick=plot;$('lab-at-x').oninput=sample;for(const k of ['a','b','c'])$('lab-param-'+k).oninput=()=>{s.params[k]=+$('lab-param-'+k).value;$('lab-param-'+k+'-value').textContent=fmt(s.params[k]);plot();};plot();
}
function triangle(){const s=state();$('lab-content').innerHTML=`<div class="lab-layout"><div><div id="lab-board" class="lab-board"></div><div id="lab-triangle-values" class="lab-result"></div></div><aside class="lab-panel"><h2>Trougao ABC</h2><p>Pomjeri vrh ili unesi koordinate. Konstrukcije ostaju vezane za trougao.</p><div id="lab-coordinates">${['A','B','C'].map((k,i)=>`<div class="lab-coordinate"><strong>${k}</strong><label>x<input data-point="${i}" data-axis="0" type="number" step="0.1" value="${s.triangle[i][0]}"></label><label>y<input data-point="${i}" data-axis="1" type="number" step="0.1" value="${s.triangle[i][1]}"></label></div>`).join('')}</div>${[['medians','Težišnice'],['altitudes','Visine'],['bisectors','Simetrale uglova'],['circumcircle','Opisana kružnica'],['incircle','Upisana kružnica']].map(([k,v])=>`<label class="lab-check"><input type="checkbox" data-construction="${k}" ${k==='medians'?'checked':''}>${v}</label>`).join('')}<button id="lab-reset-triangle">Početni trougao</button></aside></div>`;
 const b=boardAt('lab-board'),P=s.triangle.map((xy,i)=>b.create('point',xy,{name:'ABC'[i],size:4,strokeColor:'#64bcca',fillColor:'#64bcca'}));b.create('polygon',P,{fillColor:'#54b7c8',fillOpacity:.12,borders:{strokeColor:'#59bfd1',strokeWidth:2}});
 const groups={medians:[],altitudes:[],bisectors:[],circumcircle:[],incircle:[]};
 P.forEach((p,i)=>{const q=P[(i+1)%3],r=P[(i+2)%3],mid=b.create('midpoint',[q,r],{visible:false});groups.medians.push(b.create('segment',[p,mid],{strokeColor:'#c297e9',dash:2}));groups.altitudes.push(b.create('perpendicular',[b.create('line',[q,r],{visible:false}),p],{strokeColor:'#e3b066',visible:false,dash:2}));groups.bisectors.push(b.create('bisector',[q,p,r],{strokeColor:'#85bc6d',visible:false,dash:1}));});
 groups.circumcircle.push(b.create('circumcircle',P,{strokeColor:'#75a8eb',strokeWidth:1.5,visible:false}));groups.incircle.push(b.create('incircle',P,{strokeColor:'#e4b779',strokeWidth:1.5,visible:false}));
 function update(){s.triangle=P.map(p=>[p.X(),p.Y()]);const t=E().triangle(s.triangle);$('lab-triangle-values').textContent=t.valid?`a = ${fmt(t.a)} · b = ${fmt(t.b)} · c = ${fmt(t.c)} · Obim = ${fmt(t.perimeter)} · Površina = ${fmt(t.area)}`:'Tačke su kolinearne: nema nedegenerisanog trougla.';ctx.root.querySelectorAll('[data-point]').forEach(el=>{if(document.activeElement!==el)el.value=Number(s.triangle[+el.dataset.point][+el.dataset.axis].toFixed(3));});save();}
 P.forEach(p=>p.on('drag',update));ctx.root.querySelectorAll('[data-point]').forEach(el=>el.onchange=()=>{const i=+el.dataset.point,xy=s.triangle[i].slice(),v=Number(el.value);if(!Number.isFinite(v)||Math.abs(v)>1000){el.value=xy[+el.dataset.axis];return;}xy[+el.dataset.axis]=v;P[i].moveTo(xy);update();});ctx.root.querySelectorAll('[data-construction]').forEach(el=>el.onchange=()=>groups[el.dataset.construction].forEach(g=>g.setAttribute({visible:el.checked})));$('lab-reset-triangle').onclick=()=>{s.triangle=structuredClone(E().DEFAULT.triangle);save();render();};update();
}
function create3D(){const host=$('lab-three'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,500);camera.position.set(13,10,16);const renderer=new SVGRenderer();renderer.setQuality('high');renderer.setClearColor(0x101b2d,1);host.append(renderer.domElement);renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label','Prostorno tijelo, moguće okretanje mišem');renderer.domElement.style.touchAction='none';controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=3;controls.maxDistance=90;scene.add(new THREE.AmbientLight(0xffffff,.8));const light=new THREE.DirectionalLight(0xffffff,1.4);light.position.set(6,10,8);scene.add(light);const group=new THREE.Group();scene.add(group);function render3(){renderer.render(scene,camera);}controls.addEventListener('change',render3);resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);render3();});resize.observe(host);function clear(){while(group.children.length){const o=group.children[0];o.traverse(obj=>{obj.geometry?.dispose();if(Array.isArray(obj.material))obj.material.forEach(m=>m.dispose());else obj.material?.dispose();});group.remove(o);}}disposeScene=clear;sceneExport=()=>renderer.domElement.cloneNode(true);return{scene,group,camera,render:render3,clear};}
function mesh(view,geometry,color=0x63c8c3,opacity=.8){const m=new THREE.Mesh(geometry,new THREE.MeshLambertMaterial({color,transparent:opacity<1,opacity,side:THREE.DoubleSide}));view.group.add(m);return m;}
function line3(view,points,color=0xdce8ff){const g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p))),l=new THREE.Line(g,new THREE.LineBasicMaterial({color,linewidth:1}));view.group.add(l);return l;}
function solid(){const s=state().solid,names={cube:'Kocka',cuboid:'Kvadar',prism:'Pravilna prizma',pyramid:'Pravilna piramida',cylinder:'Valjak',cone:'Kupa',sphere:'Lopta'};$('lab-content').innerHTML=`<div class="lab-layout"><div><div id="lab-three" class="lab-three"></div><div id="lab-solid-values" class="lab-result"></div><details class="lab-net"><summary>Mreža tijela</summary><p id="lab-net-help"></p>${range('lab-net-progress','Prikaži dijelove mreže',1,0,1,.01)}<svg id="lab-net-svg" viewBox="0 0 700 380" role="img" aria-label="Razmjerna ravna mreža tijela"></svg></details></div><aside class="lab-panel"><h2>Istraži tijelo</h2><label>Tijelo<select id="lab-solid-type">${Object.entries(names).map(([k,v])=>`<option value="${k}" ${k===s.type?'selected':''}>${v}</option>`).join('')}</select></label>${[['a','Stranica a',.5,12,.1],['b','Stranica b',.5,12,.1],['r','Poluprečnik r',.5,12,.1],['h','Visina h',.5,12,.1],['n','Broj stranica osnove',3,12,1]].map(([k,label,min,max,step])=>`<div data-solid-field="${k}">${range('lab-solid-'+k,label,s[k],min,max,step)}</div>`).join('')}${range('lab-cut','Visina presjeka (%)',s.cut*100,-100,100,1)}<label class="lab-check"><input id="lab-show-cut" type="checkbox" checked>Ravan paralelna osnovi</label><button id="lab-front">Početni pogled</button><p>Miš: okreni tijelo; točkić: približi. Presjek je paralelan osnovi, a kod lopte ekvatorijalnoj ravni.</p></aside></div>`;const view=create3D();function draw(){view.clear();const{type,a,b,r,h,n}=s;const height=type==='cube'?a:type==='sphere'?2*r:h;let geom;if(type==='cube'||type==='cuboid')geom=new THREE.BoxGeometry(a,height,type==='cube'?a:b);else if(type==='sphere')geom=new THREE.SphereGeometry(r,28,18);else if(type==='cylinder'||type==='cone')geom=new THREE.CylinderGeometry(type==='cone'?0:r,r,h,40,1,false);else{const R=a/(2*Math.sin(Math.PI/n));geom=new THREE.CylinderGeometry(type==='pyramid'?0:R,R,h,n,1,false);}
 mesh(view,geom);if(type!=='sphere'){const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geom,35),new THREE.LineBasicMaterial({color:0xa1e8ed}));view.group.add(edges);}const z=s.cut*height/2,t=(s.cut+1)/2;const calc=E().solid(s);if($('lab-show-cut').checked){let ring=[];if(type==='sphere'||type==='cone'||type==='cylinder'){const radius=type==='sphere'?Math.sqrt(Math.max(0,r*r-z*z)):type==='cone'?r*(1-t):r;ring=Array.from({length:65},(_,i)=>[radius*Math.cos(i*2*Math.PI/64),z,radius*Math.sin(i*2*Math.PI/64)]);}else if(type==='cube'||type==='cuboid'){const d=type==='cube'?a:b;ring=[[-a/2,z,-d/2],[a/2,z,-d/2],[a/2,z,d/2],[-a/2,z,d/2],[-a/2,z,-d/2]];}else{const R=a/(2*Math.sin(Math.PI/n))*(type==='pyramid'?1-t:1);ring=Array.from({length:n+1},(_,i)=>[R*Math.sin(i*2*Math.PI/n),z,R*Math.cos(i*2*Math.PI/n)]);}line3(view,ring,0xffd471);const plane=mesh(view,new THREE.PlaneGeometry(Math.max(a,b,r*2)*1.4,Math.max(a,b,r*2)*1.4),0xf2c25d,.1);plane.rotation.x=-Math.PI/2;plane.position.y=z;}
 line3(view,[[0,-height/2,0],[0,height/2,0]],0xeb8ec2);$('lab-solid-values').textContent=`${names[type]} · Površina ≈ ${fmt(calc.P)} j² · Zapremina ≈ ${fmt(calc.V)} j³ · Presjek ≈ ${fmt(calc.section(z))} j²`;
 const fields=type==='sphere'?['r']:['cone','cylinder'].includes(type)?['r','h']:type==='cube'?['a']:type==='cuboid'?['a','b','h']:['a','h','n'];ctx.root.querySelectorAll('[data-solid-field]').forEach(el=>el.hidden=!fields.includes(el.dataset.solidField));view.render();drawNet();save();}
 function drawNet(){const svg=$('lab-net-svg'),progress=+$('lab-net-progress').value;$('lab-net-progress-value').textContent=Math.round(progress*100)+'%';let paths=[];const{type,a,b,r,h,n}=s;let W=20,H=10;const rect=(x,y,w,h,opacity=1)=>paths.push(`<rect x="${x}" y="${y}" width="${w}" height="${h}" opacity="${opacity}"/>`),circle=(x,y,r,opacity=1)=>paths.push(`<circle cx="${x}" cy="${y}" r="${r}" opacity="${opacity}"/>`);
 if(type==='sphere'){svg.innerHTML='';$('lab-net-help').textContent='Lopta nema tačnu ravnu mrežu bez deformacije. Istraži njene kružne presjeke u 3D prikazu.';return;}
 $('lab-net-help').textContent='Razmjerna mreža; klizač postepeno otkriva omotač i osnove. Ovo je ravna mreža, a ne animacija savijanja.';
 if(type==='cylinder'){const c=2*Math.PI*r;W=c+2;H=h+4*r+2;rect(1,2*r+1,c,h);circle(1+c/2,r+1,r,progress);circle(1+c/2,3*r+h+1,r,progress);}
 else if(type==='cone'){const l=Math.hypot(r,h),theta=2*Math.PI*r/l;W=4*l+2;H=2*l+2;const cx=l+1,cy=l+1;paths.push(`<path d="M${cx},${cy} L${cx+l},${cy} A${l},${l} 0 ${theta>Math.PI?1:0} 1 ${cx+l*Math.cos(theta)},${cy+l*Math.sin(theta)} Z"/>`);circle(3*l+1,l+1,r,progress);}
 else if(type==='cube'||type==='cuboid'){const d=type==='cube'?a:b,height=type==='cube'?a:h;W=2*a+2*d+2;H=height+2*d+2;let x=1;[a,d,a,d].forEach((w,i)=>{rect(x,d+1,w,height,i/4<=progress?1:.1);x+=w;});rect(1,1,a,d,progress);rect(1,d+height+1,a,d,progress);}
 else{const R=a/(2*Math.sin(Math.PI/n)),apothem=a/(2*Math.tan(Math.PI/n));if(type==='prism'){W=n*a+2*R+2;H=h+4*R+2;for(let i=0;i<n;i++)rect(R+1-a/2+i*a,2*R+1,a,h,i/n<=progress?1:.1);for(const y of [2*R+1-apothem,2*R+1+h+apothem]){const cy=y,sgn=y<2*R+1?1:-1;paths.push(`<polygon opacity="${progress}" points="${Array.from({length:n},(_,i)=>{const th=2*Math.PI*i/n+Math.PI/2+Math.PI/n;return `${R+1+R*Math.cos(th)},${cy+sgn*R*Math.sin(th)}`;}).join(' ')}"/>`);}}else{const slant=Math.hypot(h,apothem);W=H=2*(R+slant)+2;const c=W/2,verts=Array.from({length:n},(_,i)=>[c+R*Math.cos(i*2*Math.PI/n),c+R*Math.sin(i*2*Math.PI/n)]);paths.push(`<polygon points="${verts.map(p=>p.join(',')).join(' ')}"/>`);for(let i=0;i<n;i++){const p=verts[i],q=verts[(i+1)%n],mx=(p[0]+q[0])/2,my=(p[1]+q[1])/2,theta=(i+.5)*2*Math.PI/n;paths.push(`<polygon opacity="${i/n<=progress?1:.1}" points="${p} ${q} ${mx+slant*Math.cos(theta)},${my+slant*Math.sin(theta)}"/>`);}}}
 svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML=`<g fill="#73c7be" fill-opacity=".18" stroke="#59a5a6" stroke-width="${Math.min(W,H)/200}">${paths.join('')}</g>`;
 }
 $('lab-solid-type').onchange=()=>{s.type=$('lab-solid-type').value;draw();};for(const k of ['a','b','r','h','n'])$('lab-solid-'+k).oninput=()=>{s[k]=+$('lab-solid-'+k).value;$('lab-solid-'+k+'-value').textContent=fmt(s[k]);draw();};$('lab-cut').oninput=()=>{s.cut=+$('lab-cut').value/100;$('lab-cut-value').textContent=$('lab-cut').value;draw();};$('lab-show-cut').onchange=draw;$('lab-net-progress').oninput=drawNet;$('lab-front').onclick=()=>{view.camera.position.set(13,10,16);controls.target.set(0,0,0);controls.update();};draw();}
function dihedral(){const s=state().solid;$('lab-content').innerHTML=`<div class="lab-layout"><div><div id="lab-three" class="lab-three"></div><div class="lab-result" id="lab-dihedral-result"></div></div><aside class="lab-panel"><h2>Ugao diedra</h2>${range('lab-dihedral-angle','α (stepeni)',s.angle,10,170,1)}<p>Dvije poluravni imaju zajednički brid. Mjera diedra jednaka je uglu njihovih poluprava u normalnom presjeku.</p><svg id="lab-dihedral-cut" viewBox="0 0 280 220" role="img" aria-label="Normalni presjek diedra"></svg></aside></div>`;const view=create3D();function draw(){view.clear();const alpha=s.angle*Math.PI/180;for(const [i,t]of [0,alpha].entries()){const g=new THREE.PlaneGeometry(5,5),m=mesh(view,g,i?0xc597e9:0x69c8ca,.55);m.position.set(2.5*Math.cos(t),0,2.5*Math.sin(t));m.rotation.y=-t;}line3(view,[[0,-3,0],[0,3,0]]);line3(view,[[2.5,0,0],[0,0,0],[2.5*Math.cos(alpha),0,2.5*Math.sin(alpha)]],0xffd36b);const pts=Array.from({length:51},(_,i)=>[1.5*Math.cos(i*alpha/50),0,1.5*Math.sin(i*alpha/50)]);line3(view,pts,0xffd36b);view.render();const cx=130,cy=170,R=100,x=cx+R*Math.cos(alpha),y=cy-R*Math.sin(alpha),ax=cx+45*Math.cos(alpha),ay=cy-45*Math.sin(alpha);$('lab-dihedral-cut').innerHTML=`<path d="M${cx+R},${cy} L${cx},${cy} L${x},${y}" fill="none" stroke="#76bbd1" stroke-width="2"/><path d="M${cx+45},${cy} A45,45 0 0 0 ${ax},${ay}" fill="none" stroke="#e5b76e" stroke-width="2"/><text x="130" y="205" text-anchor="middle" fill="currentColor">α = ${s.angle}°</text>`;$('lab-dihedral-result').textContent=`Ugao normalnog presjeka = ${s.angle}°. Okretanje pogleda ne mijenja stvarni ugao.`;save();}$('lab-dihedral-angle').oninput=()=>{s.angle=+$('lab-dihedral-angle').value;$('lab-dihedral-angle-value').textContent=s.angle;draw();};draw();}
function algorithms(){ $('lab-content').innerHTML=`<div class="lab-panel lab-algorithm"><div class="controls"><label>Algoritam<select id="lab-algo"><option value="sort">Sortiranje zamjenom susjeda</option><option value="search">Linearna pretraga</option><option value="stats">Maksimum, zbir i prosjek</option></select></label><label>Niz (do 12 brojeva)<input id="lab-list" value="7, 2, 9, 4, 1, 6"></label><label>Traženi broj<input id="lab-target" type="number" value="4"></label><button id="lab-algo-load">Pripremi</button></div><div id="lab-bars" class="lab-bars"></div><p id="lab-algo-note" role="status"></p><div class="row"><button id="lab-algo-back">Prethodni korak</button><button id="lab-algo-step" class="primary">Sljedeći korak</button><span id="lab-algo-count"></span></div></div>`;let frames=[],index=0;function show(){const f=frames[index];if(!f)return;$('lab-bars').innerHTML=f.values.map((v,i)=>`<div class="lab-bar ${f.indices.includes(i)?'active':''}"><span>${fmt(v)}</span><div style="height:${20+Math.abs(v)/Math.max(1,...f.values.map(Math.abs))*140}px"></div><small>[${i}]</small></div>`).join('');$('lab-algo-note').textContent=f.note;$('lab-algo-count').textContent=`${index+1} / ${frames.length}`;$('lab-algo-back').disabled=!index;$('lab-algo-step').disabled=index===frames.length-1;}
 $('lab-algo-load').onclick=()=>{const a=$('lab-list').value.split(/[;,\s]+/).filter(Boolean).map(Number);if(!a.length||a.length>12||a.some(x=>!Number.isFinite(x)||Math.abs(x)>100000)){$('lab-status').textContent='Unesi 1–12 konačnih brojeva, do 100000 po apsolutnoj vrijednosti.';return;}frames=E().algorithm($('lab-algo').value,a,+$('lab-target').value);index=0;show();};$('lab-algo-back').onclick=()=>{index=Math.max(0,index-1);show();};$('lab-algo-step').onclick=()=>{index=Math.min(frames.length-1,index+1);show();};$('lab-algo-load').click();}
function history(){const s=state();$('lab-content').innerHTML=`<div class="lab-history">${s.saved.length?s.saved.map((r,i)=>`<article class="card"><h2>${esc(r.name)}</h2><p>${esc(modes[r.scene.mode])} · ${esc(new Date(r.date).toLocaleString())}</p><p>${esc(r.scene.notes.slice(0,160))}</p><button data-lab-open="${i}">Otvori istraživanje</button></article>`).join(''):'<p>Sačuvaj istraživanje preko odjeljka „Moje objašnjenje i izvoz”.</p>'}</div>`;ctx.root.querySelectorAll('[data-lab-open]').forEach(b=>b.onclick=()=>{const record=s.saved[+b.dataset.labOpen],saved=s.saved;ctx.profile().labWork={...E().normalize(record.scene),saved};save();render();});}
window.ELDILab=Object.freeze({mount(options){destroy();ctx=options;ctx.profile().labWork=E().normalize(ctx.profile().labWork||{});render();},destroy,getContext:()=>({title:'Matematički laboratorij · '+modes[tab],subject:'Matematika',statement:ctx?JSON.stringify({...state(),saved:undefined}):''})});
