'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawn}=require('node:child_process'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..');let browser,server;
(async()=>{
 const origin='http://127.0.0.1:18436',base=origin+'/eldi-edu/online/';
 server=spawn('php',['-S','127.0.0.1:18436','-t',path.join(root,'website')],{env:{...process.env,ELDI3333_CONFIG:path.join(root,'.qa-config.php')},stdio:'ignore'});
 for(let i=0;i<50;i++){try{await fetch(base);break;}catch{await new Promise(r=>setTimeout(r,100));}}
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const teacher=await browser.newPage({viewport:{width:1366,height:900}}),student=await browser.newPage({viewport:{width:390,height:844}}),device=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];
 for(const p of [teacher,student,device])p.on('pageerror',e=>errors.push(e.message));
 const fixture=JSON.parse(fs.readFileSync(path.join(root,'.qa-online.json'),'utf8'));
 async function login(p,username,password){await p.goto(base+'#ucenik');await p.locator('#username').fill(username);await p.locator('#password').fill(password);await p.locator('#login button').click();await p.waitForSelector('.heading');}
 await login(teacher,fixture.teacher.username,fixture.teacher.password);
 await teacher.locator('#class-title').fill('Komplet119 web provjera');await teacher.locator('#class-form button').click();await teacher.getByRole('button',{name:'Komplet119 web provjera',exact:true}).click();await teacher.locator('#toggle-invite').click();
 await teacher.locator('#roster-tests').click();for(const key of ['practice-sum','practice-maximum','practice-series'])await teacher.locator('input[name=bank][value="'+key+'"]').check();
 await teacher.locator('#section-form > button.primary').click();await teacher.getByRole('button',{name:'Komplet119 web provjera',exact:true}).click();
 await student.goto(base+'#ucenik');assert.equal(await student.locator('#register-link').innerText(),'Registruj me');await student.locator('#register-link').click();
 await student.locator('#join-class').selectOption({label:'Komplet119 web provjera'});await student.locator('#join-name').fill('Učenik komplet119');await student.locator('#join-school').selectOption({index:1});await student.locator('#join-username').fill('komplet119.web.qa');await student.locator('#join-password').fill('Complete119-Web-QA-password');await student.locator('#join-confirm').fill('Complete119-Web-QA-password');await student.locator('#registration-form button').click();await student.waitForSelector('#login');await student.locator('#password').fill('Complete119-Web-QA-password');await student.locator('#login button').click();await student.waitForSelector('#student-refresh');assert.equal(await student.locator('[data-assignment]').count(),0);
 await teacher.locator('#refresh-requests').click();await teacher.locator('[data-approve]').click();await student.locator('#student-refresh').click();await student.waitForSelector('[data-assignment]');
 const choose=title=>student.locator('article.panel').filter({hasText:title}).locator('[data-assignment]').click();
 await choose('Praktično · Zbir dva broja');await student.locator('#program-source').fill('a = int(input())\nb = int(input())\nprint(a + b)');await student.locator('#program-try').click();await student.waitForFunction(()=>document.getElementById('program-output').textContent.includes('2 / 2'));
 student.on('dialog',d=>d.accept());await student.locator('#program-submit').click();await student.waitForSelector('.score');assert.equal(await student.locator('.score').innerText(),'100 / 100');await student.locator('#student-certificate').click();await student.waitForSelector('.certificate');assert.match(await student.locator('.certificate').innerText(),/Ocjena aktivnosti: 5/);await student.locator('#certificate-back').click();await student.locator('#back').click();
 await choose('Praktično · Veći broj');await student.locator('#program-language').selectOption('blocks');await student.waitForSelector('.blocklySvg');
 await student.evaluate(()=>{Blockly.serialization.workspaces.load({blocks:{languageVersion:0,blocks:[{type:'task_read',x:20,y:20,fields:{NAME:'a'},next:{block:{type:'task_read',fields:{NAME:'b'},next:{block:{type:'task_if',fields:{EXPR:'a > b'},inputs:{DO:{block:{type:'task_print',fields:{EXPR:'a'}}},ELSE:{block:{type:'task_print',fields:{EXPR:'b'}}}}}}}}}]}},practicalWorkspace);});
 await student.locator('#program-try').click();await student.waitForFunction(()=>document.getElementById('program-output').textContent.includes('2 / 2'));assert.equal(await student.evaluate(()=>practicalWorkspace.getAllBlocks(false).length),5);
 assert(await student.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2));
 fs.mkdirSync(path.join(root,'.qa-sections'),{recursive:true});await student.screenshot({path:path.join(root,'.qa-sections/practical-blocks-mobile.png'),fullPage:true});
 await student.locator('#program-submit').click();await student.waitForSelector('.score');assert.equal(await student.locator('.score').innerText(),'100 / 100');await student.locator('#back').click();
 await choose('Praktično · Zbir od 1 do n');await student.locator('#program-source').fill('n = int(input())\ns = 0\nfor i in range(1, n + 1):\n    s += i\nprint(s)');await student.locator('#program-try').click();await student.waitForFunction(()=>document.getElementById('program-output').textContent.includes('2 / 2'));
 await student.setViewportSize({width:1366,height:900});await student.screenshot({path:path.join(root,'.qa-sections/practical-python.png'),fullPage:true});
 await student.locator('#back').click();await student.locator('.heading a').click();await student.waitForFunction(()=>window.__eldiReady===true);await student.locator('#web33-name').fill('Rad sa prvog uređaja');await student.waitForFunction(()=>document.getElementById('cloud-status').textContent.startsWith('Sačuvano na računu'));
 await login(device,'komplet119.web.qa','Complete119-Web-QA-password');await device.locator('.heading a').click();await device.waitForFunction(()=>window.__eldiReady===true);assert.equal(await device.locator('#web33-name').inputValue(),'Rad sa prvog uređaja');await device.locator('#web33-name').fill('Rad sa drugog uređaja');await device.waitForFunction(()=>document.getElementById('cloud-status').textContent.startsWith('Sačuvano na računu'));
 await student.locator('#web33-name').fill('Lokalna kopija nakon sukoba');await student.waitForFunction(()=>document.getElementById('cloud-status').textContent.includes('drugom uređaju'));assert.equal(await student.locator('#web33-name').inputValue(),'Lokalna kopija nakon sukoba');
 const downloadEvent=student.waitForEvent('download');await student.locator('#cloud-copy').click();const download=await downloadEvent;const downloadPath=await download.path();assert.equal(JSON.parse(fs.readFileSync(downloadPath,'utf8')).profile.name,'Lokalna kopija nakon sukoba');
 await student.locator('#cloud-load').click();await student.waitForFunction(()=>document.getElementById('web33-name').value==='Rad sa drugog uređaja');await student.screenshot({path:path.join(root,'.qa-sections/cloud-workshop.png'),fullPage:true});
 // Another account cannot cause an already open workshop to write under its identity.
 const otherTab=await student.context().newPage();await otherTab.goto(base);await otherTab.locator('#logout').click();await otherTab.locator('#username').fill(fixture.teacher.username);await otherTab.locator('#password').fill(fixture.teacher.password);await otherTab.locator('#login button').click();await otherTab.waitForSelector('#class-form');await student.locator('#web33-name').fill('Ne šalji nastavniku');await student.waitForFunction(()=>document.getElementById('cloud-status').textContent.includes('račun promijenjen'));
 assert.deepEqual(errors,[]);console.log('Complete119 Chromium: simple registration and approval; Python/Blockly execution and grades; mobile; diploma; two-device sync/conflict copy; account switch isolation PASS');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill();});
