'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),A=require('../app/edition3333-engine.js'),E=require('../app/studio33-engine.js');
test('35 teaching units cover five grades and both subjects, with usable differentiated questions',()=>{assert.equal(A.lessons.length,35);assert.equal(new Set(A.lessons.map(x=>x.id)).size,35);let checked=0;for(const grade of [5,6,7,8,9]){assert.equal(A.lessons.filter(x=>x.grade===grade).length,7);for(const subject of ['m','i'])assert(A.lessons.some(x=>x.grade===grade&&x.subject===subject));}for(const l of A.lessons)for(const d of [1,2,3])for(const seed of [1,2,3,8,17,42,99]){const q=A.task(l.id,d,seed);assert(q.question.length>8&&q.solution.length>8&&q.hint.length>20);assert(Number.isFinite(q.answer));assert(A.check(q,String(q.answer)),q.id);assert(!A.check(q,String(q.answer+1)),q.id);assert(!A.check(q,''));checked++;}assert.equal(checked,735);assert.equal(A.phases.reduce((n,p)=>n+p[1],0),45);});
test('Answer parser accepts decimal commas and fractions, rejects expressions, infinity and division by zero',()=>{assert.equal(A.number(' 3,5 '),3.5);assert.equal(A.number('−3/2'),-1.5);for(const v of ['','1/0','Infinity','2+3','0x10','1;alert(1)','--1'])assert(Number.isNaN(A.number(v)));assert(A.check({answer:2/3,tolerance:1e-6},'2/3'));});
test('Independent mathematical keys include geometric and algorithmic boundary cases',()=>{assert.equal(A.task('operations',1,1).answer,12);assert.equal(A.task('rectangle',3,1).answer,24);assert.equal(A.task('pythagoras',2,1).answer,36);assert.equal(A.task('cylinder',3,1).answer,27);assert.equal(A.task('statistics',2,1).answer,7);assert.equal(A.task('recursion',2,1).answer,4);assert.equal(A.task('complexity',3,1).answer,6);assert.equal(A.task('graph',3,1).answer,2);});
test('Full solid measurements use analytic formulae independent of position and orientation',()=>{const cube=E.object({type:'cube',a:2}),m=A.measures(cube);assert.equal(m.volume,8);assert.equal(m.area,24);const cuboid=A.measures(E.object({type:'cuboid',a:2,b:3,h:4}));assert.equal(cuboid.volume,24);assert.equal(cuboid.area,52);const cylinder=A.measures(E.object({type:'cylinder',r:2,h:3}));assert(Math.abs(cylinder.volume-12*Math.PI)<1e-9);assert(Math.abs(cylinder.area-20*Math.PI)<1e-9);for(const t of E.TYPES){const a=E.object({type:t});const b={...a,x:8,y:-3,rx:91};assert.deepEqual(A.measures(a),A.measures(b));assert(A.measures(a).area>0);}const pyramid=A.measures(E.object({type:'pyramid',n:4,a:2,h:3}));assert(Math.abs(pyramid.volume-4)<1e-9);});
test('Practice recommendation focuses on missed or unseen grade topics, rounds retain grade and subject',()=>{const h=[{topic:'operations',ok:true},{topic:'fractions',ok:false}];const rec=A.recommend(h,5,'m');assert.equal(rec.at(-1).id,'operations');for(const g of [5,6,7,8,9])for(const subject of ['m','i']){const round=A.round({grade:g,subject,level:3,seed:2});assert.equal(round.length,10);assert(round.every(q=>q.grade===g&&q.subject===subject&&q.level===3));}const s=E.normalize({module:'lessons',extra:{edition3333:{history:h,round:{finished:true,score:3},clock:{remaining:500}}}});assert.equal(E.project(s).extra.edition3333.clock.remaining,500);});

test('Exported quizzes never repeat identical questions, including limited logic and graph variants',()=>{for(const l of A.lessons)for(const d of [1,2,3]){const qs=A.questions(l.id,d,17,6);assert(qs.length>=1&&qs.length<=6);assert.equal(new Set(qs.map(q=>q.question)).size,qs.length);assert(qs.every(q=>q.topic===l.id&&q.level===d&&A.check(q,q.answer)));}assert.equal(A.questions('graph',3).length,1);assert.equal(A.questions('logic',1).length,4);assert.equal(A.questions('operations',1).length,6);});
