'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {normalizeStore,compareVersion,releaseURL,createMaintenance}=require('../desktop/maintenance.cjs');
const sample=()=>({profiles:[{id:'student-1',name:'Učenik',results:{},drafts:{},apiKey:'must-not-export'}],active:'student-1',access_token:'must-not-export'});
test('backup normalization preserves profile IDs and excludes unknown secrets',()=>{const value=normalizeStore(sample());assert.equal(value.active,'student-1');assert.equal(value.profiles[0].name,'Učenik');assert.equal(value.profiles[0].apiKey,undefined);assert.equal(value.access_token,undefined);assert.throws(()=>normalizeStore({profiles:[...sample().profiles,...sample().profiles]}),/ponovljene/);});
test('version comparisons handle multi-digit components and reject unstable names',()=>{assert.equal(compareVersion('v11.0.0','10.5.1'),1);assert.equal(compareVersion('11.10.0','11.9.0'),1);assert.equal(compareVersion('11.0.0','11.0.0'),0);assert.equal(compareVersion('11.0.0-beta','11.0.0'),null);});
test('only exact GitHub release URLs can be opened',()=>{assert.ok(releaseURL('https://github.com/elvir585/eldi-edu/releases/tag/v11.0.0'));assert.ok(releaseURL('https://github.com/elvir585/eldi-edu/releases/download/v11.0.0/ELDI-EDU-11.0.0-Portable-x64.exe'));for(const url of ['file:///tmp/x','https://github.com.evil.test/elvir585/eldi-edu/releases/tag/v11.0.0','https://evil.test/x','https://github.com/elvir585/eldi-edu/releases/tag/v11.0.0?redirect=evil'])assert.equal(releaseURL(url),null);});
test('backups rotate five complete snapshots and reject traversal',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'eldi-backup-test-'));try{let tick=0;const service=createMaintenance({directory,version:'11.0.0',now:()=>new Date(Date.UTC(2026,9,8,12,0,tick++))});for(let i=0;i<7;i++){const value=sample();value.profiles[0].name='Učenik '+i;assert.equal((await service.backup(value)).saved,true);}const rows=await service.list();assert.equal(rows.length,5);const restored=await service.read(rows[0].id);assert.equal(restored.profiles[0].name,'Učenik 6');assert.equal(JSON.stringify(restored).includes('must-not-export'),false);await assert.rejects(()=>service.read('../secret.json'));assert.equal((await service.backup({...sample(),profiles:[{...sample().profiles[0],name:'Učenik 6'}]})).unchanged,true);}finally{await fs.rm(directory,{recursive:true,force:true});}});
test('update check uses stable release metadata and filters unsafe assets',async()=>{let requested;const service=createMaintenance({directory:'/unused',version:'10.5.1',fetchImpl:async(url)=>{requested=url;return{ok:true,text:async()=>JSON.stringify({tag_name:'v11.0.0',html_url:'https://github.com/elvir585/eldi-edu/releases/tag/v11.0.0',assets:[{name:'good.exe',size:4,browser_download_url:'https://github.com/elvir585/eldi-edu/releases/download/v11.0.0/good.exe'},{name:'bad',browser_download_url:'https://evil.test/bad'}]})};}});const result=await service.updates();assert.equal(result.available,true);assert.equal(result.assets.length,1);assert.match(requested,/api.github.com\/repos\/elvir585\/eldi-edu\/releases\/latest/);});
