'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'smoke-previews/studio33');let browser,server;
(async()=>{
 fs.mkdirSync(out,{recursive:true});
 server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.wasm':'application/wasm','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const executablePath=process.env.ELDI_CHROMIUM_PATH;const args=process.env.ELDI_CHROMIUM_ARGS?JSON.parse(process.env.ELDI_CHROMIUM_ARGS):['--no-sandbox','--disable-dev-shm-usage'];if(executablePath)fs.chmodSync(executablePath,0o755);browser=await chromium.launch({...(executablePath?{executablePath}:{}),headless:true,args});
 const page=await browser.newPage({viewport:{width:1540,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text().slice(0,180));});
 await page.goto(`http://127.0.0.1:${server.address().port}/renderer/index.html`);await page.waitForFunction(()=>window.__eldiReady);await page.evaluate(()=>go('studio33'));await page.waitForSelector('#s33-blockly .blocklySvg');
 await page.screenshot({path:path.join(out,'01-scene.png'),fullPage:true});
 await page.locator('#s33-run').click();await page.waitForFunction(()=>document.getElementById('s33-status').textContent.includes('Program završen'),{timeout:20000});assert.equal(await page.evaluate(()=>ELDIStudio33.debug().work.scene.find(o=>o.id==='valjak').h),10);await page.locator('#s33-check').click();assert.match(await page.locator('#s33-status').innerText(),/100\/100/);
 await page.locator('#s33-cut').click();await page.locator('#s33-tiltx').fill('30');await page.locator('#s33-tiltx').dispatchEvent('input');assert.match(await page.locator('#s33-scene-info').innerText(),/Površina/);
 await page.locator('#s33-type').selectOption('cube');await page.locator('#s33-net').click();await page.locator('#s33-unfold').fill('100');await page.locator('#s33-unfold').dispatchEvent('input');await page.screenshot({path:path.join(out,'02-net.png'),fullPage:true});
 await page.locator('#s33-save-project').click();await page.locator('[data-s33-module=robot]').click();await page.locator('#s33-run').click();await page.waitForFunction(()=>document.getElementById('s33-status').textContent.includes('Program završen'),{timeout:20000});assert.match(await page.locator('#s33-robot-info').innerText(),/Cilj dostignut/);
 await page.locator('[data-s33-module=web]').click();await page.waitForFunction(()=>document.querySelector('#s33-web-console').textContent.includes('ready'));await page.locator('#s33-web-run').click();await page.waitForTimeout(700);await page.frameLocator('#s33-web-frame').locator('#pozdrav').click();assert.match(await page.frameLocator('#s33-web-frame').locator('#odgovor').innerText(),/Pozdrav/);await page.screenshot({path:path.join(out,'03-web.png'),fullPage:true});
 await page.locator('[data-s33-module=sql]').click();await page.waitForSelector('#s33-sql-result td');assert.match(await page.locator('#s33-sql-result').innerText(),/Mali princ/);await page.locator('#s33-sql-check').click();await page.waitForFunction(()=>document.querySelector('#s33-status').textContent.includes('očekivane'));await page.screenshot({path:path.join(out,'04-sql.png'),fullPage:true});
 for(const module of ['algorithms','logic','network','data','debug','contest','projects','reports']){await page.locator(`[data-s33-module=${module}]`).click();await page.waitForTimeout(100);await page.screenshot({path:path.join(out,module+'.png'),fullPage:true});}
 await page.locator('[data-s33-module=debug]').click();await page.evaluate(()=>{const el=document.getElementById('s33-debug-code');el.value='var a=read33(),b=read33();print33(a+b);';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#s33-debug-test').click();await page.waitForFunction(()=>document.getElementById('s33-status').textContent.includes('4/4'));
 await page.locator('[data-s33-module=contest]').click();await page.locator('#s33-contest-start').click();await page.locator('[data-contest-answer="0"]').fill('5');await page.locator('#s33-contest-finish').click();assert.match(await page.locator('#s33-contest-result').innerText(),/Rezultat/);
 await page.evaluate(()=>ELDIStorage.flush());await page.reload();await page.waitForFunction(()=>window.__eldiReady);await page.evaluate(()=>go('studio33'));assert(await page.evaluate(()=>ELDIStudio33.debug().work.reports.length)>=3);assert(await page.evaluate(()=>ELDIStudio33.debug().work.projects.length)>=1);
 for(const size of [{width:1366,height:768},{width:1008,height:655},{width:911,height:640}]){await page.setViewportSize(size);for(const module of ['scene','web','sql','projects']){await page.locator(`[data-s33-module=${module}]`).click();const dims=await page.evaluate(()=>({w:document.documentElement.clientWidth,s:document.documentElement.scrollWidth}));assert(dims.s<=dims.w+2,JSON.stringify({size,module,dims}));}}
 assert.deepEqual(errors,[]);console.log('STUDIO33 UI PASS');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
