'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app/studio33-engine.js'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {debugTasks,quizBank,projects}=require('../renderer/studio33/tasks.js');
function runWorker(code,input='',scene=[]){return new Promise((resolve,reject)=>{let last;const timers=new Set(),timeout=setTimeout(()=>{cleanup();reject(Error('Worker did not finish'));},8000);function cleanup(){clearTimeout(timeout);for(const t of timers)clearTimeout(t);}const sandbox={console,Date,Math,Set,Map,JSON,Object,Number,String,Boolean,Array,Error,setTimeout(fn,ms){const t=setTimeout(fn,Math.min(ms,2));timers.add(t);return t;},clearTimeout,postMessage(m){if(m.frame)last=m.frame;if(m.type==='done'){cleanup();resolve(last);}if(m.type==='failure'){cleanup();reject(Error(m.message));}}};sandbox.self=sandbox;sandbox.importScripts=(...names)=>{for(const n of names)vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../renderer',n),'utf8'),ctx);};const ctx=vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../renderer/studio33-worker.js'),'utf8'),ctx);ctx.onmessage({data:{code,input,scene,speed:0}});});}
test('Studio 33 real interpreter verifies all 80 reference cases and exposes faults',async()=>{let cases=0;for(const task of debugTasks){let failedBug=false;for(const [input,expected]of task.tests){const result=await runWorker(task.solution,input);assert.equal(result.output.trim().replace(/\s+/g,' '),expected,task.id);cases++;if(!failedBug){try{const r=await runWorker(task.bug,input);if(r.output.trim()!==expected)failedBug=true;}catch{failedBug=true;}}}assert(failedBug,task.id+' needs an observable failing test');}assert.equal(cases,80);});
test('Named solids, bounded transformations and robot state use actual worker operations',async()=>{const r=await runWorker('clear33();solid33("a","cylinder",2,5);for(var i=0;i<5;i++){trace33("loop");set33("a","h",get33("a","h")+1);}print33(get33("a","h"));');assert.equal(r.objects[0].h,10);assert.equal(r.output.trim(),'10');await assert.rejects(runWorker('solid33("a","sphere",2,2);solid33("a","sphere",2,2);'),/postoji/);const bot=await runWorker('for(var i=0;i<4;i++)forward33();turn33(1);for(var i=0;i<4;i++)forward33();');assert.equal(bot.robot.goal,true);});
test('Project and profile state preserve new module data without accepting prototype keys',()=>{const s=E.normalize({extra:{gates:[{op:'XOR',a:'A',b:'B'}]},robotWorkspace:{blocks:[]},scene:[{id:'a',type:'cube',a:4}],reports:[{name:'test',score:7,max:10,grade:'4'}]});assert.equal(s.scene[0].a,4);assert.equal(E.project(s).extra.gates[0].op,'XOR');assert.equal(s.reports[0].grade,'4');assert.throws(()=>E.safeData(JSON.parse('{"__proto__":{"admin":true}}')),/ključ/);});
test('Visual criteria use tolerances and separate criterion points',()=>{const rules=[{kind:'property',id:'v',property:'h',expected:10,tolerance:.01,points:40},{kind:'robot',expected:true,points:60}];const r=E.evaluate(rules,{objects:[{id:'v',h:10.005}],robot:{goal:false}});assert.equal(r.score,40);assert.equal(r.max,100);assert.equal(E.evaluate(rules,{objects:[{id:'v',h:11}],robot:{goal:true}}).score,60);});
test('Algorithms maintain state, comparison counts and correct recursion results',()=>{for(const kind of ['bubble','insertion']){const f=E.algorithms(kind,[4,-2,4,0]).at(-1);assert.deepEqual(f.values,[-2,0,4,4]);assert(f.comparisons>0);}assert.equal(E.algorithms('recursion',[5]).at(-1).value,120);assert.match(E.algorithms('binary',[1,2,4],3).at(-1).note,/nije/);assert.deepEqual(E.algorithms('graph',[]).at(-1).visited,[0,1,2,3,4,5]);});
test('Robot collision, line sensor, network reachability and CPU execution are real',()=>{const b=E.robot();assert.equal(b.distance(),5);b.turn(-1);assert.equal(b.forward(),false);assert.equal(b.state().crashes,1);assert.deepEqual(E.networkPath([[0,1],[1,2]],0,2),[0,1,2]);assert.deepEqual(E.networkPath([[0,1]],0,2),[]);assert.equal(E.cpu('LOAD 3\nSUB 1\nJNZ 1\nHALT').at(-1).acc,0);assert.throws(()=>E.cpu('LOAD 1\nJNZ 1'),/200/);});
test('Truth tables, quoted CSV and numeric summaries include boundaries',()=>{assert.deepEqual(E.truth([{op:'XOR',a:'A',b:'B'}]).map(r=>r.G0),[0,1,1,0]);assert.throws(()=>E.truth([{op:'AND',a:'G1',b:'B'}]),/prethodno/);assert.deepEqual(E.csv('a,b\n"x,y",2\n"z\"\"z",3').rows,[['x,y','2'],['z"z','3']]);assert.throws(()=>E.csv('a,b\n1,2,3'),/isti/);assert.equal(E.stats([1,4,2,3]).median,2.5);});
test('Every grade has original mathematics and informatics practice with finite keys',()=>{for(const grade of [5,6,7,8,9])for(let v=0;v<4;v++){const math=quizBank(grade,'math',v),info=quizBank(grade,'informatics',v);assert.equal(math.length,8);assert.equal(info.length,4);for(const q of [...math,...info])assert(Number.isFinite(q.answer)&&q.explanation&&q.statement);}assert.equal(projects.length,16);assert.equal(quizBank(9,'math',1)[0].answer,20);});

test('Full learner profile round-trip retains Studio 33 with its existing schema',()=>{const P=require('../renderer/profile.js');const profile={id:'studio33-profile',name:'Provjera',results:{},drafts:{},blocks:null,studio33Work:E.normalize({module:'web',web:{html:'<h1>Moj rad</h1>'},database:'U1FMaXRl',robotWorkspace:{blocks:[]},extra:{lastWorkModule:'web'}})};const restored=P.importProfile(P.exportProfile(profile));assert.equal(restored.studio33Work.web.html,'<h1>Moj rad</h1>');assert.equal(restored.studio33Work.extra.lastWorkModule,'web');assert.equal(restored.studio33Work.database,'U1FMaXRl');});
