'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const T=require('../app/teacher-engine.js');
const E=require('../app/exam-engine.js');
const clone=v=>JSON.parse(JSON.stringify(v));
function classroom(grade=6){const teacher={id:'teacher-1',name:'Nastavnik',teacherWork:T.normalizeState()},student={id:'student-profile-1',name:'Učenik',exams:[]},state=teacher.teacherWork,c=T.createClass(state,{name:`${grade}-2`,gradeLevel:grade});T.addStudent(state,c.id,{name:student.name,profileId:student.id});return{teacher,student,state,c};}
function assignment(state,c,options={}){return T.createAssignment(state,{classId:c.id,name:'Samostalni rad',teacherName:'Nastavnik',subject:'math',count:10,seed:7,difficulty:'medium',thresholds:[50,65,80,90],...options});}
function submit(student,a,correct=a.count){T.distribute(a,student);const session=T.startAssignment(student.teacherWork,a.id,student.name);for(let i=0;i<correct;i++){const task=E.resolve(session.refs[i]);session.answers[i]=Object.fromEntries(task.fields.map(f=>[f.key,Array.isArray(f.answer)?(f.answer.length?f.answer.join('; '):'nema'):String(f.answer)]));}session.notes[0]='Prvo čitam zadatak, zatim računam.';const result=T.finishAssignment(student.teacherWork);student.exams.push(result);return result;}

test('Teacher state normalizes optional fields without sharing mutable arrays',()=>{const first=T.normalizeState(),second=T.normalizeState();assert.deepEqual(first,{schema:1,classes:[],assignments:[],submissions:[],reviews:[],activeSession:null});first.classes.push({});assert.equal(second.classes.length,0);assert.throws(()=>T.normalizeState({schema:2}));});

test('Classes and roster validate grades, duplicate profile links, unsafe identities and limits',()=>{const {state,c}=classroom();assert.throws(()=>T.createClass(state,{name:'',gradeLevel:6}));assert.throws(()=>T.createClass(state,{name:'IV',gradeLevel:4}));assert.throws(()=>T.addStudent(state,c.id,{name:'Drugi',profileId:'student-profile-1'}));assert.throws(()=>T.addStudent(state,c.id,{name:'Učenik',profileId:'__proto__'}));const bad=clone(state);bad.classes.push(clone(bad.classes[0]));assert.throws(()=>T.normalizeState(bad));const limits=T.normalizeState();limits.classes=Array.from({length:T.LIMITS.classes+1},()=>clone(c));assert.throws(()=>T.normalizeState(limits));});

test('Assignments support every count and both subjects in all grades with stable unique tasks',()=>{for(const grade of [5,6,7,8,9])for(const subject of ['math','informatics','mixed'])for(const count of [1,10,50]){const {state,c}=classroom(grade),a=assignment(state,c,{subject,count});assert.equal(a.refs.length,count);assert.equal(a.gradeLevel,grade);assert.equal(new Set(a.refs.map(r=>JSON.stringify(r))).size,count);const normalized=T.normalizeState(state);assert.deepEqual(normalized.assignments[0],a);}});

test('Selecting one mathematics skill produces distinct variants and informatics focus requires one task',()=>{const {state,c}=classroom(5),lesson=T.lessons('math',5)[0],a=assignment(state,c,{count:50,lessonId:lesson.id});assert(a.refs.every(r=>r.topicId===lesson.id));assert.equal(new Set(a.refs.map(r=>r.seed)).size,50);const info=T.lessons('informatics',5)[0];assert.throws(()=>assignment(state,c,{subject:'informatics',count:10,lessonId:info.id}));const one=assignment(state,c,{subject:'informatics',count:1,lessonId:info.id});assert.equal(one.refs[0].lessonId,info.id);});

test('Assignment import preserves identity, avoids duplicate imports and rejects conflicting content',()=>{const {state,c}=classroom(),a=assignment(state,c),target=T.normalizeState(),pack=T.exportAssignment(a);T.importAssignment(target,pack);T.importAssignment(target,clone(pack));assert.equal(target.assignments.length,1);assert.deepEqual(target.assignments[0],a);const altered=clone(pack);altered.assignment.refs[0].seed=altered.assignment.refs[0].seed===200?1:altered.assignment.refs[0].seed+1;assert.throws(()=>T.importAssignment(target,altered),/drugačiji sadržaj/);assert.throws(()=>T.importAssignment(target,{format:'UNTRUSTED',assignment:a}));const switched=clone(pack);switched.assignment.classId='different-class';assert.throws(()=>T.importAssignment(target,switched));});

test('Normalization rejects duplicated tasks, foreign grade references and invalid thresholds',()=>{const {state,c}=classroom(),a=assignment(state,c),bad=clone(a);bad.refs[1]=clone(bad.refs[0]);assert.throws(()=>T.normalizeAssignment(bad));const wrong=clone(a);wrong.refs[0]={kind:'math',topicId:T.lessons('math',5)[0].id,seed:1,difficulty:'medium'};assert.throws(()=>T.normalizeAssignment(wrong));assert.throws(()=>T.normalizeAssignment({...a,thresholds:[80,65,85,90]}));assert.throws(()=>T.normalizeAssignment({...a,count:51}));});

test('Assignment answers survive safe profile-state normalization and grading uses the existing scale',()=>{const {state,c,student}=classroom(8),a=assignment(state,c,{count:20});T.distribute(a,student);const session=T.startAssignment(student.teacherWork,a.id,student.name);session.answers[0]={answer:'3/4'};session.notes[0]='Uzimam zajednički imenilac.';const restored=T.normalizeState(student.teacherWork);assert.deepEqual(restored.activeSession.session.answers,session.answers);assert.equal(restored.activeSession.session.notes[0],session.notes[0]);for(const [correct,grade]of [[0,1],[10,2],[13,3],[16,4],[18,5]]){const learner={id:'learner-'+correct,name:'Učenik',exams:[]},result=submit(learner,a,correct);assert.equal(result.correct,correct);assert.equal(result.gradeResult.grade,grade);assert.equal(learner.teacherWork.activeSession,null);assert.equal(learner.teacherWork.submissions[0].examId,result.id);}});

test('Forged session tasks and unsupported answer keys are rejected before grading',()=>{const {state,c,student}=classroom(),a=assignment(state,c);T.distribute(a,student);T.startAssignment(student.teacherWork,a.id,student.name);const bad=clone(student.teacherWork);bad.activeSession.session.refs[0].seed+=1;assert.throws(()=>T.normalizeState(bad));const unsafe=clone(student.teacherWork);unsafe.activeSession.session.answers[0]=JSON.parse('{"__proto__":"injected"}');assert.throws(()=>T.normalizeState(unsafe));const extra=clone(student.teacherWork);extra.activeSession.session.notes[999]='Nepripadajuća bilješka';assert.throws(()=>T.normalizeState(extra));});

test('Dashboard consolidates actual local answers and recalculates rather than trusting saved marks',()=>{const {state,c,student}=classroom(),a=assignment(state,c),exam=submit(student,a,6);exam.correct=10;exam.percentage=100;exam.gradeResult.grade=5;let rows=T.report(state,[student],c.id);assert.equal(rows.length,1);assert.equal(rows[0].correct,6);assert.equal(rows[0].percentage,60);assert.equal(rows[0].grade,2);assert.equal(rows[0].studentName,'Učenik');const forged=clone(student);forged.exams[0].refs[0].seed+=1;forged.teacherWork.submissions[0].result.refs[0].seed+=1;rows=T.report(state,[forged],c.id);assert.equal(rows[0].status,'Čeka predaju');assert.equal(rows[0].correct,null);});

test('Missing links and unsubmitted students remain explicit while repeated attempts remain separate',()=>{const {state,c,student}=classroom(),a=assignment(state,c);T.addStudent(state,c.id,{name:'Novi učenik'});let rows=T.report(state,[student],c.id);assert.deepEqual(rows.map(r=>r.status),['Čeka predaju','Profil nije povezan']);submit(student,a,5);submit(student,a,8);rows=T.report(state,[student],c.id);assert.equal(rows.filter(r=>r.examId).length,2);assert.deepEqual(rows.filter(r=>r.examId).map(r=>r.correct),[5,8]);});

test('Teacher review retains automatic marks, displays a separate manual grade and updates one review',()=>{const {state,c,student}=classroom(),a=assignment(state,c),exam=submit(student,a,5);T.reviewSubmission(state,{assignmentId:a.id,examId:exam.id,profileId:student.id,comment:'Dobar postupak, provjeri treći zadatak.',manualGrade:4});let row=T.report(state,[student],c.id)[0];assert.equal(row.grade,2);assert.equal(row.manualGrade,4);assert(row.reviewedAt);T.reviewSubmission(state,{assignmentId:a.id,examId:exam.id,profileId:student.id,comment:'Pregledano.',manualGrade:null});assert.equal(state.reviews.length,1);row=T.report(state,[student],c.id)[0];assert.equal(row.comment,'Pregledano.');assert.equal(row.manualGrade,null);assert.throws(()=>T.reviewSubmission(state,{assignmentId:a.id,examId:exam.id,profileId:student.id,manualGrade:6}));assert.deepEqual(T.normalizeState(state),state);});

test('Due dates enforce real calendar dates and treat end of selected day as inclusive',()=>{const {state,c}=classroom();assert.throws(()=>assignment(state,c,{dueDate:'2026-02-30'}));assert.throws(()=>assignment(state,c,{dueDate:'8.10.2026'}));const due='2026-10-08';assert.equal(T.isLate(due,new Date(2026,9,8,23,59,59).toISOString()),false);assert.equal(T.isLate(due,new Date(2026,9,9,0,0,0).toISOString()),true);assert.equal(T.isLate('',new Date().toISOString()),false);});

test('CSV exports escape separators, quotes, newlines and spreadsheet formula injection',()=>{assert.equal(T.csvCell('Dino; Elvir'), '"Dino; Elvir"');assert.equal(T.csvCell('"Dobro"'),'"""Dobro"""');for(const s of ['=SUM(1;2)','+1','-1','@cmd','  =A1','\tformula','\rformula','\nformula'])assert(T.csvCell(s).startsWith('"\''),JSON.stringify(s));const csv=T.csvReport([{className:'VI-2',studentName:'=HYPERLINK("x")',assignmentName:'Razlomci; provjera',status:'Predano',correct:8,total:10,percentage:80,grade:4,manualGrade:null,finishedAt:'2026-10-08T10:00:00Z',reviewedAt:'',comment:'Dobar rad\nNastavi.'}]);assert(csv.startsWith('\uFEFF'));assert(csv.includes('"\'=HYPERLINK(""x"")"'));assert(csv.includes('"Razlomci; provjera"'));assert(csv.includes('"80.0"'));assert(csv.includes('"Dobar rad\nNastavi."'));});

test('Profile state rejects duplicate submissions and reviews, unknown assignments and huge text',()=>{const {state,c,student}=classroom(),a=assignment(state,c);submit(student,a);const bad=clone(student.teacherWork);bad.submissions.push(clone(bad.submissions[0]));assert.throws(()=>T.normalizeState(bad));const missing=clone(student.teacherWork);missing.submissions[0].assignmentId='missing';assert.throws(()=>T.normalizeState(missing));assert.throws(()=>T.normalizeAssignment({...a,instructions:'x'.repeat(6001)}));const nulled=T.normalizeState({schema:1,classes:[],assignments:[],submissions:[],reviews:[],activeSession:null});assert.equal(nulled.classes.length,0);});

test('Assignment snapshots retain actual results and notes after shared exam history is cleared',()=>{const {state,c,student}=classroom(),a=assignment(state,c);submit(student,a,8);student.exams=[];student.teacherWork=T.normalizeState(student.teacherWork);const row=T.report(state,[student],c.id)[0];assert.equal(row.correct,8);assert.equal(row.grade,4);assert.equal(row.result.notes[0],'Prvo čitam zadatak, zatim računam.');assert.equal(row.status,'Predano');});

test('Snapshot normalization rejects invented saved grades and mismatched result identity',()=>{const {state,c,student}=classroom(),a=assignment(state,c);submit(student,a,5);const forged=clone(student.teacherWork);forged.submissions[0].result.gradeResult.grade=5;assert.throws(()=>T.normalizeState(forged),/ne odgovara odgovorima/);const identity=clone(student.teacherWork);identity.submissions[0].examId='another-exam';assert.throws(()=>T.normalizeState(identity));});
