import {debugTasks,quizBank,projects} from './tasks.js';
import {esc,E,$,table,edit,note,download,report,field} from './common.js';
import {setupBlocks,toolbox,generate} from './blocks.js';
export function debugUI(c){let selected=debugTasks[0],editor,worker,testing=false,workspace=null,stage='repair',disposed=false;const w=c.work;
 c.body.innerHTML=`<div class="s33-controls"><label>Zadatak<select id="s33-debug-task">${debugTasks.map((t,i)=>`<option value="${i}">${t.grade}. · ${t.title}</option>`).join('')}</select></label><label>Način rada<select id="s33-debug-stage"><option value="repair">Ispravi grešku</option><option value="blocks">Složi blokove</option><option value="complete">Dopuni kod</option><option value="independent">Napiši samostalno</option></select></label><button id="s33-debug-run" class="primary">▶ Pokreni</button><button id="s33-debug-test">Svi testovi</button><button id="s33-debug-stop">Prekini</button><button id="s33-debug-solution">Prikaži rješenje</button><button id="s33-debug-export">Izvezi zadatak</button></div><p id="s33-debug-statement" class="s33-task"></p><div class="s33-two"><div class="s33-panel"><div id="s33-debug-blocks" hidden style="height:440px"></div><textarea id="s33-debug-code" aria-label="Program za provjeru"></textarea><label>Objašnjenje ispravke<textarea id="s33-debug-explanation">${esc(w.extra.debugExplanation||'')}</textarea></label></div><div class="s33-panel"><label>Ulaz<textarea id="s33-debug-input"></textarea></label><h3>Rezultat</h3><pre id="s33-debug-output" role="status"></pre><h3>Moji dodatni testovi</h3><p>JSON niz: objekti s poljima input i output. Dodaj nulu, negativan broj ili najmanji dopušteni ulaz.</p><textarea id="s33-debug-tests" aria-label="Dodatni testovi">[]</textarea><div id="s33-debug-results"></div></div></div>`;
 function code(){return stage==='blocks'?generate(workspace,'js'):$('s33-debug-code').value;}
 function run(code,input){return new Promise((resolve,reject)=>{const current=new Worker(c.asset('studio33-worker.js'));worker=current;const timer=setTimeout(()=>{current.terminate();if(worker===current)worker=null;reject(Error('Program je prekoračio vrijeme.'));},6500);current.onmessage=({data:m})=>{if(m.type==='done'){clearTimeout(timer);current.terminate();if(worker===current)worker=null;resolve({ok:true,output:m.frame.output});}if(m.type==='failure'){clearTimeout(timer);current.terminate();if(worker===current)worker=null;resolve({ok:false,output:'',error:m.message});}};current.onerror=e=>{clearTimeout(timer);current.terminate();reject(Error(e.message));};current.postMessage({code,input,scene:[],speed:0});});}
 function load(){const d=w.extra.debugDrafts||={};selected=debugTasks[+$('s33-debug-task').value];$('s33-debug-statement').textContent=selected.statement+' Za ulaz koristi read33(), za izlaz print33(). Kod JS podržava školski podskup ES5.';$('s33-debug-input').value=selected.tests[0][0];if(stage==='blocks'){setupBlocks();editor?.destroy();editor=null;$('s33-debug-code').hidden=true;$('s33-debug-blocks').hidden=false;if(!workspace)workspace=Blockly.inject('s33-debug-blocks',{toolbox,media:c.asset('vendor/media/'),scrollbars:true,trashcan:true,zoom:{controls:true,wheel:true}});else workspace.clear();note('Složi program koji čita podatke i ispisuje rezultat. Isti testovi važe i za blokove i za kod.');}else{workspace?.dispose();workspace=null;$('s33-debug-blocks').hidden=true;$('s33-debug-code').hidden=false;editor?.destroy();const template=stage==='independent'?'// Učitaj podatke, obradi ih i ispiši rezultat.\n':stage==='complete'?selected.solution.replace(/print33\([^;]+\);?\s*$/,'// DOPUNI: ispiši traženi rezultat.\n'):selected.bug;$('s33-debug-code').value=d[selected.id+'-'+stage]??template;editor=edit('s33-debug-code','javascript',()=>$('s33-debug-run').click());$('s33-debug-code').oninput=()=>{d[selected.id+'-'+stage]=$('s33-debug-code').value;c.save();};}$('s33-debug-results').replaceChildren();}
 $('s33-debug-task').onchange=load;$('s33-debug-stage').onchange=()=>{stage=$('s33-debug-stage').value;load();};$('s33-debug-explanation').oninput=()=>{w.extra.debugExplanation=$('s33-debug-explanation').value;c.save();};
 $('s33-debug-run').onclick=async()=>{if(testing)return;testing=true;try{const r=await run(code(),$('s33-debug-input').value);if(!disposed)$('s33-debug-output').textContent=r.ok?r.output:r.error;}catch(e){if(!disposed)note(e.message,true);}finally{testing=false;}};
 $('s33-debug-test').onclick=async()=>{if(testing)return;testing=true;try{const custom=JSON.parse($('s33-debug-tests').value);if(!Array.isArray(custom)||custom.length>20||custom.some(t=>typeof t.input!=='string'||typeof t.output!=='string'||t.input.length>10000||t.output.length>10000))throw Error('Dodatni testovi: do 20 objekata s tekstualnim input i output poljima.');const tests=[...selected.tests.map(([input,output])=>({input,output})),...custom],results=[],source=code();for(let i=0;i<tests.length&&testing;i++){const t=tests[i],r=await run(source,t.input),ok=r.ok&&r.output.trim().replace(/\s+/g,' ')===t.output.trim().replace(/\s+/g,' ');results.push([i+1,ok?'✓':'✗',t.input,t.output,r.ok?r.output:r.error]);if(disposed)return;$('s33-debug-results').innerHTML=table(['Test','Status','Ulaz','Očekivano','Dobijeno'],results);}if(!testing)return;const score=results.filter(r=>r[1]==='✓').length;report(c,'Program: '+selected.title,score,tests.length,results.map(r=>r.join(' | ')).join('\n')+'\nObjašnjenje: '+w.extra.debugExplanation);note(`${score}/${tests.length} testova prošlo. Objašnjenje pregleda nastavnik.`);}catch(e){if(!disposed)note(e.message,true);}finally{testing=false;}};
 $('s33-debug-stop').onclick=()=>{testing=false;worker?.terminate();worker=null;note('Provjera prekinuta; nezavršeni testovi ne donose rezultat.');};$('s33-debug-solution').onclick=()=>{$('s33-debug-output').textContent=selected.solution+'\n\nUporedi rješenje sa svojim kodom i objasni promjenu.';};$('s33-debug-export').onclick=()=>download('ELDI-33-programerski-zadatak.json',{format:'ELDI-33-CODE-TASK',task:selected,studentCode:code(),explanation:w.extra.debugExplanation});load();return()=>{disposed=true;testing=false;worker?.terminate();workspace?.dispose();editor?.destroy();};
}
export function contestUI(c){const w=c.work;let session=w.extra.contest||null,timer;
 c.body.innerHTML=`<div class="s33-panel"><h2>ELDI priprema za takmičenje</h2><p>Originalni školski zadaci za vježbu. Lokalni rezultat služi nastavi; ne predstavlja službeno takmičarsko rangiranje.</p><div class="s33-controls"><label>Razred<select id="s33-contest-grade">${[5,6,7,8,9].map(g=>`<option>${g}</option>`).join('')}</select></label><label>Oblast<select id="s33-contest-subject"><option value="math">Matematika</option><option value="informatics">Informatika</option><option value="mixed">Mješovito</option></select></label><label>Trajanje<select id="s33-contest-duration"><option value="15">15 minuta</option><option value="30">30 minuta</option><option value="45">45 minuta</option></select></label><button id="s33-contest-start" class="primary">Nova provjera</button><button id="s33-contest-finish">Predaj</button><button id="s33-contest-print">Štampaj zadatke</button><output id="s33-contest-clock"></output></div><div id="s33-contest-questions"></div><div id="s33-contest-result"></div></div>`;
 function questions(){if(!session)return[];return(session.subject==='mixed'?['math','informatics']:[session.subject]).flatMap(s=>quizBank(session.grade,s,session.variant));}
 function save(){w.extra.contest=session;c.save();}
 function render(){if(!session){$('s33-contest-questions').textContent='Izaberi razred i započni provjeru.';return;}const qs=questions();$('s33-contest-questions').innerHTML=qs.map((q,i)=>`<article class="s33-question"><h3>${i+1}. ${esc(q.title)} <small>${q.points} bodova</small></h3><p>${esc(q.statement)}</p><label>Brojčani odgovor<input data-contest-answer="${i}" inputmode="decimal" value="${esc(session.answers[i]||'')}" ${session.done?'disabled':''}></label>${session.done?`<p>${isCorrect(q,session.answers[i])?'✓ Tačno':'✗ Netačno'} · ${esc(q.explanation)} Odgovor: ${Number(q.answer.toFixed(8))}</p>`:''}</article>`).join('');c.body.querySelectorAll('[data-contest-answer]').forEach(el=>el.oninput=()=>{if(Date.now()>session.deadline){finish();return;}session.answers[+el.dataset.contestAnswer]=el.value;save();});if(session.done)$('s33-contest-result').textContent=`Rezultat: ${session.score}/${session.max} bodova.`;else $('s33-contest-result').replaceChildren();tick();}
 function isCorrect(q,a){if(typeof a!=='string'||!a.trim())return false;const n=Number(a.replace(',','.'));return Number.isFinite(n)&&Math.abs(n-q.answer)<1e-6;}
 function finish(){if(!session||session.done)return;const qs=questions();session.score=qs.reduce((s,q,i)=>s+(isCorrect(q,session.answers[i])?q.points:0),0);session.max=qs.reduce((s,q)=>s+q.points,0);session.done=true;report(c,'Takmičarska priprema · '+session.grade+'. razred',session.score,session.max,qs.map((q,i)=>`${q.title}: ${session.answers[i]||'bez odgovora'}; tačno ${q.answer}`).join('\n'));save();render();}
 function tick(){if(!session)return;if(session.done){$('s33-contest-clock').textContent='Završeno';return;}const seconds=Math.max(0,Math.ceil((session.deadline-Date.now())/1000));$('s33-contest-clock').textContent=`Preostalo ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(seconds===0)finish();}
 $('s33-contest-start').onclick=()=>{session={grade:+$('s33-contest-grade').value,subject:$('s33-contest-subject').value,variant:Math.floor(Math.random()*4),deadline:Date.now()+Number($('s33-contest-duration').value)*60000,answers:{},done:false};save();render();};$('s33-contest-finish').onclick=finish;$('s33-contest-print').onclick=()=>c.print();render();timer=setInterval(tick,1000);return()=>clearInterval(timer);
}
export function projectsUI(c){const w=c.work;
 c.body.innerHTML=`<div class="s33-project-grid">${projects.map(([name,module,grade,instructions,rules],i)=>`<article class="s33-project-card"><div class="s33-project-art art-${module}" aria-hidden="true">${{scene:'◇',robot:'↱',web:'{ }',sql:'▤',algorithms:'↗',logic:'⊕',network:'⌁',data:'▥',debug:'✓'}[module]}</div><p class="s33-caption">${grade}. razred · ${module}</p><h3>${esc(name)}</h3><p>${esc(instructions)}</p><button data-project-start="${i}">Otvori zadatak</button><button data-project-download="${i}">Preuzmi paket</button></article>`).join('')}</div><div class="s33-panel"><h2>Moji sačuvani projekti</h2><div class="s33-project-grid">${w.projects.map((p,i)=>`<article class="s33-project-card">${p.thumbnail.startsWith('data:image/png;base64,')?`<img src="${p.thumbnail}" alt="Sačuvani prikaz projekta ${esc(p.name)}">`:'<div class="s33-project-art">▣</div>'}<h3>${esc(p.name)}</h3><p>${esc(new Date(p.date).toLocaleString())}</p><button data-project-open="${i}">Nastavi</button><button data-project-file="${i}">Izvezi</button></article>`).join('')||'<p>U radionici klikni „Sačuvaj projekat“. Ovdje će se pojaviti tvoj rad.</p>'}</div></div><div class="s33-panel"><h2>Nastavnička projektna radionica</h2><p>U jednom paketu su uputa, početni rad i kriteriji provjere. Paket učenicima prosljeđuješ kao datoteku.</p>${field('s33-assignment-title','Naziv zadatka','Moj projektni zadatak')}<label>Uputa<textarea id="s33-assignment-instructions"></textarea></label><label>Kriteriji provjere (JSON)<textarea id="s33-assignment-rules">[{"kind":"property","id":"valjak","property":"h","expected":10,"tolerance":0.01,"points":100}]</textarea></label><p>Vrste kriterija: object (vrsta tijela), property (svojstvo uz toleranciju), robot (cilj), output (tačan tekst). Za tekstualno obrazloženje dodaj nastavnički komentar i ocjenu u Izvještajima.</p><button id="s33-assignment-export">Izvezi zadatak s trenutnim radom</button></div>`;
 function pack(i){const [title,module,grade,instructions,rules]=projects[i];return{format:'ELDI-33-ASSIGNMENT',version:1,assignment:E().assignment({title,instructions,grade,rules,starter:{module,title,scene:[E().object()],web:{},notes:''}})};}
 c.body.querySelectorAll('[data-project-start]').forEach(b=>b.onclick=()=>{const p=pack(+b.dataset.projectStart);w.assignment=p.assignment;w.title=p.assignment.title;w.notes='';c.switch(p.assignment.starter.module);note(p.assignment.instructions);});c.body.querySelectorAll('[data-project-download]').forEach(b=>b.onclick=()=>download('ELDI-33-zadatak-'+b.dataset.projectDownload+'.json',pack(+b.dataset.projectDownload)));
 c.body.querySelectorAll('[data-project-open]').forEach(b=>b.onclick=()=>{const p=w.projects[+b.dataset.projectOpen];c.applyProject(p.payload);});c.body.querySelectorAll('[data-project-file]').forEach(b=>b.onclick=()=>download('ELDI-33-projekat.json',{format:'ELDI-33-PROJECT',version:1,project:w.projects[+b.dataset.projectFile].payload}));
 $('s33-assignment-export').onclick=()=>{try{const assignment=E().assignment({title:$('s33-assignment-title').value,instructions:$('s33-assignment-instructions').value,rules:JSON.parse($('s33-assignment-rules').value),starter:{...E().project(w),module:w.extra.lastWorkModule||'scene'},grade:7});download('ELDI-33-nastavnicki-zadatak.json',{format:'ELDI-33-ASSIGNMENT',version:1,assignment});}catch(e){note(e.message,true);}};return()=>{};
}
export function reportsUI(c){const w=c.work;c.body.innerHTML=`<div class="s33-controls"><button id="s33-reports-csv">Izvezi CSV</button><button id="s33-reports-print">Štampaj izvještaj</button></div><div class="s33-panel"><h2>Izvještaj rada · ${esc(c.profileName())}</h2><p>Automatski bodovi i nastavnička ocjena čuvaju se odvojeno. Datum izvještaja: ${esc(new Date().toLocaleDateString('bs-BA'))}.</p>${w.reports.map((r,i)=>`<article class="s33-report"><h3>${esc(r.name)} · ${r.score}/${r.max}</h3><p>${esc(new Date(r.date).toLocaleString())}</p><pre>${esc(r.details)}</pre><div class="s33-controls"><label>Nastavnička ocjena<input data-report-grade="${i}" value="${esc(r.grade)}" maxlength="20"></label><label>Komentar<textarea data-report-comment="${i}" maxlength="3000">${esc(r.comment)}</textarea></label></div></article>`).join('')||'<p>Ovdje će se pojaviti rezultati završenih provjera.</p>'}</div>`;for(const key of ['grade','comment'])c.body.querySelectorAll('[data-report-'+key+']').forEach(el=>el.oninput=()=>{w.reports[Number(el.getAttribute('data-report-'+key))][key]=el.value;c.save();});$('s33-reports-print').onclick=()=>c.print();$('s33-reports-csv').onclick=()=>{const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const rows=[['Učenik','Zadatak','Datum','Bodovi','Maksimum','Ocjena','Komentar'],...w.reports.map(r=>[c.profileName(),r.name,r.date,r.score,r.max,r.grade,r.comment])];download('ELDI-33-izvjestaj.csv','\ufeff'+rows.map(r=>r.map(v=>quote(/^[=+@-]/.test(String(v))?"'"+v:v)).join(';')).join('\r\n'),'text/csv');};return()=>{};}
