import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
const V=(x,y,z)=>new T.Vector3(x,y,z),rad=d=>d*Math.PI/180;
export const shapeNames={cube:'Kocka',cuboid:'Kvadar',prism:'Prizma',pyramid:'Piramida',cylinder:'Valjak',cone:'Kupa',sphere:'Lopta'};
function geometry(o){if(o.type==='cube')return new T.BoxGeometry(o.a,o.a,o.a);if(o.type==='cuboid')return new T.BoxGeometry(o.a,o.h,o.b);if(o.type==='sphere')return new T.SphereGeometry(o.r,40,28);if(o.type==='cylinder'||o.type==='cone')return new T.CylinderGeometry(o.type==='cone'?0:o.r,o.r,o.h,64);const R=o.a/(2*Math.sin(Math.PI/o.n));return new T.CylinderGeometry(o.type==='pyramid'?0:R,R,o.h,o.n);}
function clean(group){for(const c of [...group.children]){c.traverse(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();});group.remove(c);}}
function poly(group,vertices,color,opacity=.85){const g=new T.BufferGeometry().setFromPoints(vertices),idx=[];for(let i=1;i<vertices.length-1;i++)idx.push(0,i,i+1);g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,new T.MeshPhongMaterial({color,side:T.DoubleSide,transparent:opacity<1,opacity,shininess:55}));m.castShadow=true;m.receiveShadow=true;group.add(m);const line=new T.LineLoop(new T.BufferGeometry().setFromPoints(vertices),new T.LineBasicMaterial({color:0xa5eef5}));group.add(line);return m;}
export function foldedNet(group,o,u){u=Math.max(0,Math.min(1,u));const a=o.a,h=o.type==='cube'?a:o.h,b=o.type==='cube'?a:o.b;let base;
 if(['cube','cuboid'].includes(o.type))base=[V(-a/2,0,-b/2),V(a/2,0,-b/2),V(a/2,0,b/2),V(-a/2,0,b/2)];else{const R=a/(2*Math.sin(Math.PI/o.n));base=Array.from({length:o.n},(_,i)=>V(R*Math.cos(i*2*Math.PI/o.n),0,R*Math.sin(i*2*Math.PI/o.n)));}
 poly(group,base,o.color);for(let i=0;i<base.length;i++){const p=base[i],q=base[(i+1)%base.length],mid=p.clone().add(q).multiplyScalar(.5),normal=mid.clone().normalize(),up=V(0,1,0),theta=u*Math.PI/2,direction=up.clone().multiplyScalar(Math.cos(theta)).addScaledVector(normal,Math.sin(theta));
  if(o.type==='pyramid'){const ap=mid.length(),L=Math.hypot(ap,h),angle=Math.atan2(h,-ap)*(1-u),apex=mid.clone().addScaledVector(normal,L*Math.cos(angle)).addScaledVector(up,L*Math.sin(angle));poly(group,[p,q,apex],o.color);}
  else{poly(group,[p,q,q.clone().addScaledVector(direction,h),p.clone().addScaledVector(direction,h)],o.color);if(i===0){const tangent=q.clone().sub(p).normalize(),hinge=mid.clone().addScaledVector(direction,h);const top=base.map(v=>{const rel=v.clone().sub(mid),d=rel.dot(normal),t=rel.dot(tangent);return hinge.clone().addScaledVector(tangent,t).addScaledVector(normal,d*Math.cos(2*theta)).addScaledVector(up,-d*Math.sin(2*theta));});poly(group,top,o.color);}}
 }
}
export function makeScene(host,{quality='full',onSection=()=>{},theme='dark'}={}){
 let renderer,rich=false;try{if(quality==='simple')throw Error();renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});rich=true;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;}catch{renderer=new SVGRenderer();renderer.setQuality('high');}
 const light=theme==='light',bg=light?0xeaf1f5:0x0e1825;renderer.setClearColor(bg,1);host.replaceChildren(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D scena; povuci mišem za rotaciju, točkić za približavanje');renderer.domElement.setAttribute('role','img');renderer.domElement.tabIndex=0;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,300);camera.position.set(9,7,11);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.minDistance=3;controls.maxDistance=100;controls.update();scene.add(new T.AmbientLight(0xddefff,1.7));const key=new T.DirectionalLight(0xffffff,3.5);key.position.set(8,16,10);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-25;key.shadow.camera.right=25;key.shadow.camera.top=25;key.shadow.camera.bottom=-25;scene.add(key);const fill=new T.DirectionalLight(0x44bacb,1.1);fill.position.set(-8,5,-8);scene.add(fill);
 const grid=new T.GridHelper(60,60,light?0x8c9eae:0x374959,light?0xc7d3de:0x213242);grid.position.y=-6;scene.add(grid);if(rich){const floor=new T.Mesh(new T.PlaneGeometry(60,60),new T.ShadowMaterial({opacity:.2}));floor.rotation.x=-Math.PI/2;floor.position.y=-5.99;floor.receiveShadow=true;scene.add(floor);}
 const axes=new T.AxesHelper(3);axes.position.set(-7,-5.8,-7);scene.add(axes);const content=new T.Group(),section=new T.Group();scene.add(content,section);let objects=[],options={},disposed=false;
 const render=()=>{if(!disposed)renderer.render(scene,camera);};controls.addEventListener('change',render);
 const observer=new ResizeObserver(()=>{const w=Math.max(100,host.clientWidth),h=Math.max(180,host.clientHeight);renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();render();});observer.observe(host);
 function update(list,opts={}){objects=list;options=opts;clean(content);clean(section);const meshes=[];if(opts.net){const o=list.find(o=>o.id===opts.selected)||list[0];if(o&&['cube','cuboid','prism','pyramid'].includes(o.type)){foldedNet(content,o,opts.unfold||0);onSection({net:true});render();return;}}
 for(const o of list){const g=geometry(o),m=new T.Mesh(g,new T.MeshPhongMaterial({color:o.color,transparent:o.opacity<1,opacity:o.opacity,side:T.DoubleSide,shininess:65,depthWrite:o.opacity>.95}));m.position.set(o.x,o.y,o.z);m.rotation.set(rad(o.rx),rad(o.ry),rad(o.rz));m.castShadow=true;m.receiveShadow=true;content.add(m);const e=new T.LineSegments(new T.EdgesGeometry(g,32),new T.LineBasicMaterial({color:o.id===opts.selected?0x9aeaf2:0x6897aa,transparent:true,opacity:.8}));e.position.copy(m.position);e.rotation.copy(m.rotation);content.add(e);meshes.push([o,m]);}
 if(opts.cut){const selected=meshes.find(([o])=>o.id===opts.selected)||meshes[0];if(selected){const [,m]=selected;content.updateMatrixWorld(true);const normal=V(Math.sin(rad(opts.tiltX||0)),Math.cos(rad(opts.tiltX||0)),Math.sin(rad(opts.tiltZ||0))).normalize(),offset=Number(opts.offset)||0,plane=new T.Plane(normal,-offset),points=[];const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry,arr=g.getAttribute('position');for(let i=0;i<arr.count;i+=3){const ps=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(arr,i+j).applyMatrix4(m.matrixWorld));for(let j=0;j<3;j++){const a=ps[j],b=ps[(j+1)%3],da=plane.distanceToPoint(a),db=plane.distanceToPoint(b);if(Math.abs(da)<1e-7)points.push(a);else if(da*db<0)points.push(a.clone().lerp(b,da/(da-db)));}}if(g!==m.geometry)g.dispose();const unique=[];for(const p of points)if(!unique.some(q=>p.distanceToSquared(q)<1e-8))unique.push(p);
 const right=V(0,0,1).cross(normal).normalize();if(right.length()<.1)right.set(1,0,0);const up=normal.clone().cross(right).normalize(),center=unique.reduce((s,p)=>s.add(p),V(0,0,0)).multiplyScalar(1/Math.max(1,unique.length));unique.sort((a,b)=>Math.atan2(a.clone().sub(center).dot(up),a.clone().sub(center).dot(right))-Math.atan2(b.clone().sub(center).dot(up),b.clone().sub(center).dot(right)));let area=0;for(let i=0;i<unique.length;i++){const p=unique[i],q=unique[(i+1)%unique.length];area+=p.dot(right)*q.dot(up)-q.dot(right)*p.dot(up);}if(unique.length>=3)poly(section,unique,0xffc45c,.72);
 const pm=new T.Mesh(new T.PlaneGeometry(20,20),new T.MeshBasicMaterial({color:0xf4b852,side:T.DoubleSide,transparent:true,opacity:.10,depthWrite:false}));pm.quaternion.setFromUnitVectors(V(0,0,1),normal);pm.position.copy(normal.clone().multiplyScalar(offset));section.add(pm);onSection({area:Math.abs(area)/2,points:unique.length,approx:['sphere','cone','cylinder'].includes(selected[0].type)});
 }}else onSection(null);render();}
 function reset(){camera.position.set(9,7,11);controls.target.set(0,0,0);controls.update();render();}
 async function png(){render();if(rich)return renderer.domElement.toDataURL('image/png');const str=new XMLSerializer().serializeToString(renderer.domElement),blob=new Blob([str],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const image=new Image();await new Promise((ok,no)=>{image.onload=ok;image.onerror=no;image.src=url;});const c=document.createElement('canvas');c.width=host.clientWidth*2;c.height=host.clientHeight*2;const x=c.getContext('2d');x.fillStyle=light?'#eaf1f5':'#0e1825';x.fillRect(0,0,c.width,c.height);x.drawImage(image,0,0,c.width,c.height);return c.toDataURL('image/png');}finally{URL.revokeObjectURL(url);}}
 return{update,reset,png,rich,render,setView(kind){const poses={iso:[9,7,11],front:[0,0,16],top:[0,18,.01],side:[18,0,0]};camera.position.set(...(poses[kind]||poses.iso));controls.target.set(0,0,0);controls.update();render();},svg(){const r=new SVGRenderer();r.setSize(host.clientWidth,host.clientHeight);r.setClearColor(bg,1);r.render(scene,camera);return new XMLSerializer().serializeToString(r.domElement);},destroy(){disposed=true;observer.disconnect();controls.dispose();clean(content);clean(section);scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose?.();});renderer.dispose?.();host.replaceChildren();}};
}
