export const debugTasks=[
 {id:'zbir',title:'Zbir dva broja',grade:5,statement:'Učitaj dva broja i ispiši njihov zbir.',bug:'var a=read33(),b=read33();\nprint33(a-b);',solution:'var a=read33(),b=read33();\nprint33(a+b);',tests:[['2 3','5'],['-5 2','-3'],['0 0','0'],['100 -100','0']]},
 {id:'maksimum',title:'Maksimum negativnih brojeva',grade:5,statement:'Prvi broj je n; slijedi n cijelih brojeva. Ispiši najveći.',bug:'var n=read33(),m=0;\nfor(var i=0;i<n;i++){var x=read33();if(x>m)m=x;}\nprint33(m);',solution:'var n=read33(),m=read33();\nfor(var i=1;i<n;i++){var x=read33();if(x>m)m=x;}\nprint33(m);',tests:[['3 -8 -2 -5','-2'],['1 -10','-10'],['4 0 2 9 1','9'],['2 7 7','7']]},
 {id:'parni',title:'Brojanje parnih',grade:5,statement:'Učitaj n pa n brojeva. Ispiši koliko ih je parno.',bug:'var n=read33(),k=0;for(var i=0;i<n;i++){if(read33()%2)k++;}print33(k);',solution:'var n=read33(),k=0;for(var i=0;i<n;i++){if(read33()%2===0)k++;}print33(k);',tests:[['4 2 3 4 5','2'],['3 0 -2 8','3'],['2 1 3','0'],['1 2','1']]},
 {id:'zbir-n',title:'Zbir od 1 do n',grade:5,statement:'Učitaj n ≥ 0. Ispiši 1 + 2 + … + n.',bug:'var n=read33(),s=0;for(var i=1;i<n;i++)s+=i;print33(s);',solution:'var n=read33(),s=0;for(var i=1;i<=n;i++)s+=i;print33(s);',tests:[['0','0'],['1','1'],['5','15'],['100','5050']]},
 {id:'faktorijel',title:'Početna vrijednost proizvoda',grade:6,statement:'Izračunaj n! za 0 ≤ n ≤ 10. Vrijedi 0! = 1.',bug:'var n=read33(),p=0;for(var i=1;i<=n;i++)p*=i;print33(p);',solution:'var n=read33(),p=1;for(var i=1;i<=n;i++)p*=i;print33(p);',tests:[['0','1'],['1','1'],['5','120'],['8','40320']]},
 {id:'cifre',title:'Zbir cifara',grade:6,statement:'Učitaj nenegativan cijeli broj. Ispiši zbir njegovih cifara.',bug:'var n=read33(),s=0;while(n>0){s+=n%10;n=n/10;}print33(s);',solution:'var n=read33(),s=0;while(n>0){s+=n%10;n=Math.floor(n/10);}print33(s);',tests:[['0','0'],['5','5'],['1203','6'],['9999','36']]},
 {id:'minimum',title:'Najmanji pozitivan broj',grade:6,statement:'Učitaj n pa n brojeva. Ispiši najmanji.',bug:'var n=read33(),m=0;for(var i=0;i<n;i++){var x=read33();if(x<m)m=x;}print33(m);',solution:'var n=read33(),m=read33();for(var i=1;i<n;i++){var x=read33();if(x<m)m=x;}print33(m);',tests:[['3 4 9 6','4'],['1 2','2'],['3 -1 -4 0','-4'],['2 8 8','8']]},
 {id:'stepen',title:'Stepenovanje petljom',grade:6,statement:'Učitaj a i nenegativan n. Ispiši a na stepen n.',bug:'var a=read33(),n=read33(),p=a;for(var i=0;i<n;i++)p*=a;print33(p);',solution:'var a=read33(),n=read33(),p=1;for(var i=0;i<n;i++)p*=a;print33(p);',tests:[['2 0','1'],['2 3','8'],['-2 3','-8'],['5 2','25']]},
 {id:'gcd',title:'Euklidov algoritam',grade:7,statement:'Učitaj dva pozitivna broja i ispiši njihov NZD.',bug:'var a=read33(),b=read33();while(b!==0){a=b;b=a%b;}print33(a);',solution:'var a=read33(),b=read33();while(b!==0){var r=a%b;a=b;b=r;}print33(a);',tests:[['12 8','4'],['7 5','1'],['9 9','9'],['100 25','25']]},
 {id:'prost',title:'Da li je broj prost?',grade:7,statement:'Za cijeli n ≥ 0 ispiši 1 ako je prost, inače 0.',bug:'var n=read33(),ok=true;for(var d=2;d*d<n;d++)if(n%d===0)ok=false;print33(ok?1:0);',solution:'var n=read33(),ok=n>=2;for(var d=2;d*d<=n;d++)if(n%d===0)ok=false;print33(ok?1:0);',tests:[['1','0'],['2','1'],['49','0'],['97','1']]},
 {id:'prosjek',title:'Prosjek nije zbir',grade:7,statement:'Učitaj n > 0 pa n brojeva. Ispiši njihov aritmetički prosjek.',bug:'var n=read33(),s=0;for(var i=0;i<n;i++)s+=read33();print33(s/(n+1));',solution:'var n=read33(),s=0;for(var i=0;i<n;i++)s+=read33();print33(s/n);',tests:[['2 4 6','5'],['1 7','7'],['4 0 0 0 0','0'],['3 -3 0 3','0']]},
 {id:'brojaci',title:'Koliko je traženih vrijednosti?',grade:7,statement:'Učitaj n, traženi k, zatim n brojeva. Ispiši broj pojavljivanja k.',bug:'var n=read33(),k=read33(),c=0;for(var i=0;i<n;i++){c=0;if(read33()===k)c++;}print33(c);',solution:'var n=read33(),k=read33(),c=0;for(var i=0;i<n;i++){if(read33()===k)c++;}print33(c);',tests:[['4 2 2 1 2 2','3'],['3 9 1 2 3','0'],['1 -1 -1','1'],['3 0 0 0 0','3']]},
 {id:'sort',title:'Smjer sortiranja',grade:8,statement:'Učitaj n pa n brojeva. Ispiši ih rastuće, odvojene razmakom.',bug:'var n=read33(),a=[];for(var i=0;i<n;i++)a.push(read33());for(var i=0;i<n;i++)for(var j=0;j<n-1;j++)if(a[j]<a[j+1]){var t=a[j];a[j]=a[j+1];a[j+1]=t;}print33(a.join(" "));',solution:'var n=read33(),a=[];for(var i=0;i<n;i++)a.push(read33());for(var i=0;i<n;i++)for(var j=0;j<n-1;j++)if(a[j]>a[j+1]){var t=a[j];a[j]=a[j+1];a[j+1]=t;}print33(a.join(" "));',tests:[['4 3 1 4 2','1 2 3 4'],['1 0','0'],['3 -2 -5 -1','-5 -2 -1'],['3 2 2 1','1 2 2']]},
 {id:'binarna',title:'Granice binarne pretrage',grade:8,statement:'Učitaj n, k i rastuće sortiran niz. Ispiši indeks k (od 0) ili −1.',bug:'var n=read33(),k=read33(),a=[];for(var i=0;i<n;i++)a.push(read33());var l=0,r=n-1,ans=-1;while(l<r){var m=Math.floor((l+r)/2);if(a[m]===k){ans=m;break;}if(a[m]<k)l=m+1;else r=m-1;}print33(ans);',solution:'var n=read33(),k=read33(),a=[];for(var i=0;i<n;i++)a.push(read33());var l=0,r=n-1,ans=-1;while(l<=r){var m=Math.floor((l+r)/2);if(a[m]===k){ans=m;break;}if(a[m]<k)l=m+1;else r=m-1;}print33(ans);',tests:[['1 4 4','0'],['4 8 2 4 6 8','3'],['3 1 1 2 3','0'],['3 9 1 2 3','-1']]},
 {id:'prefiks',title:'Prefiksni zbirovi',grade:8,statement:'Učitaj n pa niz. Ispiši zbir prvih 1, prvih 2, … prvih n članova.',bug:'var n=read33(),s=0,a=[];for(var i=0;i<n;i++){s=read33();a.push(s);}print33(a.join(" "));',solution:'var n=read33(),s=0,a=[];for(var i=0;i<n;i++){s+=read33();a.push(s);}print33(a.join(" "));',tests:[['3 2 3 4','2 5 9'],['1 7','7'],['3 -1 1 2','-1 0 2'],['2 0 0','0 0']]},
 {id:'razliciti',title:'Različite vrijednosti',grade:8,statement:'Učitaj n pa n cijelih brojeva. Ispiši broj različitih vrijednosti.',bug:'var n=read33(),a=[],c=0;for(var i=0;i<n;i++){var x=read33();if(a.indexOf(x)>0)c++;a.push(x);}print33(c);',solution:'var n=read33(),a=[];for(var i=0;i<n;i++){var x=read33();if(a.indexOf(x)===-1)a.push(x);}print33(a.length);',tests:[['4 1 1 2 3','3'],['1 8','1'],['3 -1 -1 -1','1'],['4 0 1 2 3','4']]},
 {id:'fibonacci',title:'Fibonaccijev niz',grade:9,statement:'Ispiši F(n) za 0 ≤ n ≤ 25, uz F(0)=0, F(1)=1.',bug:'var n=read33(),a=0,b=1;for(var i=0;i<n;i++){a=b;b=a+b;}print33(a);',solution:'var n=read33(),a=0,b=1;for(var i=0;i<n;i++){var t=a+b;a=b;b=t;}print33(a);',tests:[['0','0'],['1','1'],['6','8'],['10','55']]},
 {id:'parovi',title:'Parovi sa zadanim zbirom',grade:9,statement:'Učitaj n, cilj i niz. Broj parova indeksa i < j čiji je zbir jednak cilju.',bug:'var n=read33(),t=read33(),a=[],c=0;for(var i=0;i<n;i++)a.push(read33());for(var i=0;i<n;i++)for(var j=0;j<n;j++)if(a[i]+a[j]===t)c++;print33(c);',solution:'var n=read33(),t=read33(),a=[],c=0;for(var i=0;i<n;i++)a.push(read33());for(var i=0;i<n;i++)for(var j=i+1;j<n;j++)if(a[i]+a[j]===t)c++;print33(c);',tests:[['4 5 1 2 3 4','2'],['3 4 2 2 2','3'],['1 2 1','0'],['3 0 -1 0 1','1']]},
 {id:'kadane',title:'Najveći zbir susjednih članova',grade:9,statement:'Za neprazan niz nađi najveći zbir nepraznog uzastopnog dijela.',bug:'var n=read33(),best=0,s=0;for(var i=0;i<n;i++){s=Math.max(0,s+read33());best=Math.max(best,s);}print33(best);',solution:'var n=read33(),s=read33(),best=s;for(var i=1;i<n;i++){var x=read33();s=Math.max(x,s+x);best=Math.max(best,s);}print33(best);',tests:[['3 -5 -2 -8','-2'],['5 1 -2 3 4 -1','7'],['1 -4','-4'],['3 2 3 4','9']]},
 {id:'lcm',title:'NZS uz NZD',grade:9,statement:'Učitaj dva pozitivna broja. Ispiši njihov najmanji zajednički sadržalac.',bug:'var a=read33(),b=read33(),x=a,y=b;while(y){var r=x%y;x=y;y=r;}print33(a*b*x);',solution:'var a=read33(),b=read33(),x=a,y=b;while(y){var r=x%y;x=y;y=r;}print33((a/x)*b);',tests:[['4 6','12'],['7 5','35'],['9 9','9'],['1 12','12']]}
];
const mathTemplates={
5:[n=>['Ostatak pri dijeljenju',`Koliki je ostatak pri dijeljenju ${101+n*7} sa 6?`,(101+n*7)%6,'Broj predstavi kao 6k + ostatak.'],n=>['Pravougaonik',`Pravougaonik ima stranice ${n+3} cm i ${n+5} cm. Koliki je obim u cm?`,4*n+16,'O = 2(a+b).'],n=>['Zbir uzastopnih',`Koliki je zbir ${n+10}, ${n+11} i ${n+12}?`,3*n+33,'Srednji broj pomnoži sa 3.'],n=>['Broj stranica',`Svaki od ${n+3} učenika pročita 12 stranica. Koliko ukupno?`,12*(n+3),'Broj učenika × stranice po učeniku.'],n=>['Dijeljenje paketa',`U ${n+4} kutija raspoređeno je ${(n+4)*8} olovaka jednako. Koliko je u kutiji?`,8,'Ukupan broj podijeli brojem kutija.'],n=>['Kvadrat',`Kvadrat stranice ${n+2} cm ima površinu koliko cm²?`,(n+2)**2,'P = a².'],n=>['Vrijeme',`Čas počinje u 9:00 i traje ${n+2} puta po 15 minuta. Koliko minuta traje?`,15*(n+2),'Trajanje pomnoži brojem intervala.'],n=>['Izbor para',`Na polici je ${n+3} različitih knjiga. Na koliko načina biraš dvije, bez redoslijeda?`,(n+3)*(n+2)/2,'n(n−1)/2.']],
6:[n=>['Dio cjeline',`Koliko je 3/4 od ${4*(n+5)}?`,3*(n+5),'Prvo podijeli sa 4, zatim pomnoži sa 3.'],n=>['Treći ugao',`Dva ugla trougla su ${30+n*5}° i 70°. Koliki je treći?`,80-n*5,'Zbir uglova trougla je 180°.'],n=>['Postotak',`Koliko je 25% od ${20*(n+3)}?`,5*(n+3),'25% je četvrtina.'],n=>['Suprotni brojevi',`Izračunaj −${n+4} + ${2*n+10}.`,n+6,'Brojevi imaju različite predznake.'],n=>['Decimalni proizvod',`Izračunaj 0,5 × ${n+8}.`,(n+8)/2,'Množenje sa 0,5 je prepolovljavanje.'],n=>['Skupovi',`Skup A ima ${n+5}, skup B ${n+7}, a presjek 3 elementa. Koliko ima unija?`,2*n+9,'|A∪B| = |A|+|B|−|A∩B|.'],n=>['NZD',`Koliki je NZD brojeva ${6*(n+1)} i ${9*(n+1)}?`,3*(n+1),'NZD(6k,9k)=3k.'],n=>['Razlomak',`Koliki je brojilac skraćenog razlomka ${3*(n+2)}/${4*(n+2)}?`,3,'Brojilac i imenilac podijeli zajedničkim faktorom.']],
7:[n=>['Jednačina',`Riješi 3x + ${n+2} = ${4*n+14}.`,n+4,'Oduzmi slobodni član i podijeli sa 3.'],n=>['Razmjera',`a:b=2:3 i a+b=${5*(n+4)}. Koliko je b?`,3*(n+4),'Ukupno je pet jednakih dijelova.'],n=>['Popust',`Cijena ${20*(n+3)} KM snižena je 10%. Kolika je nova cijena?`,18*(n+3),'Plati se 90% početne cijene.'],n=>['Brzina',`Pređeš ${12*(n+2)} km za 3 h. Brzina u km/h?`,4*(n+2),'v=s/t.'],n=>['Površina trougla',`Osnovica je ${2*(n+3)} cm, a visina 5 cm. Površina u cm²?`,5*(n+3),'P=ah/2.'],n=>['Stepen negativnog',`Izračunaj (−${n+2})².`,(n+2)**2,'Kvadrat negativnog broja je pozitivan.'],n=>['Aritmetička sredina',`Prosjek brojeva ${n+2}, ${n+5}, ${n+8}?`,n+5,'Zbir tri broja podijeli sa 3.'],n=>['Vjerovatnoća',`U kutiji su ${n+2} crvene i ${n+2} plave kuglice. Vjerovatnoća izvlačenja crvene (decimalno)?`,.5,'Povoljni ishodi / svi jednako mogući ishodi.']],
8:[n=>['Pitagora',`Katete pravouglog trougla su ${3*(n+1)} i ${4*(n+1)} cm. Hipotenuza?`,5*(n+1),'a²+b²=c².'],n=>['Kvadratni korijen',`Izračunaj √${(n+8)**2}.`,n+8,'Traži nenegativan broj čiji je kvadrat zadani broj.'],n=>['Linearna funkcija',`Za y=2x−3, koliko je y kada je x=${n+4}?`,2*n+5,'Uvrsti zadani x.'],n=>['Unutrašnji uglovi',`Koliki je zbir unutrašnjih uglova ${n+4}-ougla u stepenima?`,(n+2)*180,'S=(n−2)·180°.'],n=>['Dijagonala kvadrata',`Ako je dijagonala kvadrata ${2*(n+2)}√2 cm, kolika je stranica?`,2*(n+2),'d=a√2.'],n=>['Sistem jednačina',`x+y=${2*n+10}, x−y=4. Koliko je x?`,n+7,'Saberi jednačine.'],n=>['Obim kruga',`Krug ima r=${n+2} cm. Koliki je koeficijent uz π u obimu?`,2*(n+2),'O=2rπ.'],n=>['Sličnost',`Dužina ${n+3} cm uvećana je faktorom 3. Nova dužina?`,3*(n+3),'Odgovarajuće dužine množe se faktorom sličnosti.']],
9:[n=>['Zapremina valjka',`Valjak ima r=${n+1} i h=5. Koliki je koeficijent uz π u zapremini?`,5*(n+1)**2,'V=πr²h.'],n=>['Zapremina kupe',`Kupa ima r=${n+1} i h=6. Koliki je koeficijent uz π u zapremini?`,2*(n+1)**2,'V=πr²h/3.'],n=>['Površina lopte',`Lopta ima r=${n+1}. Koliki je koeficijent uz π u površini?`,4*(n+1)**2,'P=4πr².'],n=>['Kvadratna jednačina',`Pozitivno rješenje x²=${(n+3)**2}?`,n+3,'Jednačina ima dva suprotna korijena; traži se pozitivan.'],n=>['Prizma',`Prizma ima površinu osnove ${n+5} cm² i visinu 8 cm. Zapremina?`,8*(n+5),'V=B·H.'],n=>['Piramida',`Piramida ima osnovu površine ${3*(n+5)} cm² i visinu 4 cm. Zapremina?`,4*(n+5),'V=B·H/3.'],n=>['Sličnost i površina',`Faktor sličnosti je ${n+2}. Koliko puta je površina veća?`,(n+2)**2,'Površine se odnose kao kvadrati odgovarajućih dužina.'],n=>['Vjerovatnoća komplementa',`Vjerovatnoća uspjeha je ${(n+2)/10}. Vjerovatnoća neuspjeha?`,1-(n+2)/10,'P(A)+P(ne A)=1.']]};
const infoQuestions={
5:[['Bajt','Koliko bitova ima jedan bajt?',8,'Bajt čini 8 bitova.'],['Petlja','Petlja se izvrši 6 puta i svaki put ispiše dvije zvjezdice. Ukupan broj zvjezdica?',12,'6·2=12.'],['Binarni broj','Binarni 1011 u decimalnom sistemu?',11,'8+2+1=11.'],['Mreža','Koliko računara učestvuje u razmjeni kada jedan šalje poruku drugom?',2,'Pošiljalac i primalac.']],
6:[['Kapacitet','Koliko bajtova ima 2 KiB?',2048,'1 KiB=1024 B.'],['Uslov','Za x=5, koliko puta se izvrši tijelo: dok x<8, povećaj x za 1?',3,'Za vrijednosti 5,6,7.'],['Logika','Vrijednost 1 AND 0?',0,'AND je 1 samo kada su oba ulaza 1.'],['Liste','Indeksi liste s 8 elemenata počinju od 0. Posljednji indeks?',7,'Posljednji indeks je dužina−1.']],
7:[['Stek','Dodaj 2, pa 5, pa 9 na prazan stek. Koji broj prvi uklanjaš?',9,'Stek radi po LIFO principu.'],['Red','Dodaj 2, pa 5, pa 9 u prazan red. Koji broj prvi uklanjaš?',2,'Red radi po FIFO principu.'],['SQL','Tabela ima 7 redova. COUNT(*) bez uslova vraća?',7,'COUNT(*) prebrojava redove.'],['HTTP','Koji status označava da resurs nije pronađen?',404,'HTTP 404 označava resurs koji nije pronađen.']],
8:[['Binarna pretraga','Najviše koliko provjera srednjeg elementa treba za uspješnu pretragu među 15 različitih sortiranih elemenata?',4,'Nivoi imaju 1,2,4,8 mjesta; ukupno 15.'],['Graf','Stablo sa 8 čvorova ima koliko bridova?',7,'Svako konačno stablo s n čvorova ima n−1 bridova.'],['Rekurzija','Vrijednost faktorijela 5?',120,'5·4·3·2·1=120.'],['XOR','Vrijednost 1 XOR 1?',0,'XOR je 1 kada su ulazi različiti.']],
9:[['Parovi','Koliko parova indeksa i<j ima niz od 10 elemenata?',45,'10·9/2=45.'],['Algoritam','Dvije ugniježđene petlje izvrše se 12, odnosno 8 puta. Broj izvršavanja unutrašnjeg tijela?',96,'12·8=96.'],['API','Koji HTTP status u ovoj radionici označava uspješno kreiran zapis?',201,'201 Created.'],['Prefiksni zbir','Niz je 3, −1, 4, 2. Zbir članova na indeksima 1 do 3 uključivo?',5,'−1+4+2=5.']]};
export function quizBank(grade,subject,variant=0){const rows=subject==='math'?mathTemplates[grade].map(f=>f(variant%4)):infoQuestions[grade];return rows.map(([title,statement,answer,explanation],i)=>({id:subject+'-'+grade+'-'+i+'-'+variant,title,statement,answer,explanation,points:10}));}
export const projects=[
 ['Valjak u pokretu','scene',7,'Napravi tijelo valjak, poluprečnika 2 i visine 5. Petljom povećaj visinu do 10. Objasni kako promjena visine utječe na zapreminu.',[{kind:'property',id:'valjak',property:'r',expected:2,points:40,tolerance:.01},{kind:'property',id:'valjak',property:'h',expected:10,points:60,tolerance:.01}]],
 ['Tri geometrijska tijela','scene',8,'Napravi kocku, valjak i loptu s imenima kocka, valjak, lopta. Rasporedi ih da se ne preklapaju. Uporedi njihove površine.',[{kind:'object',id:'kocka',expected:'cube',points:30},{kind:'object',id:'valjak',expected:'cylinder',points:30},{kind:'object',id:'lopta',expected:'sphere',points:40}]],
 ['Prizma sa šest stranica','scene',9,'Dodaj pravilnu prizmu imena prizma. Postavi n=6 i visinu 8. Istraži kosu ravan presjeka; priloži sliku i objašnjenje.',[{kind:'property',id:'prizma',property:'n',expected:6,points:50,tolerance:0},{kind:'property',id:'prizma',property:'h',expected:8,points:50,tolerance:.01}]],
 ['Mreža kocke','scene',6,'Odaberi kocku, otvori Mreža i pomjeraj klizač do kraja. Prebroj stranice i objasni koja postaje gornja. Sačuvaj prikaz.',[]],
 ['Robot do cilja','robot',5,'Na prvoj stazi dovedi robota do cilja C. Prvo napravi program s naredbama, zatim ga skrati petljama.',[{kind:'robot',expected:true,points:100}]],
 ['Robot i senzor','robot',7,'Na drugoj stazi koristi uslov i senzor udaljenosti. Objasni zašto samo pravilo „uvijek skreni desno“ ne mora biti dovoljno za svaki labirint.',[]],
 ['Moja prva stranica','web',6,'Napravi stranicu s naslovom, glavnim sadržajem, tri odjeljka i dugmetom koje mijenja tekst. Provjeri prikaz telefona i izvezi ZIP.',[]],
 ['Kviz iz matematike','web',7,'Napravi kviz s tri pitanja, brojačem bodova i jasnom povratnom informacijom. Dodaj oznake poljima za odgovore.',[]],
 ['Kalkulator površine','web',8,'Napravi kalkulator površine pravougaonika koji odbija prazne i nepozitivne dužine. Napiši najmanje četiri testna slučaja.',[]],
 ['Školska biblioteka','sql',8,'Istraži oglednu bazu. Dodaj izmišljenu knjigu, prikaži ukupan broj primjeraka i spoji posudbe s imenima članova i naslovima.',[]],
 ['Poređenje algoritama','algorithms',8,'Uporedi dva sortiranja na već sortiranom, obrnutom i miješanom nizu. Zabilježi poređenja i zamjene, pa objasni razlike.',[]],
 ['Sabirač od logičkih kola','logic',7,'Sastavi XOR i AND nad A i B. Iz tabele istinitosti objasni zbirni bit i prenos pri sabiranju dva bita.',[]],
 ['Prekinuta mreža','network',7,'Isključi jednu vezu i provjeri koji računar može do servera. Dodaj rezervnu vezu i objasni novi put poruke.',[]],
 ['API biblioteke','network',9,'Dodaj dvije knjige metodom POST. Jednu pročitaj metodom GET i drugu obriši metodom DELETE. Zapiši statusne kodove.',[]],
 ['Sedmica mjerenja','data',7,'Unesi sedam izmišljenih temperatura. Izračunaj prosjek i medijanu, filtriraj vrijednosti i objasni promjenu grafikona.',[]],
 ['Ispravi i dokaži testom','debug',8,'Odaberi program s greškom. Napiši najmanje jedan test koji pada prije izmjene i prolazi poslije. Objasni uzrok greške.',[]]
];
