import {zipSync,strToU8} from 'fflate';
import {parse} from 'acorn';
import {esc,E,$,table,edit,note,download,report} from './common.js';
const webExamples={
 stranica:{html:'<main>\n  <p class="label">MOJ PRVI WEB PROJEKAT</p>\n  <h1>Dobro došli u moju radionicu.</h1>\n  <p>Učim, istražujem i stvaram.</p>\n  <button id="pozdrav">Pozdravi</button>\n  <p id="odgovor" aria-live="polite"></p>\n</main>',css:'body { margin:0; font:18px system-ui; background:#101d2b; color:#edf6ff; }\nmain { max-width:720px; margin:60px auto; padding:30px; }\nh1 { font-size:clamp(32px,6vw,60px); line-height:1.1; }\n.label { color:#42cedb; font-size:13px; letter-spacing:2px; }\nbutton { padding:14px 24px; border:0; border-radius:8px; background:#42cedb; color:#102536; cursor:pointer; }',js:"document.getElementById('pozdrav').onclick = function () {\n  document.getElementById('odgovor').textContent = 'Pozdrav iz ELDI radionice!';\n  console.log('Dugme radi.');\n};"},
 kviz:{html:'<main><h1>Mali kviz</h1><p>Koliko je 7 × 8?</p><input id="odgovor" type="number" aria-label="Tvoj odgovor"><button id="provjeri">Provjeri</button><p id="rezultat" role="status"></p></main>',css:'body{font:20px system-ui;background:#f1f6fa;color:#172e42}main{max-width:640px;margin:60px auto;padding:28px;background:white;border-radius:16px}button,input{font:inherit;padding:12px;margin:8px}',js:"document.getElementById('provjeri').onclick=function(){\n var odgovor=Number(document.getElementById('odgovor').value);\n document.getElementById('rezultat').textContent=odgovor===56?'Tačno!':'Pokušaj ponovo.';\n};"},
 kalkulator:{html:'<main><h1>Kalkulator površine</h1><label>Stranica a <input id="a" type="number" value="3"></label><label>Stranica b <input id="b" type="number" value="4"></label><button id="racunaj">Izračunaj</button><output id="p"></output></main>',css:'body{font:20px system-ui;background:#102331;color:white}main{max-width:600px;margin:auto;padding:40px}label,output{display:block;margin:20px 0}input,button{font:inherit;padding:12px;border-radius:6px}output{color:#52e1d4}',js:"document.getElementById('racunaj').onclick=function(){\n var a=Number(document.getElementById('a').value);\n var b=Number(document.getElementById('b').value);\n document.getElementById('p').textContent=a>0&&b>0?'P = '+(a*b):'Unesi pozitivne dužine.';\n};"},
 portal:{html:'<header><h1>Naš razred</h1><nav><a href="#vijesti">Vijesti</a> <a href="#raspored">Raspored</a></nav></header><main><section id="vijesti"><h2>Radionica programiranja</h2><p>Predstavljamo svoje prve projekte.</p></section><section id="raspored"><h2>Raspored</h2><table><tr><th>Dan</th><th>Aktivnost</th></tr><tr><td>Ponedjeljak</td><td>ELDI radionica</td></tr></table></section></main>',css:'body{margin:0;font:18px system-ui;background:#f4f7f9;color:#163142}header{padding:28px;background:#153c50;color:white}a{color:#69deee;margin-right:20px}main{max-width:900px;margin:auto;padding:24px;display:grid;gap:20px}section{padding:24px;background:white;border-radius:12px}td,th{padding:14px;border-bottom:1px solid #ccc;text-align:left}',js:"console.log('Školski portal je spreman za uređivanje.');"}
};
export function instrument(code){const ast=parse(code,{ecmaVersion:'latest'}),inserts=[];function walk(n){if(!n||typeof n!=='object')return;if(['ForStatement','ForInStatement','ForOfStatement','WhileStatement','DoWhileStatement'].includes(n.type)){const b=n.body;if(b.type==='BlockStatement')inserts.push([b.start+1,'__eldiGuard();']);else inserts.push([b.start,'{__eldiGuard();'],[b.end,'}']);}if(['FunctionDeclaration','FunctionExpression','ArrowFunctionExpression'].includes(n.type)&&n.body.type==='BlockStatement')inserts.push([n.body.start+1,'__eldiGuard();']);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object'&&v.type)walk(v);}walk(ast);for(const[pos,s]of inserts.sort((a,b)=>b[0]-a[0]))code=code.slice(0,pos)+s+code.slice(pos);return `(function(){let __eldiCount=0;function __eldiGuard(){if(++__eldiCount>100000)throw Error('Previše koraka: provjeri petlju ili rekurziju.');}\ntry {\n${code}\n} catch (__eldiError) { console.error(__eldiError.message || String(__eldiError)); }\n})();`;}
export function webUI(c){const w=c.work;if(!w.web.html)w.web={...webExamples.stranica};let language='html',editor,debounce,frame,disposed=false;let jsPending='';
 c.body.innerHTML=`<div class="s33-controls"><label>Početni projekat<select id="s33-web-example">${Object.keys(webExamples).map(k=>`<option>${k}</option>`).join('')}</select></label><button id="s33-web-load">Učitaj primjer</button><button id="s33-web-run" class="primary">▶ Pokreni JavaScript</button><button id="s33-web-stop">Zaustavi / osvježi</button><button id="s33-web-check">Provjeri pristupačnost</button><button id="s33-web-zip">Izvezi web ZIP</button><label>Prikaz<select id="s33-web-size"><option value="100%">Računar</option><option value="390px">Telefon · 390 px</option></select></label></div><div class="s33-two"><div class="s33-panel"><div class="s33-tabs">${['html','css','js'].map(k=>`<button data-web-lang="${k}">${k.toUpperCase()}</button>`).join('')}</div><textarea id="s33-web-code" aria-label="Kod web stranice" spellcheck="false"></textarea><p class="s33-caption">HTML i CSS osvježavaju se tokom pisanja. JavaScript pokrećeš dugmetom. Pregled nema pristup profilu, datotekama ili mreži.</p></div><div class="s33-panel"><div id="s33-preview-host"></div><h3>Konzola i provjere</h3><pre id="s33-web-console" role="status"></pre></div></div>`;
 function preview(runJS=false){if(disposed)return;try{jsPending=runJS?instrument(w.web.js):'';frame?.remove();frame=document.createElement('iframe');frame.id='s33-web-frame';frame.title='Pregled učeničkog web projekta';frame.sandbox='allow-scripts';frame.src=c.asset('studio33-preview.html');frame.style.width=$('s33-web-size').value;$('s33-preview-host').append(frame);}catch(e){$('s33-web-console').textContent='JavaScript: '+e.message;}}
 function receive(e){if(e.source!==frame?.contentWindow||!e.data?.eldi33Preview)return;const m=e.data;if(m.kind==='loaded'){frame.contentWindow.postMessage({type:'eldi33-preview',html:w.web.html,css:w.web.css,js:jsPending},'*');return;}const log=$('s33-web-console');if(log)log.textContent=(log.textContent+'\n'+m.kind+': '+m.text).slice(-12000);}
 window.addEventListener('message',receive);
 function tab(k){language=k;editor?.destroy();$('s33-web-code').value=w.web[k];editor=edit('s33-web-code',k==='js'?'javascript':k,()=>preview(true));c.body.querySelectorAll('[data-web-lang]').forEach(b=>b.classList.toggle('active',b.dataset.webLang===k));$('s33-web-code').oninput=()=>{w.web[language]=$('s33-web-code').value;c.save();clearTimeout(debounce);if(language!=='js')debounce=setTimeout(()=>preview(),400);};}
 c.body.querySelectorAll('[data-web-lang]').forEach(b=>b.onclick=()=>tab(b.dataset.webLang));$('s33-web-load').onclick=()=>{w.web={...webExamples[$('s33-web-example').value]};tab(language);preview();c.save();};$('s33-web-run').onclick=()=>{$('s33-web-console').textContent='';preview(true);};$('s33-web-stop').onclick=()=>preview();$('s33-web-size').onchange=()=>{if(frame)frame.style.width=$('s33-web-size').value;};
 $('s33-web-check').onclick=()=>{const doc=new DOMParser().parseFromString(w.web.html,'text/html'),checks=[['Naslov h1',!!doc.querySelector('h1')],['Glavni sadržaj main',!!doc.querySelector('main')],['Slike imaju alt tekst',[...doc.images].every(i=>i.hasAttribute('alt'))],['Dugmad imaju naziv',[...doc.querySelectorAll('button')].every(b=>b.textContent.trim()||b.getAttribute('aria-label'))],['Polja imaju oznake',[...doc.querySelectorAll('input,textarea,select')].every(el=>el.hasAttribute('aria-label')||el.closest('label')||[...doc.querySelectorAll('label')].some(l=>l.htmlFor===el.id&&el.id))]];const details=checks.map(([n,ok])=>(ok?'✓ ':'✗ ')+n).join('\n');$('s33-web-console').textContent=details+'\nOvo su osnovne automatske provjere; smisao teksta i upotrebljivost pregleda nastavnik.';report(c,'Web: osnovne provjere',checks.filter(x=>x[1]).length,checks.length,details);};
 $('s33-web-zip').onclick=()=>{const html=`<!doctype html><html lang="bs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(w.title)}</title><link rel="stylesheet" href="style.css"></head><body>${w.web.html}<script src="script.js"></script></body></html>`;download('ELDI-33-moj-web-projekat.zip',zipSync({'index.html':strToU8(html),'style.css':strToU8(w.web.css),'script.js':strToU8(w.web.js),'UPUTE.txt':strToU8('Raspakuj ZIP i otvori index.html. Izvozni kod je tvoj izvorni JavaScript.\n'+w.notes)}),'application/zip');};
 tab('html');preview();return()=>{disposed=true;clearTimeout(debounce);window.removeEventListener('message',receive);editor?.destroy();frame?.remove();};
}
const seed=`CREATE TABLE IF NOT EXISTS clanovi(id INTEGER PRIMARY KEY, ime TEXT NOT NULL, razred INTEGER);\nCREATE TABLE IF NOT EXISTS knjige(id INTEGER PRIMARY KEY, naslov TEXT NOT NULL, primjerci INTEGER);\nCREATE TABLE IF NOT EXISTS posudbe(clan_id INTEGER REFERENCES clanovi(id), knjiga_id INTEGER REFERENCES knjige(id), vraceno INTEGER DEFAULT 0);\nINSERT OR IGNORE INTO clanovi VALUES(1,'Učenik A',7),(2,'Učenik B',8),(3,'Učenik C',7);\nINSERT OR IGNORE INTO knjige VALUES(1,'Mali princ',4),(2,'Orlovi rano lete',6),(3,'Družba Pere Kvržice',3);\nINSERT INTO posudbe SELECT 1,1,0 WHERE NOT EXISTS(SELECT 1 FROM posudbe);\nSELECT * FROM knjige;`;
export const sqlTasks=[
 ['Sve knjige','Prikaži sve kolone tabele knjige.','SELECT * FROM knjige;'],['Abecedni red','Prikaži naslove knjiga abecednim redom.','SELECT naslov FROM knjige ORDER BY naslov;'],['Dostupni primjerci','Prikaži naslov i primjerci za knjige s najmanje 4 primjerka, poredano po id.','SELECT naslov, primjerci FROM knjige WHERE primjerci >= 4 ORDER BY id;'],['Ukupan fond','Izračunaj zbir primjeraka. Naziv kolone: ukupno.','SELECT SUM(primjerci) AS ukupno FROM knjige;'],['Sedmi razred','Prikaži ime članova sedmog razreda, poredano po id.','SELECT ime FROM clanovi WHERE razred=7 ORDER BY id;'],['Grupisanje','Prikaži razred i broj članova kao broj, poredano po razredu.','SELECT razred,COUNT(*) AS broj FROM clanovi GROUP BY razred ORDER BY razred;'],['Ko je posudio?','Prikaži ime člana i naslov posuđene knjige.','SELECT c.ime,k.naslov FROM posudbe p JOIN clanovi c ON c.id=p.clan_id JOIN knjige k ON k.id=p.knjiga_id;'],['Najviše primjeraka','Prikaži naslov knjige s najviše primjeraka.','SELECT naslov FROM knjige ORDER BY primjerci DESC LIMIT 1;'],['Prosjek','Prikaži prosječan broj primjeraka kao prosjek.','SELECT AVG(primjerci) AS prosjek FROM knjige;'],['Bez posudbe','Prikaži imena članova bez posudbe, poredano po id.','SELECT ime FROM clanovi WHERE id NOT IN (SELECT clan_id FROM posudbe) ORDER BY id;']];
export function sqlUI(c){let worker,seq=0,pending=new Map(),disposed=false,editor;const w=c.work;
 c.body.innerHTML=`<div class="s33-controls"><button id="s33-sql-run" class="primary">▶ Izvrši SQL</button><button id="s33-sql-seed">Nova ogledna biblioteka</button><button id="s33-sql-export">Izvezi bazu SQLite</button><label>Uvezi SQLite<input id="s33-sql-import" type="file" accept=".sqlite,.db"></label><label>Zadatak<select id="s33-sql-task">${sqlTasks.map((t,i)=>`<option value="${i}">${i+1}. ${t[0]}</option>`).join('')}</select></label><button id="s33-sql-check">Provjeri upit</button><button id="s33-sql-solution">Objašnjenje / rješenje</button></div><p id="s33-sql-statement" class="s33-task"></p><div class="s33-two"><div class="s33-panel"><textarea id="s33-sql-code" aria-label="SQL upit"></textarea><details><summary>Šema biblioteke</summary><p>clanovi: id → ime, razred</p><p>knjige: id → naslov, primjerci</p><p>posudbe: clan_id → clanovi.id; knjiga_id → knjige.id; vraceno</p><p>SELECT čita, INSERT dodaje, UPDATE mijenja, DELETE briše. U projektu se čuva stvarna SQLite baza. Ogledni podaci su izmišljeni.</p></details></div><div class="s33-panel"><h3>Rezultat</h3><div id="s33-sql-result"></div></div></div>`;
 function start(){worker=new Worker(c.asset('studio33-sql-worker.js'));worker.onmessage=({data:r})=>{const p=pending.get(r.id);if(p){clearTimeout(p.timer);pending.delete(r.id);r.ok?p.resolve(r):p.reject(Error(r.error));}};worker.onerror=e=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error(e.message));}pending.clear();};}
 function query(sql,{reset=false,load=w.database}={}){if(disposed)return Promise.reject(Error('Radionica zatvorena.'));return new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{worker.terminate();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Upit je prekoračio 4 sekunde. Prethodno sačuvana baza je zadržana.'));}pending.clear();start();},4000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,sql,load,reset});});}
 function show(r){$('s33-sql-result').innerHTML=r.results.length?r.results.map(t=>table(t.columns,t.values)).join(''):`<p>Izmijenjeno redova: ${r.modified}.</p>`;}
 async function run(){try{const r=await query($('s33-sql-code').value);if(disposed)return;w.sql=$('s33-sql-code').value;w.database=r.database;c.save();show(r);note('SQL je izvršen.');}catch(e){if(!disposed)note(e.message,true);}}
 $('s33-sql-code').value=w.sql||'SELECT * FROM knjige;';$('s33-sql-code').oninput=()=>{w.sql=$('s33-sql-code').value;c.save();};editor=edit('s33-sql-code','sql',run);$('s33-sql-run').onclick=run;
 $('s33-sql-seed').onclick=async()=>{try{const r=await query(seed,{reset:true,load:''});if(disposed)return;w.database=r.database;c.save();show(r);note('Nova ogledna baza je spremna.');}catch(e){if(!disposed)note(e.message,true);}};
 $('s33-sql-task').onchange=()=>{$('s33-sql-statement').textContent=sqlTasks[+$('s33-sql-task').value][1]+' Provjera koristi početne ogledne podatke.';};$('s33-sql-task').onchange();
 $('s33-sql-check').onclick=async()=>{try{const t=sqlTasks[+$('s33-sql-task').value],clean=await query(seed,{reset:true,load:''}),expected=await query(t[2],{load:clean.database}),actual=await query($('s33-sql-code').value,{load:clean.database}),ok=JSON.stringify(actual.results)===JSON.stringify(expected.results);if(disposed)return;show(actual);const detail=ok?'Upit vraća očekivane kolone i redove.':'Očekivano: '+JSON.stringify(expected.results)+'\nDobijeno: '+JSON.stringify(actual.results);report(c,'SQL: '+t[0],ok?10:0,10,detail);note(detail,!ok);}catch(e){if(!disposed)note(e.message,true);}};
 $('s33-sql-solution').onclick=()=>note(sqlTasks[+$('s33-sql-task').value][2]);$('s33-sql-export').onclick=()=>{if(!w.database){note('Prvo izvrši upit.');return;}download('ELDI-biblioteka.sqlite',Uint8Array.from(atob(w.database),c=>c.charCodeAt(0)),'application/vnd.sqlite3');};$('s33-sql-import').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>1000000)throw Error('Baza mora biti manja od 1 MB.');const bytes=new Uint8Array(await f.arrayBuffer());let str='';for(const b of bytes)str+=String.fromCharCode(b);const r=await query('SELECT name FROM sqlite_master WHERE type=\'table\';',{load:btoa(str)});if(disposed)return;w.database=r.database;c.save();show(r);}catch(e){if(!disposed)note(e.message,true);}};
 start();if(!w.database)$('s33-sql-seed').click();else run();return()=>{disposed=true;worker?.terminate();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Radionica zatvorena.'));}pending.clear();editor?.destroy();};
}
