(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ELDI3333=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const rows=[
[5,'m','operations','Redoslijed računskih operacija','Prvo računaj u zagradama, zatim množenje i dijeljenje, a na kraju sabiranje i oduzimanje.','Prepoznaj redoslijed i obrazloži svaki korak.','debug'],
[5,'m','fractions','Razlomci kao dijelovi cjeline','Kod jednakih nazivnika sabiramo brojnike. Nazivnik opisuje veličinu jednog dijela i ostaje isti.','Saberi razlomke i protumači rezultat kao dio cjeline.','scene'],
[5,'m','rectangle','Obim i površina pravougaonika','Obim je dužina granice: O = 2(a + b). Površina je broj jediničnih kvadrata: P = a · b.','Razlikuj obim od površine i koristi odgovarajuće jedinice.','scene'],
[5,'m','units','Mjere i pretvaranje jedinica','Jedan metar ima 100 centimetara. Kod površine faktor pretvaranja kvadriramo: 1 m² = 10 000 cm².','Pretvori dužine i površine bez miješanja jedinica.','data'],
[5,'i','binary','Binarni zapis','Mjesta u binarnom zapisu imaju vrijednosti 1, 2, 4, 8, 16… zdesna nalijevo. Saberi samo mjesta na kojima je cifra 1.','Pretvori binarni broj u dekadni.','logic'],
[5,'i','sequence','Algoritam i slijed naredbi','Program izvršava naredbe redom. Nova dodjela mijenja prethodnu vrijednost varijable.','Prati stanje varijable poslije svake naredbe.','scene'],
[5,'i','loops','Ponavljanje i robot','Petlja ponavlja isti niz naredbi. Broj izvršavanja pomnoži s pomakom u jednom koraku.','Predvidi rezultat petlje prije pokretanja blokova.','robot'],
[6,'m','integers','Cijeli brojevi','Oduzimanje negativnog broja jednako je sabiranju njegovog suprotnog broja. Znak proizvoda zavisi od broja negativnih faktora.','Računaj sa predznacima i provjeri procjenom.','debug'],
[6,'m','decimals','Decimalni brojevi','Poravnaj decimalne zareze pri sabiranju. Pri množenju prvo pomnoži cijele zapise, pa vrati decimalna mjesta.','Koristi decimalne brojeve u praktičnom računu.','data'],
[6,'m','ratio','Omjer i razmjera','Omjer a : b opisuje odnos dviju količina. Ukupan broj jednakih dijelova je a + b.','Podijeli količinu u zadanom omjeru.','data'],
[6,'m','angles','Uglovi trougla','Zbir unutrašnjih uglova svakog trougla je 180°. Kod jednakokrakog trougla uglovi na osnovici su jednaki.','Odredi nepoznati ugao i obrazloži primijenjeno pravilo.','scene'],
[6,'i','conditions','Grananje i uslovi','Uslov daje tačno ili netačno. Izvršava se samo odgovarajuća grana if/else naredbe.','Odaberi granu i izračunaj konačan rezultat.','debug'],
[6,'i','arrays','Liste i indeksi','U ovom zadatku prvi element ima indeks 0. Dužina liste je broj elemenata, a ne posljednji indeks.','Razlikuj indeks od vrijednosti i prati izmjenu liste.','algorithms'],
[6,'i','storage','Bitovi, bajtovi i memorija','Jedan bajt ima 8 bitova. Oznaka KiB znači 1024 bajta; ne treba je miješati s decimalnim kB.','Izračunaj veličinu podatka uz jasno navedenu jedinicu.','data'],
[7,'m','equation','Linearne jednačine','Jednakost ostaje tačna kada na obje strane izvedemo istu dopuštenu operaciju. Rješenje provjeri zamjenom.','Riješi jednačinu i provjeri dobijenu vrijednost.','debug'],
[7,'m','percent','Procenti i promjena cijene','p% od broja iznosi p/100 puta taj broj. Sniženje se oduzima od početne cijene; uzastopne promjene se množe.','Izračunaj procenat, novu cijenu i dvije promjene.','data'],
[7,'m','triangle','Površina trougla','Površina trougla je P = a · h / 2. Visina mora odgovarati odabranoj osnovici.','Primijeni formulu i razlikuj stranicu od visine.','scene'],
[7,'m','proportion','Direktna i obrnuta proporcionalnost','Kod direktne proporcionalnosti omjer ostaje stalan. Kod obrnute, uz iste uslove rada, stalan je proizvod.','Prepoznaj vrstu zavisnosti i sastavi račun.','data'],
[7,'i','search','Pretraživanje podataka','Linearna pretraga poredi elemente redom. Binarna pretraga zahtijeva sortiranu listu i prepolovljava interval.','Prebroj poređenja i obrazloži izbor postupka.','algorithms'],
[7,'i','html','Struktura web stranice','HTML označava značenje sadržaja. Elementi h1, p, a i li imaju različite uloge; brojanje obuhvata otvorene elemente.','Prepoznaj strukturu liste i veze u dokumentu.','web'],
[7,'i','logic','Logička kola','AND je tačno kada su oba ulaza tačna; OR kada je barem jedan tačan; XOR kada se ulazi razlikuju; NOT obrće vrijednost.','Odredi izlaz složenog logičkog izraza.','logic'],
[8,'m','pythagoras','Pitagorina teorema','U pravouglom trouglu vrijedi a² + b² = c², gdje je c hipotenuza. Teoremu ne primjenjuj na proizvoljan trougao.','Izračunaj hipotenuzu, katetu ili dijagonalu.','scene'],
[8,'m','powers','Stepeni i pravila računanja','Kod množenja stepena iste osnove sabiramo eksponente. Kod stepenovanja stepena eksponente množimo.','Razlikuj sabiranje stepena od množenja stepena.','debug'],
[8,'m','function','Linearna funkcija','U y = kx + n, k opisuje promjenu y po jedinici x, a n vrijednost y za x = 0.','Izračunaj vrijednost funkcije i pronađi nepoznati x.','data'],
[8,'m','polygon','Mnogouglovi','Zbir unutrašnjih uglova n-terougla je (n − 2) · 180°. Broj dijagonala je n(n − 3)/2.','Poveži broj stranica, uglove i dijagonale.','scene'],
[8,'i','sort','Sortiranje i poređenja','Bubble sort poredi susjedne elemente. U jednom prolazu najveći element prelazi na kraj neobrađenog dijela.','Prati jedan prolaz i izbroj zamjene.','algorithms'],
[8,'i','sql','Upiti nad podacima','SELECT bira kolone, WHERE filtrira redove, a COUNT(*) broji odabrane redove. Uslov se provjerava za svaki red.','Predvidi rezultat filtriranja i provjeri ga u SQL radionici.','sql'],
[8,'i','network','Mreže i prijenos podataka','Vrijeme prijenosa je količina podataka podijeljena brzinom. Bit i bajt nisu ista jedinica; zanemarivanje zaglavlja je pojednostavljenje modela.','Izračunaj idealno vrijeme prijenosa uz ispravne jedinice.','network'],
[9,'m','systems','Sistemi linearnih jednačina','Rješenje sistema zadovoljava obje jednačine. Sabiranjem ili oduzimanjem jednačina možeš eliminisati jednu nepoznatu.','Odredi nepoznatu i provjeri obje jednakosti.','debug'],
[9,'m','quadratic','Kvadratne jednačine','Ako je proizvod dva faktora nula, barem jedan faktor je nula. Kvadratni izraz može imati dva različita realna korijena.','Poveži faktorizaciju, korijene i koeficijente.','debug'],
[9,'m','cylinder','Zapremina i površina tijela','Valjak: V = πr²h i P = 2πr(r + h). Kupa iste osnove i visine ima trećinu zapremine valjka.','Odvoji koeficijent uz π i uporedi tijela.','scene'],
[9,'m','statistics','Srednja vrijednost i medijana','Aritmetička sredina je zbir podijeljen brojem podataka. Za medijanu prvo sortiraj podatke; kod parnog broja uzmi sredinu dva središnja.','Izračunaj i uporedi srednju vrijednost, medijanu i raspon.','data'],
[9,'i','recursion','Rekurzija i bazni slučaj','Rekurzivna funkcija svodi problem na manji. Bazni slučaj prekida pozive. Za faktorijel vrijedi 0! = 1.','Prati pozive funkcije i izračunaj rezultat.','algorithms'],
[9,'i','graph','Grafovi i najkraći put','U nepotežinskom grafu BFS pretražuje po slojevima. Dužina puta je broj grana, a ne broj posjećenih čvorova.','Prepoznaj najkraći put i osnovne veličine grafa.','network'],
[9,'i','complexity','Broj operacija algoritma','Dvije ugniježđene petlje s po n prolaza izvršavaju tijelo n² puta. Tačan broj zavisi od granica petlji.','Izračunaj broj izvršavanja i razlikuj linearni od kvadratnog rasta.','algorithms']
];
const lessons=rows.map(([grade,subject,id,title,explain,outcome,module])=>({grade,subject,id,title,explain,outcome,module}));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,Math.trunc(Number(x)||a)));
function task(id,level=1,seed=1){const l=lessons.find(x=>x.id===id);if(!l)throw Error('Nepoznata nastavna cjelina.');level=clamp(level,1,3);seed=clamp(seed,1,9999);const n=seed%7+2,k=seed%4+2,d=level;let q='',a=0,solution='',hint=l.explain;
const set=(question,answer,explanation)=>{q=question;a=answer;solution=explanation;};
switch(id){
case'operations':d===1?set(`${n} + ${k} · 3 = ?`,n+k*3,`Prvo ${k} · 3 = ${k*3}, zatim ${n} + ${k*3} = ${n+k*3}.`):d===2?set(`(${n} + ${k}) · 3 = ?`,(n+k)*3,`Zagrada daje ${n+k}; ${n+k} · 3 = ${(n+k)*3}.`):set(`(${n} + ${k}) · 3 − ${k}² = ?`,(n+k)*3-k*k,`Zagrada: ${n+k}; proizvod: ${(n+k)*3}; kvadrat: ${k*k}; razlika: ${(n+k)*3-k*k}.`);break;
case'fractions':set(`${n}/${n+k+5} + ${k*d}/${n+k+5} = ? (upiši razlomak ili decimalni broj)`,(n+k*d)/(n+k+5),`Zajednički nazivnik je ${n+k+5}. Zbir brojnika je ${n+k*d}, pa je rezultat ${n+k*d}/${n+k+5}.`);break;
case'rectangle':d===1?set(`Pravougaonik ima stranice ${n} cm i ${k} cm. Koliki je obim u cm?`,2*(n+k),`O = 2(${n} + ${k}) = ${2*(n+k)} cm.`):d===2?set(`Pravougaonik ima stranice ${n+4} cm i ${k+2} cm. Kolika je površina u cm²?`,(n+4)*(k+2),`P = ${n+4} · ${k+2} = ${(n+4)*(k+2)} cm².`):set(`Površina pravougaonika je ${(n+4)*(k+2)} cm², a jedna stranica ${k+2} cm. Koliki je obim u cm?`,2*(n+k+6),`Druga stranica: ${(n+4)*(k+2)} ÷ ${k+2} = ${n+4}; O = ${2*(n+k+6)} cm.`);break;
case'units':d===1?set(`Koliko centimetara ima ${n} m?`,n*100,`${n} · 100 = ${n*100} cm.`):d===2?set(`Koliko metara je ${n*100+k*10} cm?`,n+k/10,`${n*100+k*10} ÷ 100 = ${n+k/10} m.`):set(`Koliko cm² ima ${n} m²?`,n*10000,`1 m² = 100 · 100 cm². Zato ${n} m² = ${n*10000} cm².`);break;
case'binary':{const v=n+k*d*3;set(`Pretvori binarni broj ${v.toString(2)} u dekadni.`,v,`${v.toString(2).split('').map((c,i,s)=>`${c}·${2**(s.length-1-i)}`).join(' + ')} = ${v}.`);break;}
case'sequence':d===1?set(`x = ${n}; x = x + ${k}; ispiši x.`,n+k,`Nova vrijednost x je ${n} + ${k} = ${n+k}.`):d===2?set(`x = ${n}; x = x * ${k}; x = x − 2; ispiši x.`,n*k-2,`Nakon množenja x = ${n*k}; nakon oduzimanja x = ${n*k-2}.`):set(`x = ${n}; y = x + ${k}; x = y * 2; ispiši x + y.`,3*(n+k),`y = ${n+k}; x = ${2*(n+k)}; zbir je ${3*(n+k)}.`);break;
case'loops':set(`Robot počinje na x = ${d===1?0:n}. Ponavlja ${n+d} puta: idi ${k} koraka desno${d===3?'; idi 1 korak lijevo':''}. Na kojoj je x koordinati?`,(d===1?0:n)+(n+d)*(k-(d===3?1:0)),`Pomak u jednom prolazu je ${k-(d===3?1:0)}. Ukupno: početak + ${n+d} · pomak.`);break;
case'integers':d===1?set(`−${n} + ${k} = ?`,-n+k,`Kreći od −${n} za ${k} mjesta udesno: ${-n+k}.`):d===2?set(`−${n} − (−${k}) = ?`,-n+k,`Oduzimanje negativnog broja daje −${n} + ${k} = ${-n+k}.`):set(`(−${n}) · (−${k}) − ${n+k} = ?`,n*k-n-k,`Proizvod je pozitivan ${n*k}; zatim oduzmi ${n+k}.`);break;
case'decimals':set(`Jedna sveska košta ${(n/10+1).toFixed(1)} KM. Koliko košta ${k*d} sveski?`,Math.round((n/10+1)*k*d*100)/100,`Pomnoži cijenu ${(n/10+1).toFixed(1)} i broj sveski ${k*d}.`);break;
case'ratio':set(`Podijeli ${(n+k)*(d+2)} klikera u omjeru ${n} : ${k}. Koliko dobija prvi učenik?`,n*(d+2),`Ima ${n+k} dijelova; jedan dio je ${d+2}. Prvom pripada ${n} · ${d+2} = ${n*(d+2)}.`);break;
case'angles':d===1?set(`Uglovi trougla su ${n*5}° i ${k*10}°. Koliki je treći?`,180-n*5-k*10,`180 − ${n*5} − ${k*10} = ${180-n*5-k*10}°.`):d===2?set(`Vršni ugao jednakokrakog trougla je ${n*10}°. Koliki je ugao na osnovici?`,(180-n*10)/2,`Preostala dva ugla su jednaka: (180 − ${n*10}) / 2.`):set(`Jedan vanjski ugao trougla je ${100+n*5}°, a jedan od dva nesusjedna unutrašnja ${k*10}°. Koliki je drugi nesusjedni?`,100+n*5-k*10,`Vanjski ugao je zbir dva nesusjedna unutrašnja: ${100+n*5} − ${k*10}.`);break;
case'conditions':{const x=n-d;set(`x = ${x}; ako je x > ${k}, y = x * 2; inače y = x + ${d}. Ispiši y.`,x>k?x*2:x+d,`Uslov ${x} > ${k} je ${x>k?'tačan':'netačan'}, pa primjenjujemo ${x>k?'množenje sa 2':'sabiranje sa '+d}.`);break;}
case'arrays':{const arr=[n,k,n+k,n*k];d===1?set(`Lista je [${arr.join(', ')}], prvi indeks je 0. Šta je na indeksu 2?`,arr[2],`Indeksi su 0, 1, 2, 3; na indeksu 2 je ${arr[2]}.`):d===2?set(`a = [${arr.join(', ')}]; a[1] = a[0] + a[3]. Koliko je a[1]?`,n+n*k,`a[0] = ${n}, a[3] = ${n*k}; zbir je ${n+n*k}.`):set(`a = [${arr.join(', ')}]. Koliki je zbir elemenata na parnim indeksima (0 i 2)?`,2*n+k,`${n} + ${n+k} = ${2*n+k}.`);break;}
case'storage':d===1?set(`Koliko bitova ima ${n} bajtova?`,n*8,`${n} · 8 = ${n*8} bitova.`):d===2?set(`Koliko bajtova ima ${k} KiB?`,k*1024,`${k} · 1024 = ${k*1024} bajta.`):set(`Crno-bijela slika ${n*8} × ${k*8} piksela koristi 1 bit po pikselu, bez zaglavlja. Koliko bajtova zauzima?`,n*k*8,`Piksela: ${n*k*64}; toliko je bitova; dijeljenjem sa 8 dobijamo ${n*k*8} bajta.`);break;
case'equation':{const x=n+2;d===1?set(`x + ${k} = ${x+k}. Odredi x.`,x,`Oduzmi ${k} s obje strane: x = ${x}.`):d===2?set(`${k}x − ${n} = ${k*x-n}. Odredi x.`,x,`Dodaj ${n}, zatim podijeli sa ${k}: x = ${x}.`):set(`${k}(x − ${n}) = ${k*(x-n)}. Odredi x.`,x,`Podijeli sa ${k}: x − ${n} = ${x-n}; dodaj ${n}: x = ${x}.`);break;}
case'percent':{const price=(n+2)*100,p=k*5;d===1?set(`Koliko je ${p}% od ${price}?`,price*p/100,`${price} · ${p}/100 = ${price*p/100}.`):d===2?set(`Cijena ${price} KM snižena je ${p}%. Kolika je nova cijena?`,price*(100-p)/100,`Ostaje ${100-p}% cijene: ${price} · ${(100-p)/100}.`):set(`Cijena ${price} KM prvo raste 20%, pa pada 20%. Kolika je konačna cijena?`,price*.96,`${price} · 1,2 · 0,8 = ${price*.96}. Promjene se ne poništavaju.`);break;}
case'triangle':d<3?set(`Osnovica trougla je ${n*d*2} cm, a odgovarajuća visina ${k+2} cm. Kolika je površina u cm²?`,n*d*(k+2),`P = ${n*d*2} · ${k+2} / 2 = ${n*d*(k+2)} cm².`):set(`Površina trougla je ${n*k} cm², a osnovica ${n*2} cm. Kolika je visina u cm?`,k,`h = 2P/a = ${2*n*k}/${n*2} = ${k} cm.`);break;
case'proportion':d<3?set(`${k} jednaka proizvoda koštaju ${k*n} KM. Koliko košta ${k+d+2} takvih proizvoda?`,(k+d+2)*n,`Jedinična cijena je ${n} KM; pomnoži je s ${k+d+2}.`):set(`${k} radnika završi isti posao za ${n*2} dana. Za koliko dana ga završi ${k*2} jednako produktivnih radnika?`,n,`Dvostruko više radnika: upola manje dana. ${n*2}/2 = ${n}.`);break;
case'search':{const count=n+d;d<3?set(`Linearna pretraga liste [${Array.from({length:count},(_,i)=>i+1).join(', ')}] traži ${d===1?count:count+1}. Koliko poređenja napravi?`,count,`Pretraga provjerava svih ${count} elemenata ${d===1?'dok ne pronađe posljednji':'jer traženi broj nije prisutan'}.`):set(`Sortirana lista ima ${2**k-1} elemenata. Koliko poređenja najviše treba standardnoj binarnoj pretrazi?`,k,`Interval se prepolovljava: za 2^${k} − 1 elemenata potrebno je najviše ${k} poređenja.`);break;}
case'html':set(`HTML lista sadrži ${n} elemenata <li>. Dodamo ${k*d} novih <li> elemenata${d===3?' i uklonimo 2 postojeća':''}. Koliko stavki sada prikazuje lista?`,n+k*d-(d===3?2:0),`Svaki <li> predstavlja jednu stavku: ${n} + ${k*d}${d===3?' − 2':''}.`);break;
case'logic':{const A=n%2,B=k%2;const exp=d===1?'A AND B':d===2?'A XOR B':'(NOT A) OR B';set(`A = ${A}, B = ${B}. Izračunaj ${exp}. Upiši 0 ili 1.`,Number(d===1?A&&B:d===2?A!==B:!A||B),`AND traži oba ulaza 1; XOR različite ulaze; NOT ${A} = ${1-A}. Primijeni operator iz zadatka.`);break;}
case'pythagoras':d===1?set(`Katete su ${3*k} i ${4*k}. Kolika je hipotenuza?`,5*k,`c = √(${(3*k)**2} + ${(4*k)**2}) = ${5*k}.`):d===2?set(`Hipotenuza je ${13*k}, a jedna kateta ${5*k}. Kolika je druga kateta?`,12*k,`b = √(${(13*k)**2} − ${(5*k)**2}) = ${12*k}.`):set(`Pravougaonik stranica ${8*k} i ${15*k} ima dijagonalu dužine?`,17*k,`d = √(${(8*k)**2} + ${(15*k)**2}) = ${17*k}.`);break;
case'powers':d===1?set(`2^${k} · 2^${d+1} = 2^x. Koliko je x?`,k+d+1,`Saberi eksponente iste osnove: ${k} + ${d+1}.`):d===2?set(`(3^${k})^${n} = 3^x. Koliko je x?`,k*n,`Kod stepena stepena eksponente množimo: ${k} · ${n}.`):set(`2^${k+3} ÷ 2^${k} = ?`,8,`2^(${k+3} − ${k}) = 2³ = 8.`);break;
case'function':d<3?set(`y = ${k}x ${d===1?'+':'−'} ${n}. Koliko je y za x = ${n+d}?`,k*(n+d)+(d===1?n:-n),`Zamijeni x: ${k} · ${n+d} ${d===1?'+':'−'} ${n}.`):set(`y = ${k}x + ${n}. Za koju vrijednost x je y = ${k*(n+1)+n}?`,n+1,`Oduzmi ${n} i podijeli sa ${k}: x = ${n+1}.`);break;
case'polygon':{const sides=n+3;d===1?set(`Koliki je zbir unutrašnjih uglova ${sides}-terougla (u stepenima)?`,(sides-2)*180,`(${sides} − 2) · 180 = ${(sides-2)*180}°.`):d===2?set(`Koliko dijagonala ima ${sides}-terougao?`,sides*(sides-3)/2,`${sides}(${sides} − 3)/2 = ${sides*(sides-3)/2}.`):set(`Pravilni mnogougao ima ${k*3} stranica. Koliki je njegov vanjski ugao?`,360/(k*3),`Zbir vanjskih uglova je 360°; jedan je 360/${k*3}°.`);break;}
case'sort':{const arr=d===1?[n+3,n,n+2]:d===2?[n+4,n+3,n+2,n]:[n+5,n+4,n+3,n+2,n];set(`Jedan prolaz bubble sorta slijeva nadesno kroz [${arr.join(', ')}], rastući poredak. Koliko zamjena napravi?`,arr.length-1,`Prvi broj je najveći i zamijeni mjesto sa svakim od ${arr.length-1} susjeda na putu do kraja.`);break;}
case'sql':{const values=[n,k,n+k,n+2,k+1],limit=d===1?k:d===2?n:n+k;const count=values.filter(v=>v>=limit).length;set(`Tabela ima vrijednosti bodovi: ${values.join(', ')}. Šta vraća SELECT COUNT(*) FROM radovi WHERE bodovi >= ${limit}?`,count,`Uslov zadovoljavaju: ${values.filter(v=>v>=limit).join(', ')||'nijedna vrijednost'}. Broj redova je ${count}.`);break;}
case'network':{const mb=n*d,rate=k*2;set(`Datoteka ima ${mb} MB (1 MB = 1 000 000 bajtova), veza ${rate} Mbit/s. Koliko sekundi traje idealan prijenos bez dodatnih troškova?`,mb*8/rate,`Količina je ${mb*8} Mbit; vrijeme = ${mb*8}/${rate} = ${mb*8/rate} s.`);break;}
case'systems':{const x=n+d,y=k;set(`x + y = ${x+y}; ${d===1?'x − y':`2x + y`} = ${d===1?x-y:2*x+y}. Odredi ${d===3?'y':'x'}.`,d===3?y:x,d===1?`Saberi jednačine: 2x = ${2*x}; x = ${x}.`:`Oduzmi prvu od druge: x = ${x}. Zatim y = ${x+y} − ${x} = ${y}.`);break;}
case'quadratic':d===1?set(`(x − ${n})(x − ${n+k}) = 0. Koji je manji korijen?`,n,`Korijeni su ${n} i ${n+k}; manji je ${n}.`):d===2?set(`x² − ${n+k}x + ${n*k} = 0. Koliki je zbir korijena?`,n+k,`Faktori su (x − ${n})(x − ${k}); zbir korijena je ${n+k}.`):set(`x² − ${2*n}x + ${n*n-k*k} = 0. Koliki je veći korijen?`,n+k,`(x − ${n})² = ${k*k}; korijeni su ${n-k} i ${n+k}.`);break;
case'cylinder':d===1?set(`Valjak ima r = ${k}, h = ${n}. V = Kπ. Odredi K.`,k*k*n,`V = π · ${k}² · ${n} = ${k*k*n}π.`):d===2?set(`Valjak ima r = ${k}, h = ${n}. Ukupna površina P = Kπ. Odredi K.`,2*k*(k+n),`P = 2π · ${k}(${k} + ${n}) = ${2*k*(k+n)}π.`):set(`Kupa ima r = ${k}, h = ${n*3}. V = Kπ. Odredi K.`,k*k*n,`V = πr²h/3 = π · ${k*k} · ${n*3}/3 = ${k*k*n}π.`);break;
case'statistics':{const arr=[n,n+2,n+4,n+6,n+18];d===1?set(`Odredi aritmetičku sredinu: ${arr.join(', ')}.`,n+6,`Zbir ${5*n+30} podijeli sa 5: ${n+6}.`):d===2?set(`Odredi medijanu: ${[arr[4],arr[0],arr[3],arr[1],arr[2]].join(', ')}.`,n+4,`Sortiraj: ${arr.join(', ')}. Srednji podatak je ${n+4}.`):set(`Odredi raspon: ${arr.join(', ')}.`,18,`Najveći minus najmanji: ${n+18} − ${n} = 18.`);break;}
case'recursion':{const v=k+(d===3?1:0),fac=Array.from({length:v},(_,i)=>i+1).reduce((s,x)=>s*x,1);d===2?set(`f(0)=1; f(n)=n·f(n−1). Koliko ukupno poziva, uključujući početni i f(0), nastaje za f(${v})?`,v+1,`Pozivi su f(${v}), f(${v-1}), …, f(0): ukupno ${v+1}.`):set(`f(0)=1; f(n)=n·f(n−1). Koliko je f(${v})?`,fac,`${Array.from({length:v},(_,i)=>i+1).join(' · ')} = ${fac}.`);break;}
case'graph':d===1?set(`Put kroz graf prolazi čvorove A → B → C → D${k>3?' → E':''}. Koliko grana sadrži?`,k>3?4:3,'Broj grana na putu za jedan je manji od broja navedenih čvorova.'):d===2?set(`Neusmjeren graf ima ${n+k} grana. Koliki je zbir stepena svih čvorova?`,2*(n+k),`Svaka grana doprinosi dvama stepenima: 2 · ${n+k}.`):set('Graf ima grane A–B, A–C, B–D, C–D, D–E, B–E. Kolika je dužina najkraćeg puta A–E?',2,'Put A–B–E ima dvije grane; direktna grana A–E ne postoji.');break;
case'complexity':d===1?set(`Petlja prolazi i = 1, 2, …, ${n*k}. Koliko puta izvrši tijelo?`,n*k,`Jedan prolaz za svaku od ${n*k} vrijednosti.`):d===2?set(`Vanjska petlja ima ${n} prolaza, a unutrašnja ${k} prolaza za svaki vanjski. Koliko je ukupno izvršavanja unutrašnjeg tijela?`,n*k,`${n} · ${k} = ${n*k}.`):set(`Za i = 1, …, ${n}, unutrašnja petlja radi i puta. Koliko ukupno izvršavanja?`,n*(n+1)/2,`1 + 2 + … + ${n} = ${n} · ${n+1}/2 = ${n*(n+1)/2}.`);break;
}
return{id:`${id}:${d}:${seed}`,topic:id,grade:l.grade,subject:l.subject,level:d,seed,question:q,answer:a,solution,hint,tolerance:1e-6};}
function number(value){let s=String(value??'').trim().replace(/−/g,'-').replace(/,/g,'.');if(s.length>80||!s)return NaN;if(/^[+-]?\d+(?:\.\d+)?\s*\/\s*[+-]?\d+(?:\.\d+)?$/.test(s)){const[a,b]=s.split('/').map(Number);return b===0?NaN:a/b;}return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)?Number(s):NaN;}
const check=(q,v)=>Number.isFinite(number(v))&&Math.abs(number(v)-q.answer)<=Math.max(1,Math.abs(q.answer))*q.tolerance;
function round({grade=5,subject='all',level=2,seed=1,count=10}={}){let pool=lessons.filter(l=>l.grade===clamp(grade,5,9)&&(subject==='all'||l.subject===subject));if(!pool.length)throw Error('Nema cjelina za odabrani predmet.');return Array.from({length:clamp(count,3,20)},(_,i)=>task(pool[(i+seed)%pool.length].id,level,seed+i*11));}
function recommend(history,grade,subject='all'){const pool=lessons.filter(l=>l.grade===grade&&(subject==='all'||l.subject===subject));return pool.map(l=>{const attempts=history.filter(x=>x.topic===l.id).slice(-8);return{...l,attempts:attempts.length,accuracy:attempts.length?attempts.filter(x=>x.ok).length/attempts.length:0};}).sort((a,b)=>a.accuracy-b.accuracy||a.attempts-b.attempts);}
function measures(o){const{a,b,h,r,n,type}=o;let volume,area,formula;const base=n*a*a/(4*Math.tan(Math.PI/n));switch(type){case'cube':volume=a**3;area=6*a*a;formula='V = a³; P = 6a²';break;case'cuboid':volume=a*b*h;area=2*(a*b+a*h+b*h);formula='V = abh; P = 2(ab + ah + bh)';break;case'cylinder':volume=Math.PI*r*r*h;area=2*Math.PI*r*(r+h);formula='V = πr²h; P = 2πr(r + h)';break;case'cone':volume=Math.PI*r*r*h/3;area=Math.PI*r*(r+Math.hypot(r,h));formula='V = πr²h/3; P = πr(r + s)';break;case'sphere':volume=4*Math.PI*r**3/3;area=4*Math.PI*r*r;formula='V = 4πr³/3; P = 4πr²';break;case'prism':volume=base*h;area=2*base+n*a*h;formula='B = na²/(4 tan(π/n)); V = Bh; P = 2B + nah';break;case'pyramid':volume=base*h/3;area=base+n*a*Math.hypot(h,a/(2*Math.tan(Math.PI/n)))/2;formula='V = Bh/3; P = B + nas/2';break;default:throw Error('Nepoznato tijelo.');}return{volume,area,formula};}
return{lessons,task,number,check,round,recommend,measures,phases:[['Uvod',5],['Primjer',10],['Samostalan rad',20],['Provjera',7],['Osvrt',3]]};
});
