(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ELDIStudio33Engine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const TYPES=['cube','cuboid','prism','pyramid','cylinder','cone','sphere'];
const finite=(v,min,max,def)=>Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):def;
const text=(v,n=200)=>typeof v==='string'?v.slice(0,n):'';
function clone(v){return JSON.parse(JSON.stringify(v));}
function safeData(v,limit=2500000){const raw=JSON.stringify(v);if(!raw||raw.length>limit)throw Error('Projekat prelazi 2,5 MB.');return JSON.parse(raw,(k,x)=>{if(['__proto__','constructor','prototype'].includes(k))throw Error('Nedozvoljen ključ u projektu.');return x;});}
function object(v={}){return{id:text(v.id||'tijelo',50)||'tijelo',type:TYPES.includes(v.type)?v.type:'cylinder',r:finite(v.r,.1,20,2),h:finite(v.h,.1,30,5),a:finite(v.a,.1,20,3),b:finite(v.b,.1,20,3),n:Math.round(finite(v.n,3,12,6)),x:finite(v.x,-40,40,0),y:finite(v.y,-40,40,0),z:finite(v.z,-40,40,0),rx:finite(v.rx,-3600,3600,0),ry:finite(v.ry,-3600,3600,0),rz:finite(v.rz,-3600,3600,0),color:/^#[0-9a-f]{6}$/i.test(v.color)?v.color:'#38becb',opacity:finite(v.opacity,.15,1,.75)};}
function normalize(v={}){v=safeData(v,30000000);const out={module:text(v.module,30)||'scene',title:text(v.title,100)||'Moje istraživanje',notes:text(v.notes,10000),scene:(Array.isArray(v.scene)?v.scene:[object()]).slice(0,40).map(object),workspace:v.workspace&&typeof v.workspace==='object'?safeData(v.workspace):null,code:text(v.code,100000),web:{html:text(v.web?.html,100000),css:text(v.web?.css,100000),js:text(v.web?.js,100000)},sql:text(v.sql,50000),database:text(v.database,1400000),csv:text(v.csv,100000),projects:[],reports:[],ui:{theme:['dark','light','contrast'].includes(v.ui?.theme)?v.ui.theme:'dark',quality:v.ui?.quality==='simple'?'simple':'full',width:finite(v.ui?.width,240,650,420),speed:finite(v.ui?.speed,20,1500,200),projector:!!v.ui?.projector},versions:[],assignment:null};
 for(const p of (Array.isArray(v.projects)?v.projects:[]).slice(0,20)){if(p&&p.payload)out.projects.push({name:text(p.name,100),date:text(p.date,40),thumbnail:text(p.thumbnail,200000),payload:project(p.payload)});}
 out.extra=v.extra&&typeof v.extra==='object'?safeData(v.extra):{};out.robotWorkspace=v.robotWorkspace?safeData(v.robotWorkspace):null;
 out.versions=(Array.isArray(v.versions)?v.versions:[]).slice(0,20).map(p=>({name:text(p.name,100),date:text(p.date,40),code:text(p.code,100000),workspace:p.workspace?safeData(p.workspace):null}));
 out.reports=(Array.isArray(v.reports)?v.reports:[]).slice(0,50).map(p=>({name:text(p.name,120),date:text(p.date,40),score:finite(p.score,0,100000,0),max:finite(p.max,0,100000,100),details:text(p.details,12000),comment:text(p.comment,3000),grade:text(p.grade,20)}));
 if(v.assignment)out.assignment=assignment(v.assignment);return out;}
function project(v){if(!v||typeof v!=='object')throw Error('Nedostaje sadržaj projekta.');return{extra:v.extra&&typeof v.extra==='object'?safeData(v.extra):{},robotWorkspace:v.robotWorkspace?safeData(v.robotWorkspace):null,module:text(v.module,30)||'scene',title:text(v.title,100),notes:text(v.notes,10000),scene:(Array.isArray(v.scene)?v.scene:[]).slice(0,40).map(object),workspace:v.workspace?safeData(v.workspace):null,code:text(v.code,100000),web:{html:text(v.web?.html,100000),css:text(v.web?.css,100000),js:text(v.web?.js,100000)},sql:text(v.sql,50000),csv:text(v.csv,100000),database:text(v.database,1400000)};}
function assignment(v){return{title:text(v.title,100)||'Projektni zadatak',instructions:text(v.instructions,10000),grade:Math.round(finite(v.grade,5,9,7)),starter:v.starter?project(v.starter):null,rules:(Array.isArray(v.rules)?v.rules:[]).slice(0,30).map(r=>({kind:['object','property','robot','output'].includes(r.kind)?r.kind:'object',id:text(r.id,50),property:['type','r','h','a','b','n','x','y','z','rx','ry','rz','color'].includes(r.property)?r.property:'h',expected:typeof r.expected==='number'?finite(r.expected,-100000,100000,0):text(r.expected,1000),tolerance:finite(r.tolerance,0,100,0.01),points:finite(r.points,0,100,10)}))};}
function evaluate(rules,result){let score=0,max=0;const checks=rules.map(rule=>{const r=assignment({rules:[rule]}).rules[0];max+=r.points;let actual,ok=false;if(r.kind==='robot'){actual=result.robot?.goal;ok=actual===true;}else if(r.kind==='output'){actual=String(result.output||'').trim();ok=actual===String(r.expected).trim();}else{const o=(result.objects||[]).find(o=>o.id===r.id);actual=r.kind==='object'?o?.type:o?.[r.property];ok=typeof r.expected==='number'?typeof actual==='number'&&Math.abs(actual-r.expected)<=r.tolerance:String(actual)===String(r.expected);}if(ok)score+=r.points;return{...r,actual:actual??'nedostaje',ok};});return{score,max,checks};}
function diff(before,after){const a=String(before).split('\n'),b=String(after).split('\n'),n=Math.max(a.length,b.length);return Array.from({length:n},(_,i)=>({line:i+1,before:a[i]??'',after:b[i]??'',changed:a[i]!==b[i]}));}
function csv(source){if(source.length>100000)throw Error('CSV smije imati do 100 000 znakova.');const delimiter=source.split('\n')[0].includes(';')?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<source.length;i++){const ch=source[i];if(ch==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===delimiter&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&source[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=ch;}if(quoted)throw Error('CSV sadrži nezatvoren navodnik.');row.push(cell);if(row.some(Boolean))rows.push(row);if(rows.length>1001)throw Error('Dozvoljeno je do 1000 redova podataka.');if(!rows.length)throw Error('CSV je prazan.');const width=rows[0].length;if(width>30||rows.some(r=>r.length!==width))throw Error('Svaki red mora imati isti broj kolona, najviše 30.');return{headers:rows[0],rows:rows.slice(1)};}
function stats(values){const a=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)throw Error('Nema brojčanih vrijednosti.');const sum=a.reduce((s,v)=>s+v,0),mean=sum/a.length;return{n:a.length,min:a[0],max:a.at(-1),sum,mean,median:a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2,variance:a.reduce((s,v)=>s+(v-mean)**2,0)/a.length};}
function algorithms(kind,input=[7,2,9,4,1],target=4){const a=input.slice(0,18);if(a.some(v=>!Number.isFinite(v)))throw Error('Niz mora sadržavati brojeve.');const frames=[];let comparisons=0,swaps=0;const emit=(note,active=[],extra={})=>frames.push({values:a.slice(),active,note,comparisons,swaps,...extra});emit('Početno stanje');
 if(kind==='bubble'||kind==='insertion'){if(kind==='bubble'){for(let i=0;i<a.length;i++)for(let j=0;j<a.length-i-1;j++){comparisons++;emit('Uporedi susjede',[j,j+1]);if(a[j]>a[j+1]){[a[j],a[j+1]]=[a[j+1],a[j]];swaps++;emit('Zamijeni susjede',[j,j+1]);}}}else for(let i=1;i<a.length;i++)for(let j=i;j>0;j--){comparisons++;emit('Uporedi s prethodnim elementom',[j-1,j]);if(a[j-1]<=a[j])break;[a[j-1],a[j]]=[a[j],a[j-1]];swaps++;emit('Pomjeri manji element ulijevo',[j-1,j]);}emit('Sortiranje završeno');}
 else if(kind==='binary'){a.sort((a,b)=>a-b);emit('Binarna pretraga zahtijeva sortiran niz');let l=0,r=a.length-1;while(l<=r){const m=Math.floor((l+r)/2);comparisons++;emit('Provjeri sredinu intervala',[m],{left:l,right:r});if(a[m]===target){emit('Pronađen broj',[m]);return frames;}if(a[m]<target)l=m+1;else r=m-1;}emit('Broj nije pronađen');}
 else if(kind==='stack'||kind==='queue'){const work=[];a.forEach((v,i)=>{work.push(v);emit('Dodaj '+v,[i],{work:work.slice()});});while(work.length){const v=kind==='stack'?work.pop():work.shift();emit('Ukloni '+v,[],{work:work.slice()});}}
 else if(kind==='recursion'){const n=Math.min(8,Math.max(0,Math.floor(a[0]||0))),stack=[];let value=1;for(let i=n;i>=0;i--){stack.push('faktorijel('+i+')');emit('Poziv funkcije',[],{stack:stack.slice(),value});}while(stack.length){const i=n-stack.length+1;stack.pop();value*=Math.max(1,i);emit('Povratak iz poziva',[],{stack:stack.slice(),value});}}
 else if(kind==='tree'){const tree=[];for(const v of a){let i=0;while(tree[i]!==undefined){comparisons++;emit('Poredi u čvoru '+i,[],{tree:tree.slice()});i=v<tree[i]?i*2+1:i*2+2;if(i>1023)break;}if(i<=1023)tree[i]=v;emit('Umetni '+v,[],{tree:tree.slice()});}}
 else if(kind==='graph'){const edges=[[0,1],[0,2],[1,3],[2,3],[2,4],[3,5],[4,5]],queue=[0],seen=new Set([0]),order=[];while(queue.length){const v=queue.shift();order.push(v);emit('Posjeti čvor '+v,[v],{edges,queue:queue.slice(),visited:order.slice()});for(const [x,y]of edges){const w=x===v?y:y===v?x:null;if(w!==null&&!seen.has(w)){seen.add(w);queue.push(w);}}}}
 return frames;}
const MAZES=[['########','#Sllll.#','#.###l.#','#...#l.#','###.#l.#','#...#G.#','#......#','########'],['########','#S#....#','#.#.##.#','#...#..#','###.#.##','#...#G.#','#......#','########'],['########','#S.....#','#####..#','#......#','#.######','#.....G#','#......#','########']];
function robot(level=0){const map=MAZES[level%MAZES.length];let x=1,y=1,d=0,moves=0,crashes=0;const trace=[[x,y]],dirs=[[1,0],[0,1],[-1,0],[0,-1]];const blocked=(xx,yy)=>!map[yy]||map[yy][xx]==='#'||map[yy][xx]===undefined;return{state:()=>({x,y,d,moves,crashes,goal:map[y][x]==='G',map,trace:clone(trace)}),turn(v){d=((d+Math.round(v))%4+4)%4;},forward(){const[dx,dy]=dirs[d];if(blocked(x+dx,y+dy)){crashes++;return false;}x+=dx;y+=dy;moves++;trace.push([x,y]);return true;},distance(){const[dx,dy]=dirs[d];let n=0;while(n<20&&!blocked(x+dx*(n+1),y+dy*(n+1)))n++;return n;},line(){return ['l','S','G'].includes(map[y][x]);},goal(){return map[y][x]==='G';}};}
function truth(gates){if(!Array.isArray(gates)||gates.length>12)throw Error('Dozvoljeno je do 12 logičkih kola.');const evalRow=(A,B)=>{const vals={A:!!A,B:!!B};for(let i=0;i<gates.length;i++){const g=gates[i],x=vals[g.a],y=vals[g.b];if(x===undefined||(g.op!=='NOT'&&y===undefined))throw Error('Ulaz kola mora biti A, B ili prethodno kolo.');vals['G'+i]=g.op==='AND'?x&&y:g.op==='OR'?x||y:g.op==='XOR'?x!==y:g.op==='NOT'?!x:(()=>{throw Error('Nepoznato kolo.');})();}return{A:Number(A),B:Number(B),...Object.fromEntries(Object.entries(vals).filter(([k])=>k.startsWith('G')).map(([k,v])=>[k,Number(v)]))};};return [[0,0],[0,1],[1,0],[1,1]].map(([a,b])=>evalRow(a,b));}
function networkPath(edges,start,end){const q=[[start]],seen=new Set([start]);while(q.length){const p=q.shift(),v=p.at(-1);if(v===end)return p;for(const [a,b]of edges){const n=a===v?b:b===v?a:null;if(n!==null&&!seen.has(n)){seen.add(n);q.push([...p,n]);}}}return [];}
function cpu(program){const lines=String(program).trim().split('\n').filter(x=>x.trim()),frames=[];let acc=0,pc=0,steps=0,mem={};while(pc<lines.length&&steps++<200){const instruction=lines[pc].trim().split(/\s+/),op=instruction[0].toUpperCase(),n=Number(instruction[1]);let next=pc+1;switch(op){case'LOAD':acc=n;break;case'ADD':acc+=n;break;case'SUB':acc-=n;break;case'STORE':mem[String(instruction[1])]=acc;break;case'READ':acc=mem[String(instruction[1])]??0;break;case'JNZ':if(acc!==0)next=n;break;case'HALT':next=lines.length;break;default:throw Error('Nepoznata instrukcija: '+op);}if(!Number.isFinite(acc)||!Number.isInteger(next)||next<0||next>lines.length)throw Error('Neispravna vrijednost ili adresa instrukcije.');frames.push({pc,acc,mem:{...mem},instruction:lines[pc]});pc=next;}if(steps>200)throw Error('Prekoračeno 200 instrukcija; provjeri petlju.');return frames;}
return{TYPES,finite,clone,object,normalize,project,assignment,evaluate,diff,csv,stats,algorithms,robot,truth,networkPath,cpu,safeData};
});
