'use strict';
(async()=>{
 const status=document.getElementById('web33-storage'),name=document.getElementById('web33-name'),cloudStatus=document.getElementById('cloud-status');
 const endpoint='../online/classroom-119.php?action=';let db,account=null,csrf='',revision=0,cloudReady=false,cloudDirty=false,cloudTimer=null,cloudBusy=false;
 let profile={name:'Učenik',studio33Work:{module:'start'}},lastRevision=0,pendingWrites=0,lastSave=Promise.resolve(),recordKey='profile';window.__eldiReady=false;
 async function session(){const res=await fetch(endpoint+'status',{credentials:'same-origin',cache:'no-store'});const s=await res.json();if(!s.ok||s.features!=='complete-119')throw Error('Online učionica još nije nadograđena.');return s;}
 async function request(action,payload){const s=await session();if(!s.user||s.user.id!==account?.id)throw Error('Prijava je istekla ili je račun promijenjen. Sačuvaj svoju kopiju, pa se ponovo prijavi.');csrf=s.csrf;const res=await fetch(endpoint+action,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const r=await res.json();if(!r.ok)throw Error(r.error||'Čuvanje nije uspjelo.');return r;}
 try{const s=await session();account=s.user;csrf=s.csrf;if(account){recordKey='account:'+account.id;profile.name=account.display_name;}}catch{}
 try{
  db=await new Promise((resolve,reject)=>{const r=indexedDB.open('eldi-studio33',1);r.onupgradeneeded=()=>r.result.createObjectStore('work');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  const old=await new Promise((resolve,reject)=>{const r=db.transaction('work').objectStore('work').get(recordKey);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  if(old){if(old.format==='ELDI-LOCAL-119'){profile=old.profile;revision=old.revision||0;cloudDirty=!!old.dirty;}else profile=old;}
  status.textContent='Rad se automatski čuva u ovom pregledniku. Za vlastitu kopiju koristi „Izvezi rad“. ';
 }catch(e){status.textContent='Lokalno čuvanje nije dostupno. Redovno koristi „Izvezi rad“. '+e.message;}
 async function write(){if(!db)return;const ownRevision=++lastRevision;pendingWrites++;const indicator=document.getElementById('s33-save-state');if(indicator)indicator.textContent='Čuvanje…';try{await new Promise((resolve,reject)=>{const tx=db.transaction('work','readwrite');tx.objectStore('work').put({format:'ELDI-LOCAL-119',profile,revision,dirty:cloudDirty},recordKey);tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error||Error('Čuvanje je prekinuto.'));});if(ownRevision===lastRevision){const el=document.getElementById('s33-save-state');if(el)el.textContent='Sačuvano u pregledniku';}}catch(e){status.textContent='Čuvanje nije uspjelo: '+e.message+'. Izvezi rad prije zatvaranja.';throw e;}finally{pendingWrites--;}}
 function save(){cloudDirty=true;lastSave=write();if(cloudReady){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>saveCloud(),1500);}return lastSave;}
 function mount(){name.value=profile.name;window.ELDIStudio33.mount({root:document.getElementById('web33-app'),profile:()=>profile,save:()=>save().catch(()=>{}),assetBase:new URL('renderer/',location.href),print:()=>window.print()});window.__web33Profile=profile;}
 async function saveCloud(){if(cloudBusy||!account)return;cloudBusy=true;clearTimeout(cloudTimer);document.getElementById('cloud-save').disabled=true;cloudStatus.textContent='Čuvanje na računu…';try{
  const snapshot=JSON.stringify(profile),r=await request('project_save',{revision,profile:JSON.parse(snapshot)});revision=r.revision;cloudReady=true;cloudDirty=JSON.stringify(profile)!==snapshot;await write();cloudStatus.textContent='Sačuvano na računu '+account.display_name+' · '+new Date().toLocaleTimeString('bs-BA');if(cloudDirty)cloudTimer=setTimeout(()=>saveCloud(),1500);
 }catch(e){cloudReady=false;cloudStatus.textContent=e.message+' Rad ostaje u ovom pregledniku. Preuzmi svoju kopiju prije otvaranja rada sa računa.';}finally{cloudBusy=false;document.getElementById('cloud-save').disabled=false;}}
 if(account){cloudStatus.textContent='Račun: '+account.display_name;try{
  const r=await request('project_load',{});
  if(!cloudDirty){if(r.profile)profile=r.profile;revision=r.revision;cloudReady=true;await write();cloudStatus.textContent=r.profile?'Otvoren rad sa računa '+account.display_name+'. Promjene se automatski čuvaju uz internet.':'Novi rad na računu '+account.display_name+'. Promjene se automatski čuvaju uz internet.';}
  else if(revision===r.revision){cloudReady=true;cloudStatus.textContent='Postoji lokalna promjena. Klikni „Sačuvaj na računu“ da je pošalješ.';}
  else{cloudReady=false;cloudStatus.textContent='Sačuvane su dvije različite verzije rada. Preuzmi svoju lokalnu kopiju, pa otvori rad sa računa.';}
 }catch(e){cloudStatus.textContent=e.message;}}
 else cloudStatus.textContent='Rad bez prijave. Za čuvanje i otvaranje rada na drugom uređaju prvo se prijavi u online učionicu.';
 for(const id of ['cloud-save','cloud-load'])document.getElementById(id).disabled=!account;
 document.getElementById('cloud-save').onclick=saveCloud;
 document.getElementById('cloud-load').onclick=async()=>{if(cloudBusy)return;if(cloudDirty&&!confirm('Otvoriti rad sa računa i zamijeniti trenutno otvorenu lokalnu verziju? Prvo preuzmi svoju kopiju ako je želiš sačuvati.'))return;clearTimeout(cloudTimer);cloudBusy=true;document.getElementById('cloud-save').disabled=true;try{const r=await request('project_load',{});if(!r.profile){cloudStatus.textContent='Na računu još nema rada. Klikni Sačuvaj na računu.';return;}clearTimeout(cloudTimer);profile=r.profile;revision=r.revision;cloudDirty=false;cloudReady=true;mount();await write();cloudStatus.textContent='Rad sa računa je otvoren.';}catch(e){cloudStatus.textContent=e.message;}finally{cloudBusy=false;document.getElementById('cloud-save').disabled=false;}};
 document.getElementById('cloud-copy').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({format:'ELDI-CLOUD-119',version:1,profile},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ELDI-moja-kopija.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 document.getElementById('cloud-import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2100000)throw Error('Kopija može imati najviše 2 MB.');const p=JSON.parse(await f.text());if(p.format!=='ELDI-CLOUD-119'||!p.profile?.studio33Work||typeof p.profile.name!=='string')throw Error('Izaberi datoteku sačuvanu dugmetom Preuzmi svoju kopiju.');if(!confirm('Zamijeniti otvoreni rad izabranom kopijom?'))return;profile=p.profile;mount();await save();cloudStatus.textContent='Kopija je otvorena; provjeri status čuvanja na računu.';}catch(err){cloudStatus.textContent=err.message;}e.target.value='';};
 name.oninput=()=>{profile.name=name.value.slice(0,60)||'Učenik';save().catch(()=>{});};
 const selectedModule=new URLSearchParams(location.search).get('mod');if(selectedModule&&window.ELDIStudio33.modules[selectedModule]){profile.studio33Work||={};profile.studio33Work.module=selectedModule;}
 mount();window.__eldiReady=true;window.__web33Flush=async()=>{await lastSave;if(cloudDirty&&cloudReady)await saveCloud();};
 window.addEventListener('beforeunload',e=>{if(pendingWrites||cloudBusy||(account&&cloudDirty)){e.preventDefault();e.returnValue='';}});
})().catch(e=>{document.getElementById('web33-app').textContent='Radionica nije otvorena: '+e.message;});
