'use strict';
window.ELDIBlocksPlus=(()=>{
 let ctx=null,listener=null,selected='',points=new Set(),batchWorker=null,cancelBatch=null,custom=null;
 const $=id=>document.getElementById(id),B=()=>window.ELDIBlocks,ws=()=>B().getWorkspace();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const profile=()=>typeof ctx.profile==='function'?ctx.profile():ctx.profile;
 const work=()=>profile().studioWork;
 function save(){ctx.save();}
 function status(s){if($('bp-status'))$('bp-status').textContent=s;}
 function safely(fn){return async()=>{try{await fn();}catch(e){status(e.message);}};}
 function destroy(){if(listener&&ws())ws().removeChangeListener(listener);listener=null;cancelBatch?.();batchWorker?.terminate();batchWorker=null;ctx=null;custom=null;points=new Set();}
 function toolbox(){
  const original=B().getToolbox(),term=$('bp-search').value.trim().toLocaleLowerCase('bs');
  const beginner=work().mode==='beginner',simple=new Set(['Ulaz / izlaz','Matematika','Logika i uslovi','Petlje','Varijable','Kretanje','Olovka i oblici','Likovi i izgled']);
  const scratch=new Blockly.Workspace();
  try{const contents=original.contents.filter(c=>!beginner||simple.has(c.name)).map(c=>{
   if(!term)return c;
   if(c.custom)return c.name.toLocaleLowerCase('bs').includes(term)?c:null;
   const contents=(c.contents||[]).filter(item=>{let text=item.type;try{const block=scratch.newBlock(item.type);text+=' '+block.toString();block.dispose();}catch{}return(c.name+' '+text).toLocaleLowerCase('bs').includes(term);});
   return contents.length?{...c,contents}:null;
  }).filter(Boolean);ws().updateToolbox({...original,contents:contents.length?contents:[{kind:'category',name:'Nema rezultata',contents:[]}]});}finally{scratch.dispose();}
 }
 function mappedCode(){
  if(!ctx||!$('bp-mapped'))return;
  const lines=B().code('py',true).split('\n');let id='';
  $('bp-mapped').innerHTML=lines.map((line,index)=>{const match=line.match(/# @eldi-block ['"]([^'"]+)['"]/);if(match){id=match[1];return '';}
   return `<button type="button" class="bp-code-line ${id===selected?'bp-selected':''}" data-map="${esc(id)}"><span>${index+1}</span><code>${esc(line)||' '}</code></button>`;
  }).join('');
  $('bp-mapped').onclick=e=>{const id=e.target.closest('[data-map]')?.dataset.map,block=id&&ws().getBlockById(id);if(block){block.select();ws().centerOnBlock(id);}};
 }
 function diagnostics(){const rows=[];for(const block of ws().getAllBlocks(false)){
  const missing=block.inputList.filter(input=>input.type===Blockly.inputs.inputTypes.VALUE&&input.connection&&!input.connection.targetConnection);
  const warning=missing.length?'Nedostaje vrijednost: '+missing.map(i=>i.name).join(', '):null;block.setWarningText(warning);
  if(warning)rows.push(block.toString(70)+': '+warning);
 }status(rows.length?rows.join('\n'):'Nema praznih ulaza vrijednosti. Pokreni testove za provjeru ponašanja.');}
 function shelves(){
  for(const [key,label]of [['backpack','Grupe'],['versions','Verzije']]){
   $('bp-'+key).innerHTML=`<option value="">${label} (${work()[key].length}/20)</option>`+work()[key].map((r,i)=>`<option value="${i}">${esc(r.name)} · ${esc(new Date(r.date).toLocaleString('bs'))}</option>`).join('');
  }
  $('bp-custom').innerHTML='<option value="">Izazov iz glavnog studija</option>'+work().challenges.map((c,i)=>`<option value="${i}">${esc(c.title)}</option>`).join('');
 }
 function remember(key,project,name){work()[key].unshift({name:name.slice(0,120),date:new Date().toISOString(),project:ELDIStudioWork.project(project)});work()[key]=work()[key].slice(0,20);save();shelves();}
 function backpack(){const block=ws().getBlockById(selected);if(!block)throw Error('Prvo označi blok ili grupu koju želiš sačuvati.');const root=block.getRootBlock();remember('backpack',{format:'ELDI-BLOCKS-1',workspace:{blocks:{languageVersion:0,blocks:[Blockly.serialization.blocks.save(root)]},variables:Blockly.serialization.workspaces.save(ws()).variables||[]}},root.toString(70));status('Grupa je sačuvana u ruksaku.');}
 function append(){const index=$('bp-backpack').value;if(index==='')throw Error('Odaberi sačuvanu grupu.');const source=structuredClone(work().backpack[+index].project.workspace);
  // Merge variables by name/type; remap both variable references and every block ID.
  const ids=new Map();for(const v of source.variables||[]){const existing=ws().getVariableMap().getVariable(v.name,v.type||'');ids.set(v.id,existing?.getId()||ws().createVariable(v.name,v.type||'').getId());}
  function remap(v){if(!v||typeof v!=='object')return;for(const[k,x]of Object.entries(v)){if(k==='id'&&typeof x==='string')v[k]=ids.get(x)||Blockly.utils.idGenerator.genUid();else remap(x);}}
  Blockly.Events.setGroup(true);try{for(const block of source.blocks?.blocks||[]){remap(block);const appended=Blockly.serialization.blocks.append(block,ws(),{recordUndo:true});appended.moveBy(40,40);}}finally{Blockly.Events.setGroup(false);}B().update();status('Grupa je dodana. Poništi vraća prethodno stanje.');
 }
 function dialog(title,html){$('bp-dialog')?.remove();const node=document.createElement('dialog');node.id='bp-dialog';node.className='bp-dialog';node.innerHTML=`<div class="row"><h2>${esc(title)}</h2><button id="bp-close" aria-label="Zatvori">✕</button></div>${html}`;ctx.root.append(node);$('bp-close').onclick=()=>node.remove();node.oncancel=()=>node.remove();node.showModal();return node;}
 function teacher(){
  dialog('Novi nastavnički izazov',`<label>Naziv<input id="bp-title" maxlength="160"></label><label>Zadatak<textarea id="bp-statement" maxlength="6000"></textarea></label><p>Sačuvat će se trenutni blokovi kao početni projekat. Testovi porede tekstualni izlaz, bez praznina na početku i kraju.</p><div id="bp-test-rows"></div><button id="bp-add-test">+ Test</button><label>Dozvoljeni tipovi blokova, odvojeni zarezom (prazno = svi)<textarea id="bp-allowed" placeholder="edu_print, math_number, controls_repeat_ext"></textarea></label><button id="bp-use-types">Uzmi tipove iz trenutnog projekta</button><button class="primary" id="bp-save-challenge">Sačuvaj izazov</button><p id="bp-teacher-error" role="status"></p>`);
  function row(){if($('bp-test-rows').children.length>=20)return;const div=document.createElement('section');div.className='bp-test';div.innerHTML='<label>Ulaz<textarea data-input></textarea></label><label>Očekivani izlaz<textarea data-output></textarea></label><label>Bodovi<input data-points type="number" min="1" max="1000" value="10"></label><button data-remove>Ukloni</button>';div.querySelector('[data-remove]').onclick=()=>div.remove();$('bp-test-rows').append(div);}
  row();$('bp-add-test').onclick=row;$('bp-use-types').onclick=()=>$('bp-allowed').value=[...new Set(ws().getAllBlocks(false).map(b=>b.type))].join(', ');
  $('bp-save-challenge').onclick=()=>{try{const challenge=ELDIStudioWork.challenge({id:'custom-'+crypto.randomUUID(),title:$('bp-title').value,statement:$('bp-statement').value,tests:[...$('bp-test-rows').children].map(r=>({input:r.querySelector('[data-input]').value,output:r.querySelector('[data-output]').value,points:+r.querySelector('[data-points]').value})),allowed:$('bp-allowed').value.split(',').map(v=>v.trim()).filter(Boolean),starter:B().serialize()});if(work().challenges.length>=30)throw Error('Najviše 30 vlastitih izazova.');work().challenges.push(challenge);save();shelves();$('bp-custom').value=String(work().challenges.length-1);selectCustom();$('bp-dialog').remove();}catch(e){$('bp-teacher-error').textContent=e.message;}};
 }
 function selectCustom(){const value=$('bp-custom').value;custom=value===''?null:work().challenges[+value];$('bp-custom-text').textContent=custom?custom.title+' — '+custom.statement:'';if(custom){$('challenge-free').click();B().setChallenge({...custom,tests:custom.tests.map(t=>({input:t.input,check:{type:'output',expected:t.output}}))});B().stop();status('Vlastiti izazov je izabran. Dugme Svi testovi provjerava ovaj izazov.');}}
 async function isolated(code,input){return new Promise(resolve=>{let actions=[],done=false,timer;
  function finish(result){if(done)return;done=true;clearTimeout(timer);batchWorker?.terminate();batchWorker=null;cancelBatch=null;resolve({...result,actions});}
  cancelBatch=()=>finish({ok:false,cancelled:true,error:'Provjera je prekinuta.',output:''});batchWorker=new Worker('block-worker.js');batchWorker.onmessage=e=>{const d=e.data;if(d.type==='actions')actions.push(...d.actions);if(d.type==='done')finish(d.result);if(d.type==='error')finish({...d.result,ok:false,error:d.message});};batchWorker.onerror=e=>finish({ok:false,error:e.message,output:''});timer=setTimeout(()=>finish({ok:false,error:'Prekoračeno vrijeme.',output:''}),6000);batchWorker.postMessage({code,input});
 });}
 async function allTests(){
  if(batchWorker)throw Error('Provjera je već u toku.');const session=ctx,chosen=custom||B().getChallenge();if(!chosen)throw Error('Odaberi zadatak u studiju ili vlastiti izazov.');
  if(custom?.allowed.length){const banned=ws().getAllBlocks(false).filter(b=>!custom.allowed.includes(b.type));if(banned.length)throw Error('Izazov ne dozvoljava: '+[...new Set(banned.map(b=>b.type))].join(', '));}
  const tests=chosen.tests?.length?chosen.tests:[{input:chosen.input||'',check:chosen.check}],code=B().code('js',true),rows=[];B().stop();$('bp-all').disabled=true;
  try{for(let i=0;i<tests.length;i++){status(`Provjera ${i+1}/${tests.length}…`);const t=tests[i],r=await isolated(code,t.input||'');if(ctx!==session||r.cancelled)return;const check=t.check||{type:'output',expected:t.output};const passed=B().matchCheck(check,r).correct,max=t.points||1;rows.push({input:t.input||'',expected:check.type==='output'?String(check.expected):JSON.stringify(check),actual:r.error||r.output||JSON.stringify(r.stage),passed,points:passed?max:0,max});}
   const report={title:chosen.title,date:new Date().toISOString(),assisted:!!profile().blockLibrary?.selectedAssisted,tests:rows,notes:'',manualGrade:''};work().reports.unshift(report);work().reports=work().reports.slice(0,50);save();showReport(0);
   status(`${rows.filter(r=>r.passed).length}/${rows.length} testova • ${rows.reduce((n,r)=>n+r.points,0)}/${rows.reduce((n,r)=>n+r.max,0)} bodova. Izvještaj je sačuvan.`);
  }finally{if(ctx===session)$('bp-all').disabled=false;}
 }
 function showReport(index){const report=work().reports[index];if(!report)throw Error('Još nema izvještaja.');dialog(report.title,`<p>${esc(new Date(report.date).toLocaleString('bs'))} · ${report.assisted?'Rad uz pomoć':'Pomoć nije označena'}</p><p>Automatski bodovi: <strong>${report.tests.reduce((n,t)=>n+t.points,0)}/${report.tests.reduce((n,t)=>n+t.max,0)}</strong></p>${report.tests.map((t,i)=>`<details ${t.passed?'':'open'}><summary>Test ${i+1} · ${t.passed?'TAČNO':'NETAČNO'} · ${t.points}/${t.max}</summary><div class="bp-test"><div>Ulaz<pre>${esc(t.input)}</pre></div><div>Očekivano<pre>${esc(t.expected)}</pre></div><div>Dobijeno<pre>${esc(t.actual)}</pre></div></div></details>`).join('')}<label>Nastavnička ocjena (zasebno)<input id="bp-grade" maxlength="80" value="${esc(report.manualGrade)}"></label><label>Komentar<textarea id="bp-notes" maxlength="6000">${esc(report.notes)}</textarea></label><button id="bp-report-save">Sačuvaj komentar</button><button id="bp-report-export">Izvezi izvještaj</button>`);$('bp-report-save').onclick=()=>{report.manualGrade=$('bp-grade').value;report.notes=$('bp-notes').value;save();status('Nastavnički komentar i ocjena su sačuvani.');$('bp-dialog').remove();};$('bp-report-export').onclick=()=>ctx.exportFile('ELDI-blokovi-izvjestaj.json',JSON.stringify({...report,manualGrade:$('bp-grade').value,notes:$('bp-notes').value},null,2),'application/json');}
 function reports(){dialog('Sačuvani izvještaji',work().reports.map((r,i)=>`<p><button data-report="${i}">${esc(r.title)} · ${esc(new Date(r.date).toLocaleString('bs'))}</button></p>`).join('')||'<p>Pokreni Sve testove da sačuvaš prvi izvještaj.</p>');for(const b of $('bp-dialog').querySelectorAll('[data-report]'))b.onclick=()=>showReport(+b.dataset.report);}
 function geometry(action){if(!ctx)return;const raw=profile().labWork||{},solid={...ELDILabEngine.DEFAULT.solid,...raw.solid,type:action.solid,r:action.r,a:action.r,h:action.h};profile().labWork=ELDILabEngine.normalize({...raw,mode:'solid',solid});save();status('3D model je spreman: '+action.solid+'. Otvori laboratorij da ga rotiraš i istražiš.');}
 function mount(options){destroy();ctx=options;profile().studioWork=ELDIStudioWork.normalize(profile().studioWork||{});selected='';
  const node=document.createElement('section');node.className='bp-tools';node.innerHTML=`<div class="bp-primary"><label>Pronađi blok<input id="bp-search" type="search" placeholder="ponovi, ispiši, lista…"></label><label>Nivo<select id="bp-mode"><option value="beginner">Početnik</option><option value="advanced">Napredni</option></select></label><button id="bp-tidy">Uredi blokove</button><button id="bp-undo">↶ Poništi</button><button id="bp-redo">↷ Ponovi</button><button id="bp-fit">Prikaži sve</button><button id="bp-diagnostics">Provjeri spojeve</button></div><details id="bp-details"><summary>Alati za projekte, provjere i učenje</summary><div class="bp-primary"><label class="bp-check"><input id="bp-debug" type="checkbox" checked> Živo izvršavanje / debugger</label><button id="bp-break">Tačka prekida: označeni blok</button><span id="bp-break-count">0 tačaka prekida</span><label>Širina pozornice<input id="bp-width" type="range" min="250" max="550" step="10"></label></div><p>Korak se zaustavlja prije narednog bloka; vrijednosti pokazuju stanje prije tog bloka. Tipke i miš se očitavaju tokom živog izvršavanja. Za igru dodaj kratko čekanje u petlji.</p><div class="bp-primary"><button id="bp-pack">Sačuvaj označenu grupu</button><select id="bp-backpack" aria-label="Sačuvane grupe"></select><button id="bp-append">Dodaj grupu</button><button id="bp-snapshot">Sačuvaj verziju</button><select id="bp-versions" aria-label="Verzije projekta"></select><button id="bp-restore">Vrati verziju</button></div><div class="bp-primary"><select id="bp-custom" aria-label="Vlastiti izazov"></select><button id="bp-teacher">Novi izazov</button><button id="bp-starter">Početni blokovi izazova</button><button id="bp-export-challenge">Izvezi izazov</button><label>Uvezi izazov<input id="bp-import-challenge" type="file" accept=".json"></label></div><p id="bp-custom-text"></p><div class="bp-primary"><button id="bp-all" class="primary">✓ Svi testovi</button><button id="bp-reports">Izvještaji i ocjene</button><button id="bp-lab">3D laboratorij</button><button id="bp-algorithms">Vizualizacija algoritama</button></div><details><summary>Blok ↔ Python: klikni red ili označi blok</summary><pre id="bp-mapped"></pre></details></details><p id="bp-status" role="status" aria-live="polite">Studio je spreman. Projekti se čuvaju u aktivnom profilu.</p>`;
  $('block-studio-section').prepend(node);$('bp-mode').value=work().mode;$('bp-width').value=work().panelWidth;
  function width(){ctx.root.style.setProperty('--bp-side',work().panelWidth+'px');B().resize();}
  width();$('bp-width').oninput=()=>{work().panelWidth=+$('bp-width').value;width();save();};$('bp-search').oninput=toolbox;$('bp-mode').onchange=()=>{work().mode=$('bp-mode').value;save();toolbox();};
  const actions={'bp-tidy':()=>{ws().cleanUp();B().update();},'bp-undo':()=>ws().undo(false),'bp-redo':()=>ws().undo(true),'bp-fit':()=>ws().zoomToFit(),'bp-diagnostics':diagnostics,'bp-pack':backpack,'bp-append':append,'bp-snapshot':()=>{remember('versions',B().serialize(),'Verzija '+(work().versions.length+1));status('Verzija projekta sačuvana.');},'bp-restore':()=>{const index=$('bp-versions').value;if(index==='')throw Error('Odaberi verziju.');const project=structuredClone(work().versions[+index].project);remember('versions',B().serialize(),'Prije vraćanja');B().load(project);status('Verzija vraćena. Prethodni rad je sačuvan.');},'bp-teacher':teacher,'bp-all':allTests,'bp-reports':reports,'bp-starter':()=>{if(!custom)throw Error('Odaberi vlastiti izazov.');remember('versions',B().serialize(),'Prije izazova');B().load(custom.starter||{format:'ELDI-BLOCKS-1',workspace:{blocks:{languageVersion:0,blocks:[]}}});},'bp-export-challenge':()=>{if(!custom)throw Error('Odaberi vlastiti izazov.');ctx.exportFile('ELDI-blokovski-izazov.json',JSON.stringify({format:'ELDI-BLOCK-CHALLENGE-1',challenge:custom},null,2),'application/json');},'bp-lab':()=>ctx.go('laboratory'),'bp-algorithms':()=>{profile().labWork=ELDILabEngine.normalize({...profile().labWork,mode:'algorithms'});save();ctx.go('laboratory');},'bp-break':()=>{if(!selected)throw Error('Prvo označi blok.');points.has(selected)?points.delete(selected):points.add(selected);B().setBreakpoints([...points]);$('bp-break-count').textContent=points.size+' tačaka prekida';status(points.has(selected)?'Tačka prekida dodana na označeni blok.':'Tačka prekida uklonjena.');}};
  for(const[id,fn]of Object.entries(actions))$(id).onclick=safely(fn);
  $('bp-custom').onchange=selectCustom;$('bp-import-challenge').onchange=safely(async()=>{const file=$('bp-import-challenge').files[0];if(!file)return;if(file.size>1500000)throw Error('Izazov može imati do 1.5 MB.');const data=JSON.parse(await file.text());if(data.format!=='ELDI-BLOCK-CHALLENGE-1')throw Error('Nepoznat format izazova.');const c=ELDIStudioWork.challenge(data.challenge);if(work().challenges.length>=30)throw Error('Najviše 30 izazova.');work().challenges.push({...c,id:'custom-'+crypto.randomUUID()});save();shelves();status('Izazov uvezen.');});
  $('brun').onclick=safely(()=>{if(custom?.allowed.length&&ws().getAllBlocks(false).some(b=>!custom.allowed.includes(b.type)))throw Error('Projekat sadrži blokove koje izazov ne dozvoljava.');return ELDIBlockStudio.run({debug:$('bp-debug').checked});});$('bstop').addEventListener('click',()=>{cancelBatch?.();status('Izvršavanje zaustavljeno.');});
  listener=event=>{if(event.type===Blockly.Events.SELECTED)selected=event.newElementId||'';if(!event.isUiEvent||event.type===Blockly.Events.SELECTED)mappedCode();};ws().addChangeListener(listener);shelves();toolbox();mappedCode();B().setBreakpoints([]);ELDIBlockStudio.fitWorkbench();
 }
 return{mount,destroy,geometry,debugStatus:status,allTests};
})();
