'use strict';
window.ELDIBlocks=(()=>{let workspace=null,worker=null,onSave=()=>{},sprites=[],current=0,runningTimer=null,actionQueue=[],animTimer=null,keys=new Set();const JS=javascript.javascriptGenerator,PY=python.pythonGenerator;
const number=(v=10)=>({block:{type:'math_number',fields:{NUM:v}}});const text=t=>({block:{type:'text',fields:{TEXT:t}}});
const defs=[
{type:'edu_move',message0:'idi %1 koraka',args0:[{type:'input_value',name:'N',check:'Number'}],previousStatement:null,nextStatement:null,colour:210},
{type:'edu_turn',message0:'okreni desno %1 °',args0:[{type:'input_value',name:'N',check:'Number'}],previousStatement:null,nextStatement:null,colour:210},
{type:'edu_goto',message0:'idi na x %1 y %2',args0:[{type:'input_value',name:'X',check:'Number'},{type:'input_value',name:'Y',check:'Number'}],previousStatement:null,nextStatement:null,colour:210},
{type:'edu_say',message0:'reci %1',args0:[{type:'input_value',name:'TEXT'}],previousStatement:null,nextStatement:null,colour:280},
{type:'edu_pen',message0:'olovka %1',args0:[{type:'field_dropdown',name:'STATE',options:[['spuštena','1'],['podignuta','0']]}],previousStatement:null,nextStatement:null,colour:160},
{type:'edu_sprite',message0:'izaberi lik %1',args0:[{type:'field_dropdown',name:'S',options:[['Lik 1','0'],['Lik 2','1'],['Lik 3','2']]}],previousStatement:null,nextStatement:null,colour:280},
{type:'edu_wait',message0:'čekaj %1 sekundi',args0:[{type:'input_value',name:'N',check:'Number'}],previousStatement:null,nextStatement:null,colour:45},
{type:'edu_message',message0:'pošalji poruku %1',args0:[{type:'input_value',name:'TEXT'}],previousStatement:null,nextStatement:null,colour:45},
{type:'edu_received',message0:'kada primim %1 %2 radi %3',args0:[{type:'field_input',name:'MESSAGE',text:'start'},{type:'input_dummy'},{type:'input_statement',name:'DO'}],colour:45},
{type:'edu_clone',message0:'napravi klon aktivnog lika',previousStatement:null,nextStatement:null,colour:45},
{type:'edu_clear',message0:'očisti pozornicu',previousStatement:null,nextStatement:null,colour:160},
{type:'edu_key',message0:'pritisnuta tipka %1 ?',args0:[{type:'field_dropdown',name:'KEY',options:[['desno','ArrowRight'],['lijevo','ArrowLeft'],['gore','ArrowUp'],['dolje','ArrowDown'],['razmak',' ']]}],output:'Boolean',colour:160}
];
Blockly.defineBlocksWithJsonArray(defs);const value=(g,b,n)=>g.valueToCode(b,n,g.ORDER_NONE)||'0';
for(const g of [JS,PY]){let py=g===PY,call=(s)=>s+(py?'\n':';\n');g.forBlock.edu_move=(b,g)=>call(`move(${value(g,b,'N')})`);g.forBlock.edu_turn=(b,g)=>call(`turn(${value(g,b,'N')})`);g.forBlock.edu_goto=(b,g)=>call(`go(${value(g,b,'X')}, ${value(g,b,'Y')})`);g.forBlock.edu_say=(b,g)=>call(`say(${g.valueToCode(b,'TEXT',g.ORDER_NONE)||'""'})`);g.forBlock.edu_pen=b=>call(`pen(${b.getFieldValue('STATE')})`);g.forBlock.edu_sprite=b=>call(`sprite(${b.getFieldValue('S')})`);g.forBlock.edu_wait=(b,g)=>call(`wait(${value(g,b,'N')})`);g.forBlock.edu_message=(b,g)=>call(`broadcast(${g.valueToCode(b,'TEXT',g.ORDER_NONE)||'""'})`);g.forBlock.edu_clone=()=>call('clone()');g.forBlock.edu_clear=()=>call('clear()');g.forBlock.edu_key=b=>[`key(${JSON.stringify(b.getFieldValue('KEY'))})`,g.ORDER_FUNCTION_CALL];g.forBlock.edu_received=(b,g)=>{let message=JSON.stringify(b.getFieldValue('MESSAGE')),body=g.statementToCode(b,'DO');if(py)return `# Poruka ${message}: handler dostupan u ELDI pozornici\n`;g.definitions_['message_'+b.id]=`on(${message}, function() {\n${body}});\n`;return ''}}
const toolbox={kind:'categoryToolbox',contents:[{kind:'category',name:'Kretanje i izgled',colour:210,contents:[{kind:'block',type:'edu_move',inputs:{N:number(40)}},{kind:'block',type:'edu_turn',inputs:{N:number(90)}},{kind:'block',type:'edu_goto',inputs:{X:number(0),Y:number(0)}},{kind:'block',type:'edu_say',inputs:{TEXT:text('Zdravo!')}},{kind:'block',type:'edu_sprite'},{kind:'block',type:'edu_pen'},{kind:'block',type:'edu_clear'}]},{kind:'category',name:'Kontrola i događaji',colour:45,contents:[{kind:'block',type:'controls_repeat_ext',inputs:{TIMES:number(4)}},{kind:'block',type:'controls_if'},{kind:'block',type:'controls_whileUntil'},{kind:'block',type:'controls_for'},{kind:'block',type:'controls_forEach'},{kind:'block',type:'controls_flow_statements'},{kind:'block',type:'edu_wait',inputs:{N:number(1)}},{kind:'block',type:'edu_message',inputs:{TEXT:text('start')}},{kind:'block',type:'edu_received'},{kind:'block',type:'edu_clone'},{kind:'block',type:'edu_key'}]},{kind:'category',name:'Logika',colour:210,contents:['logic_compare','logic_operation','logic_negate','logic_boolean'].map(type=>({kind:'block',type}))},{kind:'category',name:'Matematika',colour:230,contents:['math_number','math_arithmetic','math_single','math_number_property','math_round','math_modulo','math_random_int'].map(type=>({kind:'block',type}))},{kind:'category',name:'Tekst',colour:160,contents:['text','text_join','text_length','text_isEmpty','text_indexOf','text_charAt','text_changeCase'].map(type=>({kind:'block',type}))},{kind:'category',name:'Liste',colour:260,contents:['lists_create_with','lists_repeat','lists_length','lists_isEmpty','lists_indexOf','lists_getIndex','lists_setIndex','lists_getSublist','lists_sort'].map(type=>({kind:'block',type}))},{kind:'category',name:'Varijable',custom:'VARIABLE',colour:330},{kind:'category',name:'Postupci',custom:'PROCEDURE',colour:290}]};
const keydown=e=>keys.add(e.key),keyup=e=>keys.delete(e.key);function reset(){sprites=[{x:0,y:0,angle:0,color:'#8870c5',pen:true},{x:-120,y:0,angle:0,color:'#829e3e',pen:true},{x:120,y:0,angle:0,color:'#de8b5d',pen:true}];current=0;draw(true)}
function draw(clearFirst=false){const c=document.getElementById('stage');if(!c)return;const ctx=c.getContext('2d');if(clearFirst){ctx.fillStyle='#fffef9';ctx.fillRect(0,0,480,360);ctx.strokeStyle='#e5e8dd';ctx.beginPath();for(let x=0;x<480;x+=20){ctx.moveTo(x,0);ctx.lineTo(x,360)}for(let y=0;y<360;y+=20){ctx.moveTo(0,y);ctx.lineTo(480,y)}ctx.stroke()} // sprites overlay is drawn on a fresh snapshot below
}
let trail=[];function stage(){draw(true);const ctx=document.getElementById('stage')?.getContext('2d');if(!ctx)return;for(const t of trail){ctx.strokeStyle=t.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(240+t.x1,180-t.y1);ctx.lineTo(240+t.x2,180-t.y2);ctx.stroke()}sprites.forEach((s,i)=>{ctx.save();ctx.translate(240+s.x,180-s.y);ctx.rotate(s.angle*Math.PI/180);ctx.fillStyle=s.color;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-8);ctx.lineTo(-8,8);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle=s.color;ctx.font='12px system-ui';ctx.fillText(String(i+1),250+s.x,170-s.y)})}
function apply(a){let s=sprites[current];if(a.type==='sprite'){current=Math.max(0,Math.min(sprites.length-1,Math.trunc(a.value)));return}if(a.type==='move'||a.type==='go'){let old={x:s.x,y:s.y};if(a.type==='move'){s.x+=Math.cos(s.angle*Math.PI/180)*a.value;s.y-=Math.sin(s.angle*Math.PI/180)*a.value}else{s.x=a.x;s.y=a.y}if(s.pen){trail.push({x1:old.x,y1:old.y,x2:s.x,y2:s.y,color:s.color});if(trail.length>10000)trail.shift()}}if(a.type==='turn')s.angle+=a.value;if(a.type==='pen')s.pen=!!a.value;if(a.type==='say'){const o=document.getElementById('blockout');if(o)o.textContent=(o.textContent+'\n'+a.value).slice(-50000)}if(a.type==='clone'&&sprites.length<30)sprites.push({...s,x:s.x+10,y:s.y+10});if(a.type==='clear')trail=[];stage()}
function animate(){if(!actionQueue.length){animTimer=null;return}let a=actionQueue.shift();if(a.type==='wait'){animTimer=setTimeout(animate,Math.max(0,Math.min(3000,a.value*1000)));return}apply(a);animTimer=setTimeout(animate,20)}
function code(lang='js'){let g=lang==='py'?PY:JS,raw=g.workspaceToCode(workspace);if(lang!=='py')return raw;return `import turtle\nimport time\nt=turtle.Turtle()\ndef move(n): t.forward(n)\ndef turn(n): t.right(n)\ndef go(x,y): t.goto(x,y)\ndef say(text): print(text)\ndef pen(down):\n    t.pendown() if down else t.penup()\ndef wait(n): time.sleep(max(0,n))\ndef sprite(n): pass\ndef broadcast(message): pass\ndef clone(): pass\ndef clear(): t.clear()\ndef key(name): return False\n\n`+raw+'\nturtle.done()\n'}
function update(){if(!workspace)return;try{document.getElementById('blockcode').textContent=code(document.getElementById('blocklang')?.value||'js');onSave(serialize())}catch(e){document.getElementById('blockcode').textContent=e.message}}
function serialize(){return {format:'ELDI-BLOCKS-1',workspace:Blockly.serialization.workspaces.save(workspace)}}
function load(data){if(data?.format!=='ELDI-BLOCKS-1'||!data.workspace)throw Error('Nepoznat format blokovskog projekta.');Blockly.serialization.workspaces.load(data.workspace,workspace);update()}
function stop(){worker?.terminate();worker=null;clearTimeout(runningTimer);clearTimeout(animTimer);animTimer=null;actionQueue=[]}
function run(){stop();reset();trail=[];stage();document.getElementById('blockout').textContent='Izvršavanje…';try{worker=new Worker('block-worker.js');worker.onmessage=e=>{if(e.data.type==='actions'){actionQueue.push(...e.data.actions);if(!animTimer)animate()}if(e.data.type==='done'){clearTimeout(runningTimer);document.getElementById('blockout').textContent+='\nProgram sastavljen. Naredbe se prikazuju na pozornici.';worker?.terminate();worker=null}if(e.data.type==='error'){document.getElementById('blockout').textContent=e.data.message;stop()}};worker.onerror=e=>{document.getElementById('blockout').textContent='Greška: '+e.message;stop()};worker.postMessage({code:code('js'),keys:[...keys],sprite:+document.getElementById('sprite').value});runningTimer=setTimeout(()=>{stop();document.getElementById('blockout').textContent='Program je zaustavljen: prekoračeno 5 sekundi računanja.'},5000)}catch(e){document.getElementById('blockout').textContent=e.message}}
function example(type){workspace.clear();let data=type==='square'?{blocks:{languageVersion:0,blocks:[{type:'controls_repeat_ext',inputs:{TIMES:number(4),DO:{block:{type:'edu_move',inputs:{N:number(80)},next:{block:{type:'edu_turn',inputs:{N:number(90)}}}}}}}]}}:{blocks:{languageVersion:0,blocks:[{type:'edu_say',inputs:{TEXT:text('Brojimo tri puta')},next:{block:{type:'controls_repeat_ext',inputs:{TIMES:number(3),DO:{block:{type:'edu_say',inputs:{TEXT:text('Učim!')}}}}}}}]}};Blockly.serialization.workspaces.load(data,workspace);update()}
return {init(opts){document.addEventListener('keydown',keydown);document.addEventListener('keyup',keyup);onSave=opts.onSave;workspace=Blockly.inject('blocklyDiv',{toolbox,media:'vendor/media/',trashcan:true,scrollbars:true,zoom:{controls:true,wheel:true,startScale:.8},grid:{spacing:20,length:2,colour:'#d9e3cf',snap:true}});workspace.addChangeListener(update);reset();stage();if(opts.initial)try{load(opts.initial)}catch{}update()},destroy(){document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',keyup);keys.clear();stop();workspace?.dispose();workspace=null},run,stop,example,serialize,load,update,code,clear(){workspace.clear();update()},select(i){current=i;stage()}}})();
