'use strict';
window.ELDICourses=(()=>{
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const $=id=>document.getElementById(id);
 let context,selection={subject:'math',grade:5,category:'all',search:'',offset:0};
 const all=()=>[...(window.ELDI_MATH_CATALOG||[]),...(window.ELDI_INFORMATICS_CATALOG||[])];
 function mount(options){context=options;catalog();}
 function catalog(){
  context.root.innerHTML=`<div class="eyebrow">AKADEMIJA / 5–9. RAZRED</div><h1>Hiljadu puteva do znanja.</h1><p>500 matematičkih i 500 informatičkih tematskih cjelina i vještina. Svaka ima objašnjenje, primjer i praktični zadatak. Prati svoj napredak od početnog koraka do završne provjere.</p><div class="course-catalog card"><div class="controls"><label>Predmet<select id="course-subject"><option value="math">Matematika · 500</option><option value="informatics">Informatika · 500</option></select></label><label>Razred<select id="course-grade">${[5,6,7,8,9].map(g=>`<option value="${g}">${g}. razred · 100 cjelina</option>`).join('')}</select></label><label>Područje<select id="course-category"></select></label><label>Pretraži<input type="search" id="course-search" placeholder="Razlomci, Scratch, Python…" value="${esc(selection.search)}"></label><button id="course-exam" class="primary">Završna provjera →</button></div><p id="course-count" role="status"></p></div><div id="course-cards" class="lessongrid"></div><div id="course-pages" class="row" style="margin-top:24px"></div>`;
  $('course-subject').value=selection.subject;$('course-grade').value=selection.grade;
  const reset=()=>{selection.subject=$('course-subject').value;selection.grade=+$('course-grade').value;selection.category='all';selection.offset=0;categories();list();};$('course-subject').onchange=reset;$('course-grade').onchange=reset;$('course-category').onchange=()=>{selection.category=$('course-category').value;selection.offset=0;list();};$('course-search').oninput=()=>{selection.search=$('course-search').value;selection.offset=0;list();};$('course-exam').onclick=()=>context.go('exams');categories();list();
 }
 function categories(){const values=[...new Set(all().filter(l=>l.subject===selection.subject&&l.grade===selection.grade).map(l=>l.category))];$('course-category').innerHTML='<option value="all">Sva područja</option>'+values.map(c=>`<option>${esc(c)}</option>`).join('');$('course-category').value=selection.category;}
 function list(){
  const term=selection.search.toLocaleLowerCase('bs'),profile=context.profile(),results=profile.courseResults||{};
  const filtered=all().filter(l=>l.subject===selection.subject&&l.grade===selection.grade&&(selection.category==='all'||l.category===selection.category)&&(l.title+' '+l.description+' '+l.category).toLocaleLowerCase('bs').includes(term));
  $('course-count').textContent=`${filtered.length} cjelina u ovom izboru · prikaz ${Math.min(selection.offset+1,filtered.length)}–${Math.min(selection.offset+24,filtered.length)}. Broj cjelina označava zasebne vještine, a broj varijanti označava generisane zadatke.`;
  $('course-cards').innerHTML=filtered.slice(selection.offset,selection.offset+24).map((l,i)=>`<article class="card course-card"><div class="row between"><span class="course-number">${String(selection.offset+i+1).padStart(3,'0')}</span><span class="tag">${esc(l.category)}</span></div><h3>${esc(l.title)}</h3><p>${esc(l.description)}</p><div class="row between"><span class="tag">${results[l.id]?.correct?'✓ Praktični rad riješen':'Objašnjenje + praktični rad'}</span><button data-course-id="${esc(l.id)}">Uči i vježbaj →</button></div></article>`).join('')||'<p>Nema cjelina za ovu pretragu.</p>';
  document.querySelectorAll('[data-course-id]').forEach(b=>b.onclick=()=>open(b.dataset.courseId));$('course-pages').innerHTML=`<button id="course-prev" ${selection.offset===0?'disabled':''}>← Prethodne</button><span>Stranica ${Math.floor(selection.offset/24)+1} od ${Math.max(1,Math.ceil(filtered.length/24))}</span><button id="course-next" ${selection.offset+24>=filtered.length?'disabled':''}>Sljedeće →</button>`;$('course-prev').onclick=()=>{selection.offset=Math.max(0,selection.offset-24);list();};$('course-next').onclick=()=>{selection.offset+=24;list();};
 }
 function open(id){
  const lesson=all().find(l=>l.id===id);if(!lesson)return;const p=context.profile();p.courseAnswers||={};p.courseNotes||={};p.courseResults||={};
  const task=lesson.subject==='math'?window.EduPractice.generate(lesson.id,1,'medium'):{...lesson.activity,id:'activity-'+lesson.id,title:lesson.title,grade:lesson.grade};
  context.root.innerHTML=`<div class="lessontext"><div class="row"><button id="course-back">← Katalog</button><span class="tag">${lesson.grade}. razred / ${lesson.subject==='math'?'Matematika':'Informatika'} / ${esc(lesson.category)}</span></div><h1>${esc(lesson.title)}</h1><p class="notice">${esc(lesson.description)}</p>${lesson.body.map((paragraph,i)=>`<div class="lesson-paragraph"><span class="tag">${['Razumij','Primijeni','Provjeri','Poveži','Istraži'][i]||'Dodatno'}</span><p>${esc(paragraph)}</p></div>`).join('')}<h2>Razrađen primjer</h2><pre class="result">${esc(lesson.example)}</pre><article class="card solving-task"><h2>Uradi samostalno</h2><p class="task-prompt">${esc(task.prompt)}</p><div class="task-fields">${task.fields.map((f,j)=>`<label>${esc(f.label)}${f.preserveWhitespace?`<textarea class="compact" id="course-answer-${j}" data-course-key="${esc(f.key)}" placeholder="Tačan izlaz: sačuvaj velika/mala slova i razmake">${esc(p.courseAnswers[lesson.id]?.[f.key]||'')}</textarea>`:`<input id="course-answer-${j}" data-course-key="${esc(f.key)}" value="${esc(p.courseAnswers[lesson.id]?.[f.key]||'')}" autocomplete="off" placeholder="${f.caseSensitive?'Tačan zapis, velika/mala slova':f.type==='list'?'Brojevi odvojeni ; ili razmakom':'Upiši odgovor'}">`}<span id="course-feedback-${j}" class="field-feedback" role="status"></span></label>`).join('')}</div><label>Moj postupak / bilješke<textarea id="course-notes" class="working-notes">${esc(p.courseNotes[lesson.id]||'')}</textarea></label><div class="row"><button id="course-check" class="primary">Provjeri praktični rad</button><button id="course-hint">Pomoć</button><button id="course-solution">Postupak i rješenje</button>${lesson.subject==='math'?'<button id="course-more">Još zadataka ove vještine</button>':''}${lesson.blockChallengeId?'<button id="course-blocks">Otvori povezani blokovski izazov</button>':''}</div><p id="course-result" role="status"></p><div id="course-worked" hidden class="worked-solution"><ol>${task.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${task.fields.map(f=>`<p>${esc(f.label)}: <strong>${esc(Array.isArray(f.answer)?f.answer.join('; '):f.answer)}</strong></p>`).join('')}</div></article><div class="row"><button id="course-exam-next">Završna provjera i diploma →</button></div></div>`;
  $('course-back').onclick=catalog;document.querySelectorAll('[data-course-key]').forEach(input=>input.oninput=()=>{p.courseAnswers[lesson.id]||={};p.courseAnswers[lesson.id][input.dataset.courseKey]=input.value.slice(0,2048);context.save();});$('course-notes').oninput=()=>{p.courseNotes[lesson.id]=$('course-notes').value.slice(0,6000);context.save();};
  $('course-check').onclick=()=>{const result=window.ELDIExamEngine.checkTask(task,p.courseAnswers[lesson.id]||{}),old=p.courseResults[lesson.id]||{};result.fields.forEach((r,j)=>{$('course-feedback-'+j).textContent=(r.correct?'✓ ':'✗ ')+r.message;});p.courseResults[lesson.id]={...old,correct:!!(old.correct||result.correct),attempts:(old.attempts||0)+1,title:lesson.title,grade:lesson.grade,date:new Date().toISOString()};if(lesson.subject==='informatics'){p.infoWork||={results:{}};p.infoWork.results||={};p.infoWork.results[task.id]=p.courseResults[lesson.id];}else{p.mathWork||={answers:{},notes:{},results:{},session:[],sheets:[]};p.mathWork.results||={};p.mathWork.results[task.id]=p.courseResults[lesson.id];}context.save();$('course-result').textContent=result.correct?'✓ Praktični zadatak je riješen.':'Provjeri označene odgovore i pokušaj ponovo.';};
  $('course-hint').onclick=()=>{$('course-result').textContent=task.hint||lesson.hint||'Pogledaj razrađen primjer iznad zadatka.';};$('course-solution').onclick=()=>{if(!p.courseResults[lesson.id]?.correct){p.courseResults[lesson.id]||={correct:false,attempts:0};p.courseResults[lesson.id].assisted=true;context.save();}$('course-worked').hidden=false;};
  if($('course-more'))$('course-more').onclick=()=>{context.go('collection');window.ELDICollection.startTopic(lesson.id,1);};if($('course-blocks'))$('course-blocks').onclick=()=>{p.blockChallengeId=lesson.blockChallengeId;context.save();context.go('blocks');};$('course-exam-next').onclick=()=>context.go('exams');window.scrollTo(0,0);
 }
 return{mount,catalog,open};
})();
