'use strict';
window.ELDIExams=(()=>{
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const $=id=>document.getElementById(id);let context;
 const profile=()=>context.profile();const E=()=>window.ELDIExamEngine;
 function mount(options){context=options;setup();}
 function setup(){
  const p=profile();
  context.root.innerHTML=`<div class="eyebrow">PROVJERE / OCJENE / POSTIGNUĆA</div><h1>Pokreni svoju provjeru.</h1><p>Odaberi predmet, razred i broj zadataka. Svaki potpuno riješen zadatak nosi jedan bod. Rezultat i ocjena ostaju u tvom profilu.</p><div class="exam-shell"><div class="card exam-controls"><div class="controls"><label>Predmet<select id="exam-subject"><option value="math">Matematika</option><option value="informatics">Informatika</option><option value="mixed">Matematika + informatika</option></select></label><label>Razred<select id="exam-grade">${[5,6,7,8,9].map(g=>`<option>${g}</option>`).join('')}</select></label><label>Oblast<select id="exam-category"></select></label><label>Broj zadataka<select id="exam-count">${E().counts.map(n=>`<option ${n===10?'selected':''}>${n}</option>`).join('')}<option value="custom">Drugi broj…</option></select></label><label id="exam-custom-label" hidden>Od 1 do 50<input id="exam-custom" type="number" min="1" max="50" value="12"></label><label>Nivo matematike<select id="exam-level"><option value="easy">Osnovni</option><option value="medium" selected>Srednji</option><option value="hard">Napredni</option></select></label><label>Broj provjere<input id="exam-seed" type="number" min="1" max="9999" value="1"></label></div><details><summary>Skala ocjenjivanja — prilagodi pragove</summary><p>Unesite najmanji procenat za ocjene 2, 3, 4 i 5. Pragovi moraju rasti. Ova skala pripada provjeri u aplikaciji.</p><div class="row">${[2,3,4,5].map((g,i)=>`<label>Ocjena ${g} od (%)<input id="exam-threshold-${g}" type="number" min="1" max="100" value="${[50,65,80,90][i]}"></label>`).join('')}</div></details><div class="row" style="margin-top:24px"><button id="exam-start" class="primary">▶ Pokreni provjeru</button>${p.examSession&&!p.examSession.completed?'<button id="exam-resume">Nastavi otvorenu provjeru</button>':''}</div><p id="exam-setup-error" class="error" role="status"></p></div><div class="card"><h2>Od rada do diplome</h2><ol><li>Samostalno unesi odgovore i zapiši postupak.</li><li>Kad završiš, predaj provjeru za ocjenu.</li><li>Pregledaj bodove i razrađena rješenja.</li><li>Preuzmi ili odštampaj diplomu s rezultatom, imenima autora i pečatom aplikacije.</li></ol><p>Za prolaznu ocjenu izdaje se diploma, a za ostale rezultate potvrda učešća. Značke se osvajaju stvarnim radom u aplikaciji.</p></div></div><h2>Prethodne provjere</h2><div class="grid">${(p.exams||[]).slice().reverse().slice(0,20).map(exam=>`<div class="card"><span class="tag">${exam.gradeLevel}. razred · ${exam.total} zadataka</span><h3>${subjectName(exam.subject)}</h3><p>${exam.correct}/${exam.total} · ${exam.percentage.toFixed(1)}% · ocjena ${exam.gradeResult.grade}</p><button data-exam-history="${esc(exam.id)}">Pregledaj rezultat</button></div>`).join('')||'<p>Još nema završenih provjera.</p>'}</div>`;
  const fill=()=>{$('exam-category').innerHTML='<option value="all">Sve oblasti</option>'+E().categories($('exam-subject').value,+$('exam-grade').value).map(c=>`<option>${esc(c)}</option>`).join('');};$('exam-subject').onchange=fill;$('exam-grade').onchange=fill;fill();
  $('exam-count').onchange=()=>{$('exam-custom-label').hidden=$('exam-count').value!=='custom';};
  $('exam-start').onclick=()=>{try{const session=E().createSession({subject:$('exam-subject').value,gradeLevel:+$('exam-grade').value,count:+($('exam-count').value==='custom'?$('exam-custom').value:$('exam-count').value),seed:+$('exam-seed').value,difficulty:$('exam-level').value,category:$('exam-category').value,profileName:p.name,thresholds:[2,3,4,5].map(g=>+$('exam-threshold-'+g).value)});p.examSession=session;context.save();renderSession();}catch(error){$('exam-setup-error').textContent=error.message;}};
  if($('exam-resume'))$('exam-resume').onclick=renderSession;
  document.querySelectorAll('[data-exam-history]').forEach(b=>b.onclick=()=>renderResult(p.exams.find(e=>e.id===b.dataset.examHistory)));
 }
 const subjectName=subject=>({math:'Matematika',informatics:'Informatika',mixed:'Matematika i informatika'}[subject]||subject);
 function renderSession(){
  const session=profile().examSession;if(!session||session.completed){setup();return;}const tasks=session.refs.map(E().resolve);
  context.root.innerHTML=`<div class="row between exam-controls"><button id="exam-back">← Postavke provjere</button><span>${tasks.length} zadataka · ${session.gradeLevel}. razred · ${subjectName(session.subject)}</span><button id="exam-finish" class="primary">Završi i ocijeni</button></div><div class="eyebrow">SAMOSTALNA PROVJERA / ${esc(profile().name)}</div><h1>${subjectName(session.subject)}</h1><p>Odgovori se automatski čuvaju. Rješenja i pomoć otvaraju se nakon predaje. Svaki zadatak je jedan bod, bez obzira na broj dijelova.</p><p id="exam-live-count" role="status"></p>${tasks.map((task,i)=>`<article class="card exam-question"><span class="tag">${i+1}/${tasks.length} · ${esc(task.title)}</span><p class="task-prompt">${esc(task.prompt)}</p><div class="task-fields">${task.fields.map((field,j)=>`<label>${esc(field.label)}${field.preserveWhitespace?`<textarea class="compact" id="exam-${i}-field-${j}" data-exam-index="${i}" data-exam-key="${esc(field.key)}" spellcheck="false" placeholder="Tačan izlaz: sačuvaj velika/mala slova i razmake">${esc(session.answers[i]?.[field.key]||'')}</textarea>`:`<input id="exam-${i}-field-${j}" data-exam-index="${i}" data-exam-key="${esc(field.key)}" value="${esc(session.answers[i]?.[field.key]||'')}" autocomplete="off" spellcheck="false" placeholder="${field.caseSensitive?'Tačan zapis, velika/mala slova':field.type==='list'?'Brojevi odvojeni ; ili razmakom':'Upiši odgovor'}">`}</label>`).join('')}</div><label>Moj postupak<textarea class="working-notes" data-exam-notes="${i}" placeholder="Zapiši kako si došao do rezultata…">${esc(session.notes[i]||'')}</textarea></label></article>`).join('')}<div class="row exam-controls"><button id="exam-finish-bottom" class="primary">Predaj provjeru i prikaži ocjenu</button></div>`;
  $('exam-back').onclick=setup;const update=()=>{$('exam-live-count').textContent=`Popunjeno ${tasks.filter((t,i)=>t.fields.every(f=>String(session.answers[i]?.[f.key]||'').trim())).length}/${tasks.length} zadataka.`;};
  document.querySelectorAll('[data-exam-key]').forEach(input=>input.oninput=()=>{session.answers[input.dataset.examIndex]||={};session.answers[input.dataset.examIndex][input.dataset.examKey]=input.value.slice(0,2048);context.save();update();});document.querySelectorAll('[data-exam-notes]').forEach(input=>input.oninput=()=>{session.notes[input.dataset.examNotes]=input.value.slice(0,6000);context.save();});
  $('exam-finish').onclick=finish;$('exam-finish-bottom').onclick=finish;update();
 }
 function finish(){
  const p=profile(),session=p.examSession;if(!session||session.completed)return;
  const result=E().finish(session);p.exams||=[];p.exams.push(result);p.exams=p.exams.slice(-100);p.examSession=null;
  // Completed mathematics also contributes to the learning progress record.
  p.mathWork||={answers:{},notes:{},results:{},session:[],sheets:[]};p.mathWork.results||={};p.courseResults||={};p.infoWork||={results:{}};p.infoWork.results||={};
  result.details.forEach((detail,i)=>{const ref=result.refs[i],target=ref.kind==='math'?p.mathWork.results:p.infoWork.results,old=target[detail.taskId]||{};target[detail.taskId]={...old,correct:!!(old.correct||detail.correct),lastCorrect:detail.correct,attempts:(old.attempts||0)+1,grade:result.gradeLevel,title:detail.title,date:result.finishedAt};});
  window.ELDIAwards.recordExamCertificate(p,result);context.save();renderResult(result);
 }
 function renderResult(result){
  const tasks=result.refs.map(E().resolve),record=(profile().certificates||[]).find(c=>c.examId===result.id);
  context.root.innerHTML=`<div class="result-panel card"><div><div class="eyebrow">PROVJERA JE ZAVRŠENA</div><h1>${subjectName(result.subject)}</h1><p>${result.gradeLevel}. razred · ${result.total} zadataka · ${new Date(result.finishedAt).toLocaleDateString('bs-BA')}</p><div class="row"><button id="exam-new" class="primary">Nova provjera</button><button id="exam-certificate">${result.gradeResult.passed?'Prikaži diplomu':'Prikaži potvrdu'}</button><button id="exam-print-result">Štampaj rezultat</button></div></div><div class="score-orbit"><strong>${result.gradeResult.grade}</strong><span>${esc(result.gradeResult.label)}</span><span>${result.correct}/${result.total} · ${result.percentage.toFixed(1)}%</span></div></div><div class="notice">Skala ove provjere: ocjena 2 od ${result.thresholds[0]}%, 3 od ${result.thresholds[1]}%, 4 od ${result.thresholds[2]}%, 5 od ${result.thresholds[3]}%. Rezultat je evidencija u aplikaciji.</div><h2>Pregled zadataka i postupaka</h2>${tasks.map((task,i)=>`<article class="card exam-question"><span class="tag">${i+1}. ${result.details[i].correct?'✓ 1 bod':'0 bodova'} · ${esc(task.title)}</span><p class="task-prompt">${esc(task.prompt)}</p>${task.fields.map((f,j)=>`<p><strong>${esc(f.label)}</strong><br>Tvoj odgovor: ${esc(result.answers[i]?.[f.key]||'—')}<br>Tačno: ${esc(Array.isArray(f.answer)?f.answer.join('; '):f.answer)} · ${result.details[i].fields[j].correct?'✓':'✗'}</p>`).join('')}<details><summary>Postupak rješavanja</summary><ol>${task.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${result.notes[i]?`<h3>Tvoj zapis</h3><pre class="result">${esc(result.notes[i])}</pre>`:''}</details></article>`).join('')}`;
  $('exam-new').onclick=setup;$('exam-certificate').onclick=()=>{if(record)context.showCertificate(record);};$('exam-print-result').onclick=async()=>{document.body.classList.add('printing-exam');try{await context.print();}finally{document.body.classList.remove('printing-exam');}};
 }
 return{mount,setup,renderSession,renderResult,finish,subjectName};
})();
