'use strict';
window.ELDILearningPaths=(()=>{
  const E=()=>window.ELDILearningPlan,esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let context,generation=0,tab='learn',selectedUnit='',search='',activeLesson=null,assistantRequest=null;
  const el=id=>context.root.querySelector('#'+id),on=(id,event,fn)=>{const item=el(id);if(item)item[event]=fn;},profile=()=>context.profile(),work=()=>E().ensure(profile());
  const subjectName=s=>s==='math'?'Matematika':'Informatika';
  function mount(options){activeLesson=null;assistantRequest=null;context=options;generation++;E().ensure(profile());dashboard();}
  function header(){const w=work();return `<div class="lp-shell"><div class="lp-heading"><div><div class="eyebrow">AKADEMIJA / TVOJ REDOSLIJED UČENJA</div><h1>Znanje, korak po korak.</h1><p>Objašnjenje, primjer, samostalan rad, provjera i preporuka za ponavljanje.</p></div><div class="lp-orbit" aria-hidden="true"><span>01</span><strong>UČI<br>PRIMIJENI</strong><span>05</span></div></div><div class="lp-tabs" role="group" aria-label="Prikaz akademije"><button id="lp-learn" ${tab==='learn'?'class="primary"':''}>◈ Put učenja</button><button id="lp-mapping" ${tab==='mapping'?'class="primary"':''}>▤ Mapa kurikuluma</button></div><div class="lp-filter card"><label>Predmet<select id="lp-subject"><option value="math">Matematika</option><option value="informatics">Informatika</option></select></label><label>Razred<select id="lp-grade">${[5,6,7,8,9].map(g=>`<option value="${g}">${g}. razred</option>`).join('')}</select></label>${tab==='learn'?`<label>Dnevni plan<select id="lp-daily-count">${[1,2,3,4,5].map(n=>`<option value="${n}">${n} ${n===1?'vještina':'vještine'}</option>`).join('')}</select></label>`:''}<label class="lp-search">Pretraži<input id="lp-search" type="search" placeholder="Cjelina, vještina ili ishod…" value="${esc(search)}"></label></div><div id="lp-content"></div></div>`;}
  function dashboard(){activeLesson=null;assistantRequest=null;generation++;context.root.innerHTML=header();const w=work();el('lp-subject').value=w.subject;el('lp-grade').value=w.grade;if(el('lp-daily-count'))el('lp-daily-count').value=w.dailyCount;
    on('lp-learn','onclick',()=>{tab='learn';dashboard();});on('lp-mapping','onclick',()=>{tab='mapping';dashboard();});
    const filter=()=>{w.subject=el('lp-subject').value;w.grade=+el('lp-grade').value;selectedUnit='';context.save();render();};on('lp-subject','onchange',filter);on('lp-grade','onchange',filter);on('lp-daily-count','onchange',()=>{w.dailyCount=+el('lp-daily-count').value;context.save();render();});on('lp-search','oninput',()=>{search=el('lp-search').value.slice(0,200);render();});render();
  }
  function render(){if(tab==='mapping')renderMapping();else renderLearning();}
  function matchingUnits(){const w=work(),term=search.toLocaleLowerCase('bs');return E().units.filter(u=>u.subject===w.subject&&u.grade===w.grade&&(!term||(u.title+' '+u.lessonIds.map(id=>E().getLesson(id).title).join(' ')).toLocaleLowerCase('bs').includes(term)));}
  function renderLearning(){
    const p=profile(),w=work(),cov=E().coverage(p,{subject:w.subject,grade:w.grade}),daily=E().dailyPlan(p),list=matchingUnits();
    el('lp-content').innerHTML=`<div class="lp-summary"><div><strong>${cov.independentSkills}<small>/ ${cov.skills}</small></strong><span>samostalno riješenih vještina</span></div><div><strong>${E().units.filter(u=>u.subject===w.subject&&u.grade===w.grade).length}</strong><span>uređenih cjelina</span></div><div><strong>5</strong><span>koraka u svakoj lekciji</span></div></div><section class="lp-daily"><div class="row between"><div><span class="eyebrow">PREPORUKA IZ TVOJIH REZULTATA</span><h2>Današnji mali napredak</h2></div>${w.lastLessonId?'<button id="lp-resume">Nastavi posljednju lekciju →</button>':''}</div><div class="lp-daily-grid">${daily.map((item,index)=>`<article class="card lp-daily-card"><span class="lp-index">${String(index+1).padStart(2,'0')}</span><span class="tag">${item.grade}. razred · ${subjectName(item.subject)}</span><h3>${esc(item.title)}</h3><p>${esc(item.reason)}</p><button class="primary" data-lp-open="${esc(item.lessonId)}">Kreni →</button></article>`).join('')}</div><p class="lp-note">Preporuka koristi tvoje zabilježene pokušaje. Preduslovi su pomoć pri izboru redoslijeda; svaku lekciju možeš otvoriti odmah.</p></section><div class="row between"><h2>${selectedUnit?'Vještine odabrane cjeline':'Cjeline za '+w.grade+'. razred'}</h2>${selectedUnit?'<button id="lp-all-units">← Sve cjeline</button>':''}</div><div id="lp-unit-content"></div>`;
    on('lp-resume','onclick',()=>open(w.lastLessonId));on('lp-all-units','onclick',()=>{selectedUnit='';renderLearning();});
    const unit=E().getUnit(selectedUnit);if(unit&&unit.subject===w.subject&&unit.grade===w.grade)renderUnit(unit);else el('lp-unit-content').innerHTML=`<div class="lp-unit-grid">${list.map(u=>{const result=E().unitProgress(p,u),prereqs=u.prerequisites.map(id=>E().getUnit(id).title);return `<article class="card lp-unit-card"><div class="row between"><span class="lp-index">${String(u.order).padStart(2,'0')}</span><span class="tag">${result.independent}/${result.total} samostalno</span></div><h3>${esc(u.title)}</h3><div class="progressbar"><span style="width:${result.independent/result.total*100}%"></span></div><p>${result.failed?`${result.failed} vještina za ponavljanje. `:''}${prereqs.length?'Priprema: '+esc(prereqs.join(' · ')):'Početna cjelina ovog puta.'}</p><button data-lp-unit="${esc(u.id)}">Otvori ${result.total} vještina →</button></article>`;}).join('')||'<p>Nema cjelina za ovu pretragu.</p>'}</div>`;
    context.root.querySelectorAll('[data-lp-open]').forEach(button=>button.onclick=()=>open(button.dataset.lpOpen));context.root.querySelectorAll('[data-lp-unit]').forEach(button=>button.onclick=()=>{selectedUnit=button.dataset.lpUnit;renderLearning();});
  }
  function renderUnit(unit){const p=profile(),term=search.toLocaleLowerCase('bs'),list=unit.lessonIds.map(id=>E().getLesson(id)).filter(l=>!term||(unit.title+' '+l.title).toLocaleLowerCase('bs').includes(term));el('lp-unit-content').innerHTML=`<div class="card lp-unit-lessons"><h3>${esc(unit.title)}</h3>${list.map(l=>{const result=E().progress(p,l.id);return `<div class="lp-lesson-row"><div><strong>${esc(l.title)}</strong><p>${esc(l.description)}</p></div><span class="tag">${result.independent?'✓ Samostalno':result.correct?'✓ Uz pomoć':result.failed?'Ponovi':'Novi korak'}</span><button data-lp-open="${esc(l.id)}">Uči →</button></div>`;}).join('')}</div>`;}
  function open(id,stage=0){
    generation++;const lesson=E().getLesson(id);if(!lesson)return;const p=profile(),w=work(),row=E().lessonWork(p,id),task=E().resolveTask(id,row.variant,row.difficulty);activeLesson={lesson,p,row,task,stage};assistantRequest=null;w.lastLessonId=id;context.save();
    const prerequisites=E().prerequisites(p,id),steps=['Razumij','Pogledaj primjer','Uradi sam','Provjeri','Šta dalje'];
    context.root.innerHTML=`<div class="lp-shell lp-lesson"><div class="row between"><button id="lp-back">← Put učenja</button><span class="tag">${lesson.grade}. razred · ${subjectName(lesson.subject)} · ${esc(lesson.category)}</span></div><h1>${esc(lesson.title)}</h1><p class="lp-description">${esc(lesson.description)}</p><ol class="lp-stepbar">${steps.map((title,index)=>`<li class="${stage===index?'active ':''}${index===0&&row.theoryRead||index===1&&row.exampleRead||index===3&&row.lastCorrect?'done':''}"><button data-lp-stage="${index}" ${(index===3||index===4)&&(!row.currentAttempts||row.dirty)?'disabled':''}><span>${index+1}</span>${title}</button></li>`).join('')}</ol><div id="lp-lesson-stage"></div><details class="lp-prerequisites"><summary>Preporučena priprema (${prerequisites.length} ${prerequisites.length===1?'cjelina':'cjeline'})</summary>${prerequisites.length?prerequisites.map(u=>`<div class="row between"><span>${u.grade}. razred · ${esc(u.title)} · ${u.independent}/${u.total} samostalno</span><button data-lp-prereq="${esc(u.lessonIds.find(id=>!E().progress(p,id).independent)||u.lessonIds[0])}">Ponovi cjelinu →</button></div>`).join(''):'<p>Ovo je početna cjelina uredničkog plana.</p>'}</details><p class="lp-note">Vještine i zadaci su iz postojeće zbirke ELDI EDU. Predloženi redoslijed je urednički plan.</p></div>`;
    on('lp-back','onclick',dashboard);context.root.querySelectorAll('[data-lp-stage]').forEach(button=>button.onclick=()=>open(id,+button.dataset.lpStage));context.root.querySelectorAll('[data-lp-prereq]').forEach(button=>button.onclick=()=>open(button.dataset.lpPrereq));
    const host=el('lp-lesson-stage');
    if(stage===0){host.innerHTML=`<section class="card lp-reading"><span class="eyebrow">KORAK 1 / RAZUMIJ</span><h2>Objašnjenje</h2>${lesson.body.map((paragraph,index)=>`<div class="lp-paragraph"><span>${index+1}</span><p>${esc(paragraph)}</p></div>`).join('')}<button id="lp-theory-done" class="primary">Pročitao/la sam — pokaži primjer →</button></section>`;on('lp-theory-done','onclick',()=>{row.theoryRead=true;row.updatedAt=new Date().toISOString();context.save();open(id,1);});}
    if(stage===1){host.innerHTML=`<section class="card lp-reading"><span class="eyebrow">KORAK 2 / POGLEDAJ PRIMJER</span><h2>Razrađen primjer</h2><pre class="lp-example">${esc(lesson.example)}</pre><p>Pročitaj postupak, a zatim pokušaj riješiti praktični zadatak svojim riječima i računom.</p><button id="lp-example-done" class="primary">Razumijem primjer — moj zadatak →</button></section>`;on('lp-example-done','onclick',()=>{row.exampleRead=true;row.updatedAt=new Date().toISOString();context.save();open(id,2);});}
    if(stage===2){host.innerHTML=`<section class="card lp-practice"><div class="row between"><span class="eyebrow">KORAK 3 / URADI SAM</span>${lesson.subject==='math'?`<label>Težina<select id="lp-difficulty"><option value="easy">Osnovna</option><option value="medium">Srednja</option><option value="hard">Napredna</option></select></label><span class="tag">Varijanta ${row.variant}/200</span>`:'<span class="tag">Praktična vježba iz lekcije</span>'}</div><p class="lp-task-prompt">${esc(task.prompt)}</p><div class="task-fields">${task.fields.map((field,index)=>`<label>${esc(field.label)}${field.preserveWhitespace?`<textarea id="lp-answer-${index}" class="compact" data-lp-field="${esc(field.key)}" spellcheck="false">${esc(row.answers[field.key]||'')}</textarea>`:`<input id="lp-answer-${index}" data-lp-field="${esc(field.key)}" value="${esc(row.answers[field.key]||'')}" spellcheck="false" autocomplete="off" placeholder="${field.type==='list'?'Brojevi odvojeni ; ili razmakom':'Tvoj odgovor'}">`}</label>`).join('')}</div><label>Moj postupak i bilješke<textarea id="lp-notes" class="working-notes" placeholder="Zapiši račun, međurezultate ili objasni kako si zaključio/la…">${esc(row.notes)}</textarea></label><p class="lp-note">Provjera boduje polja odgovora. Bilješke su tvoj zapis postupka.</p><div class="row lp-actions"><button id="lp-check" class="primary">✓ Provjeri moj rad</button><button id="lp-hint">Pomoć</button><button id="lp-solution">Pokaži postupak</button>${typeof context.askAI==='function'?'<button id="lp-ai">✦ Pitaj asistenta</button>':''}${lesson.subject==='math'?'<button id="lp-new-task">Druga varijanta</button>':''}${lesson.blockChallengeId?'<button id="lp-linked-block">Otvori blokovski izazov</button>':''}</div><p id="lp-help-status" class="notice" role="status" hidden></p><div id="lp-solved" class="worked-solution" hidden><h3>Postupak ovog zadatka</h3><ol>${task.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${task.fields.map(field=>`<p>${esc(field.label)}: <strong>${esc(Array.isArray(field.answer)?(field.answer.length?field.answer.join('; '):'nema'):field.answer)}</strong></p>`).join('')}</div></section>`;
      context.root.querySelectorAll('[data-lp-field]').forEach(input=>input.oninput=()=>{row.answers[input.dataset.lpField]=input.value.slice(0,2048);row.dirty=true;context.root.querySelectorAll('[data-lp-stage]').forEach(button=>{if(+button.dataset.lpStage>=3)button.disabled=true;});row.updatedAt=new Date().toISOString();context.save();});on('lp-notes','oninput',()=>{row.notes=el('lp-notes').value.slice(0,6000);context.save();});
      const changeTask=()=>{row.answers={};row.dirty=false;row.assisted=false;row.lastCorrect=false;row.currentAttempts=0;row.completedAt='';context.save();open(id,2);};if(el('lp-difficulty')){el('lp-difficulty').value=row.difficulty;on('lp-difficulty','onchange',()=>{row.difficulty=el('lp-difficulty').value;changeTask();});}
      on('lp-new-task','onclick',()=>{row.variant=row.variant%200+1;changeTask();});on('lp-check','onclick',()=>{E().recordAttempt(p,id,row.answers);context.save();open(id,3);});
      const markAssisted=()=>{row.assisted=true;context.save();};on('lp-hint','onclick',()=>{markAssisted();el('lp-help-status').hidden=false;el('lp-help-status').textContent=task.hint||lesson.hint||'Vrati se razrađenom primjeru.';});on('lp-solution','onclick',()=>{markAssisted();el('lp-solved').hidden=false;});
      on('lp-ai','onclick',()=>{const material=getContext();if(material)context.askAI(material,markAssisted);});
      on('lp-linked-block','onclick',()=>{p.blockChallengeId=lesson.blockChallengeId;context.save();context.go('blocks');});
    }
    if(stage===3){const checked=E().resolveTask(id,row.variant,row.difficulty),result=window.ELDIExamEngine.checkTask(checked,row.answers);host.innerHTML=`<section class="card lp-review ${row.currentAttempts&&row.lastCorrect?'lp-correct':''}"><span class="eyebrow">KORAK 4 / PROVJERI</span><h2>${!row.currentAttempts?'Prvo uradi zadatak':row.lastCorrect?'✓ Zadatak je tačno riješen':'Pogledaj šta treba popraviti'}</h2><div class="lp-feedback-list">${result.fields.map(field=>`<p><strong>${field.correct?'✓':'○'} ${esc(checked.fields.find(f=>f.key===field.key).label)}</strong><span>${esc(field.message)}</span></p>`).join('')}</div><p>${row.currentAttempts?`Zabilježeno pokušaja: ${row.attempts}. ${row.assisted?'U trenutnoj vježbi korištena je pomoć.':'U trenutnoj vježbi nije označena pomoć.'}`:'Otvori samostalan rad i klikni „Provjeri moj rad“ za evidentiranje rezultata.'}</p><div class="row"><button id="lp-try-again">← Vrati se zadatku</button>${row.currentAttempts?'<button id="lp-review-next" class="primary">Moja preporuka →</button>':''}</div></section>`;on('lp-try-again','onclick',()=>open(id,2));on('lp-review-next','onclick',()=>open(id,4));}
    if(stage===4){const next=E().nextLesson(p,id),daily=E().dailyPlan(p,{subject:lesson.subject,grade:lesson.grade,count:3});host.innerHTML=`<section class="card lp-review"><span class="eyebrow">KORAK 5 / POVEŽI I PONOVI</span><h2>${row.lastCorrect?'Sljedeći korak je spreman.':'Vrati se objašnjenju i pokušaj ponovo.'}</h2><p>${row.lastCorrect?(row.assisted?'Tačan rad uz pomoć. Sada pokušaj samostalno; matematika ima novu varijantu zadatka.':'Tačan samostalan rezultat. Nastavi sljedeću vještinu i poveži pravilo s novim zadatkom.'):'Pregledaj označena polja, uporedi svoj postupak s primjerom i ponovi praktični zadatak.'}</p><div class="row"><button id="lp-relearn">Ponovi objašnjenje</button><button id="lp-practice-again">${lesson.subject==='math'?'Nova samostalna varijanta':'Ponovi samostalan rad'}</button>${next?`<button id="lp-next-skill" class="primary">Sljedeće: ${esc(next.title)} →</button>`:''}</div><h3>Preporuke iz tvojih rezultata</h3><div class="lp-related">${daily.map(item=>`<div><strong>${esc(item.title)}</strong><p>${esc(item.reason)}</p><button data-lp-related="${esc(item.lessonId)}">Otvori →</button></div>`).join('')}</div></section>`;on('lp-relearn','onclick',()=>open(id,0));on('lp-practice-again','onclick',()=>{if(lesson.subject==='math')row.variant=row.variant%200+1;row.answers={};row.dirty=false;row.assisted=false;row.lastCorrect=false;row.currentAttempts=0;row.completedAt='';context.save();open(id,2);});on('lp-next-skill','onclick',()=>open(next.id));context.root.querySelectorAll('[data-lp-related]').forEach(button=>button.onclick=()=>open(button.dataset.lpRelated));}
    window.scrollTo?.(0,0);
  }
  function renderMapping(){
    const p=profile(),w=work(),c=E().coverage(p,{subject:w.subject,grade:w.grade}),term=search.toLocaleLowerCase('bs'),outcomes=w.outcomes.filter(o=>o.subject===w.subject&&o.grade===w.grade&&(!term||(o.title+' '+o.officialId+' '+o.notes).toLocaleLowerCase('bs').includes(term)));
    el('lp-content').innerHTML=`<div class="lp-summary"><div><strong>${c.mappedSkills}<small>/ ${c.skills}</small></strong><span>vještina u uredničkoj / korisničkoj mapi</span></div><div><strong>${c.reviewedSkills}</strong><span>vještina s pregledanim povezivanjem</span></div><div><strong>${c.unmappedOutcomes}</strong><span>ishoda bez povezanih zadataka</span></div></div><article class="card lp-mapping-notice"><strong>Urednički plan i korisnička provjera</strong><p>Početna mapa organizuje postojeći sadržaj. Status „Pregledano u profilu“ označava provjeru korisnika koji je unio izvor; ne predstavlja odobrenje Pedagoškog zavoda.</p><details><summary>Službeni izvor i školska godina</summary><p>${esc(E().metadata.source.note)}</p><p>Izvor provjeren: ${E().metadata.checkedAt}. <span class="lp-source">${esc(E().metadata.source.url)}</span></p></details></article><div class="row lp-map-tools"><button id="lp-new-outcome" class="primary">＋ Dodaj ishod</button><button id="lp-export-map">↓ Izvezi mapu JSON</button><label class="lp-upload">↑ Uvezi / dopuni mapu<input id="lp-import-map" type="file" accept=".json,application/json"></label></div><p class="lp-note">Uvoz dopunjava mapu; zapise s istom oznakom zamjenjuje uvezenim zapisom. Najviše 1200 ishoda i 8 MB po datoteci.</p><p id="lp-map-status" role="status" aria-live="polite"></p><div id="lp-outcome-form"></div><div class="lp-outcome-list">${outcomes.map(o=>{const correct=o.lessonIds.filter(id=>E().progress(p,id).independent).length;return `<article class="card lp-outcome-card"><div><span class="tag">${o.status==='reviewed'?'✓ Pregledano u profilu':o.status==='editorial'?'Urednički plan':'Nacrt povezivanja'}</span><h3>${esc(o.title)}</h3><p>${o.lessonIds.length} povezanih vještina · ${correct} samostalno riješenih${o.officialId?' · '+esc(o.officialId):''}${o.schoolYear?' · '+esc(o.schoolYear):''}</p>${o.source?`<p class="lp-source">Izvor: ${esc(o.source)} · ${esc(o.page)}</p>`:''}${o.reviewer?`<p>Pregledao/la: ${esc(o.reviewer)} · ${esc(o.reviewedAt.slice(0,10))}</p>`:''}<p>${esc(o.notes.slice(0,240))}</p></div><button data-lp-outcome="${esc(o.id)}">Uredi povezivanje</button></article>`;}).join('')||'<p>Nema ishoda za ovaj izbor.</p>'}</div>`;
    on('lp-new-outcome','onclick',()=>editOutcome());on('lp-export-map','onclick',()=>context.exportFile?.('ELDI-mapa-kurikuluma.json',JSON.stringify(E().exportMapping(p),null,2)));
    const currentGeneration=generation;on('lp-import-map','onchange',async()=>{const originInput=el('lp-import-map'),file=originInput.files?.[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('Najviše 8 MB.');const rows=E().importMapping(await file.text());if(currentGeneration!==generation||profile()!==p||el('lp-import-map')!==originInput)return;const combined=new Map(w.outcomes.map(o=>[o.id,o]));for(const row of rows)combined.set(row.id,row);w.outcomes=E().normalizeOutcomes([...combined.values()]);context.save();renderMapping();el('lp-map-status').textContent=`✓ Uvezeno ${rows.length} ishoda. Ukupno u profilu: ${w.outcomes.length}.`;}catch(error){if(currentGeneration===generation&&profile()===p&&el('lp-map-status'))el('lp-map-status').textContent=error.message;}});
    context.root.querySelectorAll('[data-lp-outcome]').forEach(button=>button.onclick=()=>editOutcome(button.dataset.lpOutcome));
  }
  function editOutcome(id){const w=work(),existing=id?w.outcomes.find(o=>o.id===id):null,o=existing||{id:'custom-'+crypto.randomUUID(),subject:w.subject,grade:w.grade,title:'',officialId:'',source:'',schoolYear:'',page:'',reviewer:'',reviewedAt:'',status:'draft',lessonIds:[],notes:''};
    el('lp-outcome-form').innerHTML=`<form class="card lp-outcome-form" id="lp-outcome-editor"><h2>${existing?'Uredi':'Dodaj'} ishod</h2><p>${subjectName(o.subject)} · ${o.grade}. razred. Oznaka: ${esc(o.id)}</p><label>Naziv / tekst ishoda<input id="lp-outcome-title" maxlength="400" value="${esc(o.title)}" required></label><div class="lp-form-grid"><label>Službena oznaka ishoda<input id="lp-official-id" maxlength="240" value="${esc(o.officialId)}"></label><label>Školska godina<input id="lp-school-year" placeholder="2026/2027" maxlength="30" value="${esc(o.schoolYear)}"></label><label>Izvorni dokument (http/https)<input id="lp-source" type="url" maxlength="2000" value="${esc(o.source)}"></label><label>Stranica / odjeljak<input id="lp-source-page" maxlength="80" value="${esc(o.page)}"></label><label>Pregledao/la<input id="lp-reviewer" maxlength="160" value="${esc(o.reviewer)}"></label><label>Datum pregleda<input id="lp-reviewed-at" type="date" value="${esc(o.reviewedAt.slice(0,10))}"></label><label>Status<select id="lp-outcome-status"><option value="editorial">Urednički plan</option><option value="draft">Nacrt povezivanja</option><option value="reviewed">Pregledano u profilu</option></select></label></div><label>Povezane postojeće vještine (oznake odvojene razmakom ili ;)<textarea id="lp-outcome-skills" class="compact">${esc(o.lessonIds.join('; '))}</textarea></label><details><summary>Prikaži oznake vještina za ovaj predmet i razred</summary><div class="lp-skill-identities">${E().catalog.filter(l=>l.subject===o.subject&&l.grade===o.grade).map(l=>`<p><strong>${esc(l.id)}</strong> — ${esc(l.title)}</p>`).join('')}</div></details><label>Bilješke o pokrivenosti / šta još treba dodati<textarea id="lp-outcome-notes" class="working-notes" maxlength="6000">${esc(o.notes)}</textarea></label><p class="lp-note">Pregledano povezivanje zahtijeva popunjenu službenu oznaku, izvor, školsku godinu, stranicu, ime i datum pregleda. Ishod može ostati bez vještina radi evidencije nedostajućeg sadržaja.</p><p id="lp-outcome-error" role="alert"></p><div class="row"><button class="primary" type="submit">Sačuvaj povezivanje</button><button id="lp-outcome-cancel" type="button">Zatvori</button></div></form>`;
    el('lp-outcome-status').value=o.status;on('lp-outcome-cancel','onclick',()=>{el('lp-outcome-form').innerHTML='';});on('lp-outcome-editor','onsubmit',event=>{event.preventDefault();try{const reviewed=el('lp-reviewed-at').value,row=E().normalizeOutcome({...o,title:el('lp-outcome-title').value,officialId:el('lp-official-id').value,source:el('lp-source').value,schoolYear:el('lp-school-year').value,page:el('lp-source-page').value,reviewer:el('lp-reviewer').value,reviewedAt:reviewed?reviewed+'T12:00:00.000Z':'',status:el('lp-outcome-status').value,lessonIds:el('lp-outcome-skills').value.trim().split(/[\s;,]+/).filter(Boolean),notes:el('lp-outcome-notes').value});const rows=w.outcomes.filter(item=>item.id!==row.id).concat(row);w.outcomes=E().normalizeOutcomes(rows);context.save();renderMapping();el('lp-map-status').textContent='✓ Povezivanje i bilješke su sačuvani u ovom profilu.';}catch(error){el('lp-outcome-error').textContent=error.message;}});el('lp-outcome-form').scrollIntoView?.({block:'start'});el('lp-outcome-title').focus();
  }
  function getContext(){
    if(!activeLesson||!context||context.profile()!==activeLesson.p||!context.root.querySelector('.lp-lesson')){assistantRequest=null;return null;}
    const{lesson,row,task,stage}=activeLesson;assistantRequest=activeLesson;
    const input=task.fields.map(field=>`${field.label}: ${row.answers[field.key]||'(nije uneseno)'}`).join('\n')+'\n\nMoj postupak / bilješke:\n'+(row.notes||'(nije uneseno)'),bytes=new TextEncoder().encode(input),bounded=bytes.length<=8192?input:new TextDecoder().decode(bytes.subarray(0,8192)).replace(/\uFFFD$/,'');
    return{title:lesson.title,subject:lesson.subject,grade:lesson.grade,statement:[...(stage===0?['Objašnjenje lekcije:',...lesson.body]:[]),'Praktični zadatak:',task.prompt,...task.fields.map(field=>field.label)].join('\n'),input:bounded};
  }
  function markAssisted(){
    if(!activeLesson||assistantRequest!==activeLesson||!context||context.profile()!==activeLesson.p||!context.root.querySelector('.lp-lesson'))return false;
    activeLesson.row.assisted=true;context.save();return true;
  }
  return{mount,open,dashboard,getContext,markAssisted};
})();
