'use strict';
window.ELDIMaintenance=(()=>{
  let context=null;
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function mount(options){
    context=options;const desktop=window.eldiDesktop;
    options.root.innerHTML=`<div class="eyebrow">SIGURNOSNE KOPIJE I NOVA IZDANJA</div><h1>Tvoj rad ostaje sačuvan.</h1><p>Profili, zadaci i projekti čuvaju se na ovom računaru. Automatske kopije zadržavaju pet posljednjih sačuvanih verzija; prijava asistenta i API ključevi čuvaju se odvojeno.</p><div class="maintenance-grid"><article class="card"><span class="tag">LOKALNO ČUVANJE</span><h2>Sigurnosne kopije</h2><p>Sačuvaj cijelu učionicu ili vrati raniji rad. Prije vraćanja aplikacija sačuva sadašnje stanje.</p><div class="row"><button id="backup-now" class="primary">Sačuvaj kopiju sada</button><button id="backup-export">Izvezi cijelu učionicu JSON</button><label class="backup-import-label">Uvezi učionicu JSON<input id="backup-import" type="file" accept=".json,application/json"></label></div><p id="backup-status" role="status" aria-live="polite"></p><div id="backup-list"></div></article><article class="card"><span class="tag">GITHUB / WINDOWS</span><h2>Provjera izdanja</h2><p>Trenutna verzija: <strong>${escape(desktop?.version||'33.33.0')}</strong>. Preuzimanja vode na GitHub izdanje autora.</p><button id="update-check" class="primary">Provjeri novo izdanje</button><p id="update-status" role="status" aria-live="polite"></p><div id="update-links"></div></article></div>`;
    const byId=id=>options.root.querySelector('#'+id),status=message=>{if(byId('backup-status'))byId('backup-status').textContent=message;};
    async function refresh(){if(!desktop?.backupList){byId('backup-list').textContent='Automatske kopije dostupne su u Windows aplikaciji.';return;}const rows=await desktop.backupList();if(!byId('backup-list'))return;byId('backup-list').innerHTML=rows.length?'<div class="backup-rows">'+rows.map(row=>`<div class="backup-row"><div><strong>${escape(new Date(row.createdAt).toLocaleString('bs-BA'))}</strong><small>${(row.bytes/1024/1024).toFixed(2)} MB</small></div><button data-restore="${escape(row.id)}">Pregledaj i vrati</button></div>`).join('')+'</div>':'<p>Prva kopija nastaje automatski nakon čuvanja rada.</p>';byId('backup-list').querySelectorAll('[data-restore]').forEach(button=>button.onclick=async()=>{try{const value=await desktop.backupRead(button.dataset.restore);const accepted=await review(value,'Vrati sigurnosnu kopiju');if(!accepted)return;await desktop.backupSave(options.store(),true);await options.restore(value);status('Raniji rad je vraćen.');await refresh();}catch(error){status(error.message);}});}
    byId('backup-now').onclick=async()=>{try{if(!desktop?.backupSave)throw Error('Kopije su dostupne u desktop aplikaciji.');await desktop.backupSave(options.store(),true);status('Cijela učionica je sačuvana.');await refresh();}catch(error){status(error.message);}};
    byId('backup-export').onclick=()=>{try{const value=options.cleanStore(options.store());options.exportFile('ELDI-EDU-Ucionica.json',JSON.stringify({app:'ELDI EDU',kind:'classroom-backup',schema:1,store:value},null,2),'application/json');status('Izvoz učionice je pripremljen.');}catch(error){status(error.message);}};
    byId('backup-import').onchange=async()=>{try{const file=byId('backup-import').files[0];if(!file)return;if(file.size>120*1024*1024)throw Error('Učionica smije imati do 120 MB.');const value=JSON.parse(await file.text());if(value.app!=='ELDI EDU'||value.kind!=='classroom-backup'||value.schema!==1)throw Error('Format učionice nije podržan.');const cleaned=options.cleanStore(value.store);if(!await review(cleaned,'Uvezi učionicu'))return;if(desktop?.backupSave)await desktop.backupSave(options.store(),true);await options.restore(cleaned);status('Učionica je učitana.');await refresh();}catch(error){status(error.message);}finally{if(byId('backup-import'))byId('backup-import').value='';}};
    byId('update-check').onclick=async()=>{const button=byId('update-check');button.disabled=true;try{if(!desktop?.checkUpdates)throw Error('Provjera izdanja je dostupna u Windows aplikaciji.');byId('update-status').textContent='Provjeravam GitHub…';const result=await desktop.checkUpdates();if(!byId('update-status'))return;byId('update-status').textContent=result.available?'Dostupno je novo izdanje '+result.latest+'.':'Imaš trenutno ili novije izdanje od objavljenog ('+result.latest+').';byId('update-links').innerHTML=`<button data-release-url="${escape(result.url)}">Otvori izdanje na GitHubu ↗</button>`+(result.available?result.assets.filter(asset=>/\.exe$/.test(asset.name)).map(asset=>`<button data-release-url="${escape(asset.url)}">${escape(asset.name)} ↗</button>`).join(''):'');byId('update-links').querySelectorAll('[data-release-url]').forEach(link=>link.onclick=()=>desktop.openRelease(link.dataset.releaseUrl));}catch(error){if(byId('update-status'))byId('update-status').textContent=error.message;}finally{if(button.isConnected)button.disabled=false;}};
    refresh().catch(error=>status(error.message));
  }
  function review(value,title){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='backup-review';dialog.innerHTML=`<h2>${escape(title)}</h2><p>Učitavaš ${value.profiles.length} profila. Sadašnji rad bit će sačuvan kao sigurnosna kopija.</p><ul>${value.profiles.slice(0,20).map(profile=>'<li>'+escape(profile.name)+'</li>').join('')}</ul><div class="row"><button data-accept class="primary">Vrati ove profile</button><button data-cancel>Odustani</button></div>`;document.body.append(dialog);const finish=answer=>{dialog.remove();resolve(answer);};dialog.querySelector('[data-accept]').onclick=()=>finish(true);dialog.querySelector('[data-cancel]').onclick=()=>finish(false);dialog.oncancel=event=>{event.preventDefault();finish(false);};dialog.showModal();});}
  return {mount};
})();
