'use strict';
window.ELDITeacher=(()=>{
  let context,selectedClass=null,tab='classes',notice='';
  const E=()=>window.ELDITeacherEngine;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>context.root.querySelector('#'+id);
  const profile=()=>context.profile();
  const state=()=>profile().teacherWork||=(E().normalizeState());
  const profiles=()=>context.profiles?.()||[profile()];
  const subjectName=s=>({math:'Matematika',informatics:'Informatika',mixed:'Matematika + informatika'}[s]||s);
  const filename=value=>'ELDI-'+String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').slice(0,80);
  const run=fn=>{try{fn();}catch(error){notice=error.message;const node=$('teacher-notice');if(node){node.textContent=notice;node.classList.add('error');}}};
  function commit(message='Sačuvano.'){context.save();notice=message;render();}
  function mount(options){context=options;tab='classes';notice='';const s=state();selectedClass=s.classes.some(c=>c.id===selectedClass)?selectedClass:s.classes[0]?.id??null;render();}
  function header(){const s=state(),all=E().report(s,profiles());return `<div class="teacher-heading"><div><div class="eyebrow">NASTAVNIČKI CENTAR / LOKALNA UČIONICA</div><h1>Planiraj čas.<br>Prati svaki korak.</h1><p>Odjeljenja, zaduženja i stvarni rezultati profila na ovom računaru. Zaduženja i učenički profili prenose se datotekama između računara.</p></div><div class="teacher-summary"><div><strong>${s.classes.length}</strong><span>odjeljenja</span></div><div><strong>${s.classes.reduce((n,c)=>n+c.roster.length,0)}</strong><span>učenika na spisku</span></div><div><strong>${s.assignments.length}</strong><span>zaduženja</span></div><div><strong>${all.filter(r=>r.examId).length}</strong><span>predanih pokušaja</span></div></div></div><div class="teacher-nav row">${[['classes','Odjeljenja'],['assignments','Zaduženja'],['received','Moj rad'],['results','Rezultati i komentari']].map(([key,label])=>`<button data-teacher-tab="${key}" class="${tab===key?'selected':''}">${label}</button>`).join('')}</div><p id="teacher-notice" class="feedback" role="status">${esc(notice)}</p>`;}
  function render(){context.root.innerHTML=header()+`<section class="teacher-center" id="teacher-panel"></section>`;context.root.querySelectorAll('[data-teacher-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.teacherTab;notice='';render();});({classes:renderClasses,assignments:renderAssignments,received:renderReceived,results:renderResults})[tab]();}
  function classSelect(){return `<label>Odjeljenje<select id="teacher-class"><option value="">Odaberi odjeljenje</option>${state().classes.map(c=>`<option value="${esc(c.id)}" ${c.id===selectedClass?'selected':''}>${esc(c.name)} · ${c.gradeLevel}. razred</option>`).join('')}</select></label>`;}
  function bindClass(){if($('teacher-class'))$('teacher-class').onchange=()=>{selectedClass=$('teacher-class').value||null;render();};}
  function renderClasses(){
    const s=state(),c=s.classes.find(c=>c.id===selectedClass),p=profile();
    $('teacher-panel').innerHTML=`<div class="teacher-columns"><article class="card"><span class="tag">ORGANIZACIJA</span><h2>Novo odjeljenje</h2><div class="controls"><label>Naziv odjeljenja<input id="teacher-class-name" maxlength="80" placeholder="npr. VI-2"></label><label>Razred<select id="teacher-class-grade">${[5,6,7,8,9].map(g=>`<option>${g}</option>`).join('')}</select></label></div><button class="primary" id="teacher-create-class">Dodaj odjeljenje</button><p class="teacher-muted">Spisak može sadržavati učenike kojima još nije napravljen lokalni profil.</p></article><article class="card"><h2>Spisak učenika</h2>${classSelect()}${c?`<div class="controls"><label>Ime ili oznaka učenika<input id="teacher-student-name" maxlength="60" placeholder="Ime učenika"></label><label>Lokalni profil<select id="teacher-student-profile"><option value="">Poveži kasnije</option>${profiles().filter(x=>x.id!==p.id).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label></div><button id="teacher-add-student">Dodaj učenika</button><div class="teacher-roster">${c.roster.map(student=>`<div class="teacher-roster-row"><strong>${esc(student.name)}</strong><label>Profil učenika<select data-roster-link="${esc(student.id)}"><option value="">Nije povezan</option>${profiles().map(x=>`<option value="${esc(x.id)}" ${x.id===student.profileId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><button data-remove-student="${esc(student.id)}" aria-label="Ukloni ${esc(student.name)} sa spiska">Ukloni</button></div>`).join('')||'<p>Dodajte prvog učenika.</p>'}</div>`:'<p>Kreiraj odjeljenje pa dodaj učenike.</p>'}</article></div><article class="card teacher-import"><h2>Prikupi rad s drugih računara</h2><p>Učenik na stranici Napredak izvozi cijeli profil. Uvezi taj JSON i poveži novi profil s učenikom na spisku. Uvezeni rad će se pojaviti u rezultatima odgovarajućeg zaduženja.</p>${context.importProfile?'<label>Uvezi učenički profil JSON<input id="teacher-import-profile" type="file" accept=".json,application/json"></label>':'<button id="teacher-open-progress">Otvori uvoz profila na stranici Napredak</button>'}</article>`;
    bindClass();$('teacher-create-class').onclick=()=>run(()=>{const added=E().createClass(s,{name:$('teacher-class-name').value,gradeLevel:+$('teacher-class-grade').value});selectedClass=added.id;commit('Odjeljenje je dodano.');});
    if(c){$('teacher-student-profile').onchange=()=>{const choice=profiles().find(x=>x.id===$('teacher-student-profile').value);if(choice&&!$('teacher-student-name').value.trim())$('teacher-student-name').value=choice.name;};$('teacher-add-student').onclick=()=>run(()=>{E().addStudent(s,c.id,{name:$('teacher-student-name').value,profileId:$('teacher-student-profile').value||null});commit('Učenik je dodan.');});context.root.querySelectorAll('[data-roster-link]').forEach(select=>select.onchange=()=>run(()=>{const newId=select.value||null,student=c.roster.find(x=>x.id===select.dataset.rosterLink);if(newId&&c.roster.some(x=>x.id!==student.id&&x.profileId===newId)){select.value=student.profileId||'';throw Error('Profil je već povezan s drugim učenikom u ovom odjeljenju.');}student.profileId=newId;commit('Profil je povezan sa učenikom.');}));context.root.querySelectorAll('[data-remove-student]').forEach(button=>button.onclick=()=>{c.roster=c.roster.filter(x=>x.id!==button.dataset.removeStudent);commit('Učenik je uklonjen sa spiska; profil i rezultati ostaju sačuvani.');});}
    if($('teacher-open-progress'))$('teacher-open-progress').onclick=()=>context.go('progress');
    if($('teacher-import-profile'))$('teacher-import-profile').onchange=async()=>{const ctx=context,owner=p;try{const f=$('teacher-import-profile').files[0];if(!f)return;if(f.size>window.ELDIProfiles.MAX_PROFILE_BYTES)throw Error('Profil smije imati do 30 MB.');const cleaned=window.ELDIProfiles.importProfile(JSON.parse(await f.text()));if(context!==ctx||profile()!==owner)return;await ctx.importProfile(cleaned);notice='Profil je uvezen. Poveži ga s učenikom na spisku.';render();}catch(error){if(context===ctx&&profile()===owner){notice=error.message;render();}}};
  }
  function assignmentCard(a,received=false){const s=state(),submissions=s.submissions.filter(x=>x.assignmentId===a.id);return `<article class="card teacher-assignment"><span class="tag">${a.gradeLevel}. razred · ${esc(subjectName(a.subject))} · ${a.count} zadataka</span><h3>${esc(a.name)}</h3><p>${a.dueDate?'Rok: '+esc(a.dueDate):'Bez roka'}${a.teacherName?' · '+esc(a.teacherName):''}</p>${a.instructions?`<p class="teacher-instructions">${esc(a.instructions)}</p>`:''}<div class="row"><button data-export-assignment="${esc(a.id)}">Izvezi JSON</button>${received?`<button class="primary" data-start-assignment="${esc(a.id)}">${submissions.length?'Ponovi zaduženje':'Rješavaj'}</button>`:`<button class="primary" data-distribute-assignment="${esc(a.id)}">Dodijeli povezanim profilima</button><button data-preview-assignment="${esc(a.id)}">Pregledaj zadatke</button>`}</div>${received?`<p>${submissions.length} predanih pokušaja</p><div class="teacher-attempts">${submissions.slice(-5).reverse().map(submission=>{const result=E().verifiedResult(submission.result??profile().exams?.find(e=>e.id===submission.examId),a);return result?`<button data-open-submission="${esc(submission.examId)}">${new Date(result.finishedAt).toLocaleDateString('bs-BA')} · ${result.correct}/${result.total} · ocjena ${result.gradeResult.grade}</button>`:'';}).join('')}</div>`:''}</article>`;}
  function renderAssignments(){
    const s=state(),c=s.classes.find(c=>c.id===selectedClass);
    $('teacher-panel').innerHTML=`<div class="row teacher-filter">${classSelect()}<label>Uvezi zaduženje JSON<input id="teacher-import-assignment" type="file" accept=".json,application/json"></label></div>${c?`<article class="card"><h2>Sastavi zaduženje za ${esc(c.name)}</h2><div class="controls"><label>Naziv<input id="teacher-assignment-name" maxlength="160" placeholder="npr. Razlomci — samostalni rad"></label><label>Predmet<select id="teacher-subject"><option value="math">Matematika</option><option value="informatics">Informatika</option><option value="mixed">Matematika + informatika</option></select></label><label>Oblast<select id="teacher-category"></select></label><label>Lekcija<select id="teacher-lesson"></select></label><label>Broj zadataka<input id="teacher-count" type="number" min="1" max="50" value="10"></label><label>Nivo matematike<select id="teacher-level"><option value="easy">Osnovni</option><option value="medium" selected>Srednji</option><option value="hard">Napredni</option></select></label><label>Broj varijante<input id="teacher-seed" type="number" min="1" max="9999" value="1"></label><label>Rok predaje<input id="teacher-due" type="date"></label></div><label>Uputa učenicima<textarea id="teacher-instructions" class="compact" maxlength="6000" placeholder="Zapiši postupak uz svaki odgovor…"></textarea></label><details><summary>Pragovi ocjena</summary><div class="row">${[2,3,4,5].map((g,i)=>`<label>Ocjena ${g} od (%)<input id="teacher-threshold-${g}" type="number" min="1" max="100" value="${[50,65,80,90][i]}"></label>`).join('')}</div></details><div class="row"><button id="teacher-create-assignment" class="primary">Sačuvaj zaduženje</button></div><p class="teacher-muted">Odabir jedne informatičke lekcije daje jedan praktični zadatak; za više zadataka odaberi oblast ili sve lekcije.</p></article>`:'<div class="notice">Na kartici Odjeljenja prvo napravi spisak učenika.</div>'}<div class="teacher-assignment-grid">${s.assignments.filter(a=>!selectedClass||a.classId===selectedClass).slice().reverse().map(a=>assignmentCard(a)).join('')||'<p>Još nema zaduženja za ovo odjeljenje.</p>'}</div>`;
    bindClass();bindImportAssignment();bindAssignmentButtons();
    if(c){const fillLessons=()=>{const rows=E().lessons($('teacher-subject').value,c.gradeLevel,$('teacher-category').value);$('teacher-lesson').innerHTML='<option value="">Sve lekcije odabrane oblasti</option>'+rows.map(l=>`<option value="${esc(l.id)}">${esc(l.title)}</option>`).join('');};const fillCategories=()=>{$('teacher-category').innerHTML='<option value="all">Sve oblasti</option>'+window.ELDIExamEngine.categories($('teacher-subject').value,c.gradeLevel).map(x=>`<option>${esc(x)}</option>`).join('');fillLessons();};$('teacher-subject').onchange=fillCategories;$('teacher-category').onchange=fillLessons;$('teacher-lesson').onchange=()=>{const lesson=E().lessons($('teacher-subject').value,c.gradeLevel).find(x=>x.id===$('teacher-lesson').value);if(lesson?.kind==='informatics')$('teacher-count').value='1';};fillCategories();$('teacher-create-assignment').onclick=()=>run(()=>{E().createAssignment(s,{classId:c.id,name:$('teacher-assignment-name').value,teacherName:profile().name,subject:$('teacher-subject').value,category:$('teacher-category').value,lessonId:$('teacher-lesson').value,count:+$('teacher-count').value,seed:+$('teacher-seed').value,difficulty:$('teacher-level').value,dueDate:$('teacher-due').value,instructions:$('teacher-instructions').value,thresholds:[2,3,4,5].map(g=>+$('teacher-threshold-'+g).value)});commit('Zaduženje je spremno za dodjelu i izvoz.');});}
  }
  function bindImportAssignment(){if(!$('teacher-import-assignment'))return;$('teacher-import-assignment').onchange=async()=>{const ctx=context,p=profile();try{const f=$('teacher-import-assignment').files[0];if(!f)return;if(f.size>E().LIMITS.bytes)throw Error('Zaduženje smije imati do 8 MB.');const pack=JSON.parse(await f.text());if(context!==ctx||profile()!==p)return;E().importAssignment(state(),pack);tab='received';commit('Zaduženje je uvezeno. Možeš početi rješavati.');}catch(error){if(context===ctx&&profile()===p){notice=error.message;render();}}};}
  function bindAssignmentButtons(){context.root.querySelectorAll('[data-export-assignment]').forEach(button=>button.onclick=()=>run(()=>{const a=state().assignments.find(x=>x.id===button.dataset.exportAssignment);context.exportFile(filename(a.name)+'.json',JSON.stringify(E().exportAssignment(a),null,2),'application/json');}));context.root.querySelectorAll('[data-distribute-assignment]').forEach(button=>button.onclick=()=>run(()=>{const a=state().assignments.find(x=>x.id===button.dataset.distributeAssignment),c=state().classes.find(x=>x.id===a.classId),targets=(c?.roster??[]).map(s=>profiles().find(p=>p.id===s.profileId)).filter(Boolean);if(!targets.length)throw Error('Poveži učenike s lokalnim profilima na kartici Odjeljenja.');for(const target of targets)E().distribute(a,target);commit(`Zaduženje je dodijeljeno u ${targets.length} lokalnih profila. Učenici ga otvaraju u kartici Moj rad svog profila.`);}));context.root.querySelectorAll('[data-preview-assignment]').forEach(button=>button.onclick=()=>previewAssignment(state().assignments.find(x=>x.id===button.dataset.previewAssignment)));context.root.querySelectorAll('[data-start-assignment]').forEach(button=>button.onclick=()=>run(()=>{if(state().activeSession)throw Error('Prvo nastavi ili završi otvoreno zaduženje.');E().startAssignment(state(),button.dataset.startAssignment,profile().name);context.save();renderSession();}));}
  function previewAssignment(a){context.root.innerHTML=`<div class="row"><button id="teacher-back">← Zaduženja</button><button id="teacher-print">Štampaj radni list</button></div><section class="teacher-print-area"><div class="eyebrow">${a.gradeLevel}. RAZRED / ${esc(subjectName(a.subject))}</div><h1>${esc(a.name)}</h1><p>${esc(a.instructions)}</p>${a.refs.map((r,i)=>{const t=window.ELDIExamEngine.resolve(r);return `<article class="card"><h3>${i+1}. ${esc(t.title)}</h3><p>${esc(t.prompt)}</p>${t.fields.map(f=>`<p>${esc(f.label)}: ____________________________</p>`).join('')}<div class="teacher-answer-space">Postupak:</div></article>`;}).join('')}</section>`;$('teacher-back').onclick=render;$('teacher-print').onclick=print;}
  function renderReceived(){const s=state();$('teacher-panel').innerHTML=`<div class="row teacher-filter"><label>Uvezi zaduženje JSON<input id="teacher-import-assignment" type="file" accept=".json,application/json"></label>${s.activeSession?'<button id="teacher-resume" class="primary">Nastavi otvoreno zaduženje</button>':''}</div><p class="teacher-muted">Ovdje radiš u svom trenutno odabranom profilu. Odgovori i postupci se čuvaju, a ocjena i rješenja se prikazuju nakon predaje.</p><div class="teacher-assignment-grid">${s.assignments.slice().reverse().map(a=>assignmentCard(a,true)).join('')||'<div class="notice">Nastavnik dodjeljuje zaduženje lokalnom profilu ili šalje JSON koji ovdje uvoziš.</div>'}</div>`;bindImportAssignment();bindAssignmentButtons();if($('teacher-resume'))$('teacher-resume').onclick=renderSession;context.root.querySelectorAll('[data-open-submission]').forEach(button=>button.onclick=()=>run(()=>{const submission=s.submissions.find(x=>x.examId===button.dataset.openSubmission),a=s.assignments.find(x=>x.id===submission.assignmentId),result=E().verifiedResult(submission.result??profile().exams?.find(x=>x.id===submission.examId),a);if(!result)throw Error('Sačuvani rezultat nije ispravan.');renderSubmission(result,a);}));}
  function renderSession(){
    const active=state().activeSession;if(!active){render();return;}const a=state().assignments.find(x=>x.id===active.assignmentId),session=active.session,tasks=session.refs.map(window.ELDIExamEngine.resolve);
    context.root.innerHTML=`<div class="row between teacher-solver-controls"><button id="teacher-solver-back">← Moj rad</button><span>${session.total} zadataka · ${a.gradeLevel}. razred</span><button id="teacher-finish" class="primary">Predaj i ocijeni</button></div><div class="eyebrow">ZADUŽENJE / ${esc(profile().name)}</div><h1>${esc(a.name)}</h1><p>${esc(a.instructions)}</p><p class="teacher-muted">Svaki potpuno tačan zadatak nosi jedan bod. Nastavnik može zasebno pregledati zapisani postupak i dodati komentar.</p><p id="teacher-work-status" role="status"></p>${tasks.map((task,i)=>`<article class="card exam-question"><span class="tag">${i+1}/${session.total} · ${esc(task.title)}</span><p class="task-prompt">${esc(task.prompt)}</p><div class="task-fields">${task.fields.map(f=>`<label>${esc(f.label)}${f.preserveWhitespace?`<textarea class="compact" data-assignment-index="${i}" data-assignment-key="${esc(f.key)}" spellcheck="false">${esc(session.answers[i]?.[f.key]??'')}</textarea>`:`<input data-assignment-index="${i}" data-assignment-key="${esc(f.key)}" value="${esc(session.answers[i]?.[f.key]??'')}" autocomplete="off" spellcheck="false">`}</label>`).join('')}</div><label>Moj postupak<textarea class="working-notes" maxlength="6000" data-assignment-notes="${i}" placeholder="Zapiši korake rješavanja…">${esc(session.notes[i]??'')}</textarea></label></article>`).join('')}<div class="row"><button id="teacher-finish-bottom" class="primary">Predaj zaduženje</button></div>`;
    const update=()=>{$('teacher-work-status').textContent=`Popunjeno ${tasks.filter((t,i)=>t.fields.every(f=>String(session.answers[i]?.[f.key]??'').trim())).length}/${session.total} zadataka.`;};context.root.querySelectorAll('[data-assignment-key]').forEach(input=>input.oninput=()=>{session.answers[input.dataset.assignmentIndex]||={};session.answers[input.dataset.assignmentIndex][input.dataset.assignmentKey]=input.value.slice(0,2048);context.save();update();});context.root.querySelectorAll('[data-assignment-notes]').forEach(input=>input.oninput=()=>{session.notes[input.dataset.assignmentNotes]=input.value.slice(0,6000);context.save();});$('teacher-solver-back').onclick=()=>{tab='received';render();};const finish=()=>{try{const p=profile(),result=E().finishAssignment(state());p.exams||=[];p.exams.push(result);p.exams=p.exams.slice(-100);p.mathWork||={answers:{},notes:{},results:{},session:[],sheets:[]};p.mathWork.results||={};p.infoWork||={results:{}};p.infoWork.results||={};result.details.forEach((detail,i)=>{const ref=result.refs[i],target=ref.kind==='math'?p.mathWork.results:p.infoWork.results,old=target[detail.taskId]||{};target[detail.taskId]={...old,correct:!!(old.correct||detail.correct),lastCorrect:detail.correct,attempts:(old.attempts||0)+1,grade:result.gradeLevel,title:detail.title,date:result.finishedAt};});window.ELDIAwards.recordExamCertificate(p,result);context.save();renderSubmission(result,a);}catch(error){$('teacher-work-status').textContent=error.message;}};$('teacher-finish').onclick=finish;$('teacher-finish-bottom').onclick=finish;update();
  }
  function renderSubmission(result,a){
    const record=(profile().certificates||[]).find(c=>c.examId===result.id);
    context.root.innerHTML=`<section class="teacher-print-area"><div class="card teacher-result-top"><div><div class="eyebrow">ZADUŽENJE JE PREDANO</div><h1>${esc(a.name)}</h1><p>${esc(result.profileName)} · ${a.gradeLevel}. razred</p><div class="row"><button id="teacher-result-back">← Moj rad</button><button id="teacher-print-result">Štampaj rezultat</button>${record&&context.showCertificate?'<button id="teacher-result-certificate">Diploma / potvrda</button>':''}</div></div><div class="teacher-grade"><strong>${result.gradeResult.grade}</strong><span>${result.correct}/${result.total} · ${result.percentage.toFixed(1)}%</span></div></div>${result.refs.map((r,i)=>{const t=window.ELDIExamEngine.resolve(r);return `<article class="card"><span class="tag">${i+1}. ${result.details[i].correct?'✓ 1 bod':'0 bodova'} · ${esc(t.title)}</span><p>${esc(t.prompt)}</p>${t.fields.map(f=>`<p><strong>${esc(f.label)}</strong><br>Tvoj odgovor: ${esc(result.answers[i]?.[f.key]??'—')}<br>Tačno: ${esc(Array.isArray(f.answer)?f.answer.join('; '):f.answer)}</p>`).join('')}<details><summary>Postupak rješavanja</summary><ol>${t.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${result.notes[i]?`<h3>Tvoj zapis</h3><pre class="result">${esc(result.notes[i])}</pre>`:''}</details></article>`;}).join('')}</section>`;$('teacher-result-back').onclick=()=>{tab='received';render();};$('teacher-print-result').onclick=print;if($('teacher-result-certificate'))$('teacher-result-certificate').onclick=()=>context.showCertificate(record);
  }
  function renderResults(){
    const rows=E().report(state(),profiles(),selectedClass),finished=rows.filter(r=>r.examId);
    $('teacher-panel').innerHTML=`<div class="row teacher-filter">${classSelect()}<button id="teacher-report-csv">Izvezi CSV</button><button id="teacher-report-print">Štampaj izvještaj</button></div><section class="teacher-print-area"><h2>Rezultati odjeljenja</h2><p>${finished.length} predanih pokušaja · ${finished.filter(r=>r.reviewedAt).length} nastavničkih pregleda</p><div class="teacher-table-scroll"><table class="teacher-report-table"><thead><tr><th>Učenik</th><th>Zaduženje</th><th>Status</th><th>Bodovi</th><th>Ocjena</th><th>Komentar / pregled</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${esc(r.studentName)}<small>${esc(r.className)}</small></td><td>${esc(r.assignmentName)}</td><td>${esc(r.status)}</td><td>${r.examId?r.correct+'/'+r.total:'—'}</td><td>${r.examId?r.grade:'—'}${r.manualGrade?`<small>Nastavnička: ${r.manualGrade}</small>`:''}</td><td>${esc(r.comment)}${r.examId?`<button data-review-row="${i}">${r.reviewedAt?'Otvori pregled':'Pregledaj postupak'}</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">Dodaj učenike, napravi i dodijeli prvo zaduženje.</td></tr>'}</tbody></table></div></section>`;
    bindClass();$('teacher-report-csv').onclick=()=>context.exportFile('ELDI-nastavnicki-izvjestaj.csv',E().csvReport(rows),'text/csv;charset=utf-8');$('teacher-report-print').onclick=print;context.root.querySelectorAll('[data-review-row]').forEach(b=>b.onclick=()=>renderReview(rows[+b.dataset.reviewRow]));
  }
  function renderReview(row){
    const result=row.result,a=state().assignments.find(x=>x.id===row.assignmentId);
    context.root.innerHTML=`<div class="row"><button id="teacher-review-back">← Rezultati</button><button id="teacher-review-print">Štampaj pregled</button></div><section class="teacher-print-area"><div class="eyebrow">NASTAVNIČKI PREGLED / ${esc(row.className)}</div><h1>${esc(row.studentName)}</h1><p>${esc(row.assignmentName)} · ${result.correct}/${result.total} · automatska ocjena ${result.gradeResult.grade}</p>${result.refs.map((ref,i)=>{const task=window.ELDIExamEngine.resolve(ref);return `<article class="card"><h3>${i+1}. ${esc(task.title)}</h3><p>${esc(task.prompt)}</p><p>${result.details[i].correct?'✓ Tačan odgovor':'Odgovor nije potpuno tačan'}</p>${task.fields.map(f=>`<p>${esc(f.label)}: <strong>${esc(result.answers[i]?.[f.key]??'—')}</strong><br>Tačno: ${esc(Array.isArray(f.answer)?f.answer.join('; '):f.answer)}</p>`).join('')}<h4>Učenikov postupak</h4><pre class="result">${esc(result.notes[i]||'Postupak nije zapisan.')}</pre></article>`;}).join('')}<article class="card teacher-review-form"><h2>Komentar nastavnika</h2><label>Komentar i preporuka<textarea id="teacher-review-comment" maxlength="6000" class="working-notes">${esc(row.comment)}</textarea></label><label>Nastavnička ocjena<select id="teacher-review-grade"><option value="">Bez dodatne ocjene</option>${[1,2,3,4,5].map(g=>`<option value="${g}" ${row.manualGrade===g?'selected':''}>${g}</option>`).join('')}</select></label><p class="teacher-muted">Nastavnička ocjena se prikazuje odvojeno od automatskog rezultata. Zapisani postupak pregleda nastavnik.</p><button id="teacher-save-review" class="primary">Sačuvaj pregled</button><p id="teacher-review-status" role="status"></p></article></section>`;
    $('teacher-review-back').onclick=render;$('teacher-review-print').onclick=print;$('teacher-save-review').onclick=()=>{try{E().reviewSubmission(state(),{assignmentId:a.id,examId:result.id,profileId:row.profileId,comment:$('teacher-review-comment').value,manualGrade:$('teacher-review-grade').value?+$('teacher-review-grade').value:null});context.save();notice='Nastavnički pregled je sačuvan.';render();}catch(error){$('teacher-review-status').textContent=error.message;}};
  }
  async function print(){document.body.classList.add('printing-teacher');try{await context.print();}finally{document.body.classList.remove('printing-teacher');}}
  return{mount,render,renderSession,renderResults};
})();
