<?php
declare(strict_types=1);
final class ClassroomError extends RuntimeException { public function __construct(string $message, public int $status=400){parent::__construct($message);} }
final class Classroom {
 public function __construct(public PDO $db){$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$db->setAttribute(PDO::ATTR_EMULATE_PREPARES,false);}
 public function run(string $sql,array $params=[]):PDOStatement{$q=$this->db->prepare($sql);$q->execute($params);return $q;}
 public function schema():void{
  $tables=[
   'settings (name VARCHAR(60) PRIMARY KEY, value TEXT NOT NULL)',
   'users (id VARCHAR(40) PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, display_name VARCHAR(100) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(12) NOT NULL, created_at BIGINT NOT NULL)',
   'classes (id VARCHAR(40) PRIMARY KEY, title VARCHAR(100) NOT NULL, owner_id VARCHAR(40) NOT NULL, created_at BIGINT NOT NULL)',
   'enrollments (class_id VARCHAR(40) NOT NULL, user_id VARCHAR(40) NOT NULL, PRIMARY KEY(class_id,user_id))',
   'assignments (id VARCHAR(40) PRIMARY KEY, class_id VARCHAR(40) NOT NULL, title VARCHAR(150) NOT NULL, instructions TEXT NOT NULL, kind VARCHAR(12) NOT NULL, questions MEDIUMTEXT NOT NULL, due_at BIGINT NOT NULL, closed INT NOT NULL DEFAULT 0, created_at BIGINT NOT NULL)',
   'submissions (id VARCHAR(40) PRIMARY KEY, assignment_id VARCHAR(40) NOT NULL, user_id VARCHAR(40) NOT NULL, payload MEDIUMTEXT NOT NULL, score DOUBLE NOT NULL, max_score DOUBLE NOT NULL, feedback TEXT NOT NULL, grade VARCHAR(12) NOT NULL, submitted_at BIGINT NOT NULL, UNIQUE(assignment_id,user_id))',
   'limits (bucket VARCHAR(64) PRIMARY KEY, attempts INT NOT NULL, until_at BIGINT NOT NULL)',
  ];foreach($tables as $t)$this->db->exec('CREATE TABLE IF NOT EXISTS eldi3333_'.$t);
 }
 public function installed():bool{try{return (bool)$this->run("SELECT value FROM eldi3333_settings WHERE name='installed'")->fetchColumn();}catch(PDOException){return false;}}
 public static function id():string{return bin2hex(random_bytes(16));}
 public static function text(mixed $v,int $limit=100,bool $required=true):string{if(!is_string($v))throw new ClassroomError('Očekivan je tekst.');$v=trim($v);if(strlen($v)>$limit*4||($required&&$v===''))throw new ClassroomError('Nedostaje podatak ili je tekst predug.');return $v;}
 public static function password(string $p):string{if(strlen($p)<12||strlen($p)>128)throw new ClassroomError('Lozinka mora imati 12–128 znakova.');return password_hash($p,PASSWORD_DEFAULT);}
 public static function number(mixed $v):?float{if(!is_scalar($v)||strlen((string)$v)>80)return null;$s=str_replace([',','−'],['.','-'],trim((string)$v));$part='[+-]?(?:\d+(?:\.\d*)?|\.\d+)';if(preg_match('~^('.$part.')\s*/\s*('.$part.')$~D',$s,$m))return (float)$m[2]==0.0?null:(float)$m[1]/(float)$m[2];if(!preg_match('~^'.$part.'$~D',$s))return null;$n=(float)$s;return is_finite($n)?$n:null;}
 public function install(string $username,string $name,string $password):void{if($this->installed())throw new ClassroomError('Instalacija je već završena.',409);$username=strtolower(self::text($username,60));if(!preg_match('/^[a-z0-9._-]{3,60}$/D',$username))throw new ClassroomError('Korisničko ime: 3–60 slova a–z, cifara, tačka, crtica.');$hash=self::password($password);$this->schema();$this->db->beginTransaction();try{$this->run('INSERT INTO eldi3333_settings(name,value) VALUES(?,?)',['installed',(string)time()]);$this->run('INSERT INTO eldi3333_users VALUES(?,?,?,?,?,?)',[self::id(),$username,self::text($name),$hash,'teacher',time()]);$this->db->commit();}catch(Throwable $e){$this->db->rollBack();throw $e;}}
 public function throttle(string $bucket):void{$this->run('DELETE FROM eldi3333_limits WHERE until_at < ?',[time()]);$v=$this->run('SELECT * FROM eldi3333_limits WHERE bucket=?',[$bucket])->fetch();if($v&&$v['attempts']>=15)throw new ClassroomError('Previše pokušaja. Sačekajte 15 minuta.',429);if($v)$this->run('UPDATE eldi3333_limits SET attempts=attempts+1 WHERE bucket=?',[$bucket]);else $this->run('INSERT INTO eldi3333_limits VALUES(?,?,?)',[$bucket,1,time()+900]);}
 public function login(string $username,string $password,string $bucket):array{$this->throttle($bucket);$user=$this->run('SELECT * FROM eldi3333_users WHERE username=?',[strtolower(trim($username))])->fetch();if(!$user||!password_verify($password,$user['password_hash']))throw new ClassroomError('Korisničko ime ili lozinka nisu tačni.',401);$this->run('DELETE FROM eldi3333_limits WHERE bucket=?',[$bucket]);unset($user['password_hash']);return $user;}
 public function user(string $id):array{$u=$this->run('SELECT id,username,display_name,role FROM eldi3333_users WHERE id=?',[$id])->fetch();if(!$u)throw new ClassroomError('Prijavite se ponovo.',401);return $u;}
 public function sessionTag(string $id):string{return hash('sha256',(string)$this->run('SELECT password_hash FROM eldi3333_users WHERE id=?',[$id])->fetchColumn());}
 public function teacher(array $u):void{if($u['role']!=='teacher')throw new ClassroomError('Ova radnja je dostupna nastavniku.',403);}
 public function classFor(array $u,string $id):array{$c=$this->run('SELECT * FROM eldi3333_classes WHERE id=?',[$id])->fetch();if(!$c)throw new ClassroomError('Odjeljenje nije pronađeno.',404);if($u['role']==='teacher'){if($c['owner_id']!==$u['id'])throw new ClassroomError('Nemate pristup ovom odjeljenju.',403);}elseif(!$this->run('SELECT user_id FROM eldi3333_enrollments WHERE class_id=? AND user_id=?',[$id,$u['id']])->fetch())throw new ClassroomError('Nemate pristup ovom odjeljenju.',403);return $c;}
 public function createClass(array $u,string $title):array{$this->teacher($u);$id=self::id();$this->run('INSERT INTO eldi3333_classes VALUES(?,?,?,?)',[$id,self::text($title),$u['id'],time()]);return ['id'=>$id];}
 public function students(array $u,string $class,array $names):array{
  $this->teacher($u);$this->classFor($u,$class);
  if(count($names)<1||count($names)>40)throw new ClassroomError('Unesite 1–40 učenika po grupi.');
  $created=[];$this->db->beginTransaction();
  try{
   foreach($names as $entry){
    if(is_array($entry)){
     $name=self::text($entry['name']??'',80);
     $login=strtolower(self::text($entry['username']??'',60));
     if(!preg_match('/^[a-z0-9._-]{3,60}$/D',$login))throw new ClassroomError('Korisničko ime: 3–60 slova a–z, cifara, tačka, crtica.');
     $pass=$entry['password']??null;
     if(!is_string($pass))throw new ClassroomError('Unesite lozinku za učenika '.$login.'.');
    }else{
     $name=self::text($entry,80);$login='u'.bin2hex(random_bytes(5));$pass=bin2hex(random_bytes(8));
    }
    $hash=self::password($pass);$id=self::id();
    if($this->run('SELECT id FROM eldi3333_users WHERE username=?',[$login])->fetchColumn())throw new ClassroomError('Korisničko ime '.$login.' već postoji. Promijenite ga i ponovite unos; ovaj spisak nije upisan.',409);
    $this->run('INSERT INTO eldi3333_users VALUES(?,?,?,?,?,?)',[$id,$login,$name,$hash,'student',time()]);
    $this->run('INSERT INTO eldi3333_enrollments VALUES(?,?)',[$class,$id]);
    $created[]=['id'=>$id,'name'=>$name,'username'=>$login,'password'=>$pass];
   }
   $this->db->commit();return $created;
  }catch(Throwable $e){
   $this->db->rollBack();
   if($e instanceof PDOException&&(string)$e->getCode()==='23000')throw new ClassroomError('Korisničko ime već postoji. Promijenite ga i ponovite unos; ovaj spisak nije upisan.',409);
   throw $e;
  }
 }
 public function resetStudent(array $u,string $class,string $student):array{$this->teacher($u);$this->classFor($u,$class);if(!$this->run('SELECT user_id FROM eldi3333_enrollments WHERE class_id=? AND user_id=?',[$class,$student])->fetch())throw new ClassroomError('Učenik nije u odjeljenju.',404);$pass=bin2hex(random_bytes(8));$this->run('UPDATE eldi3333_users SET password_hash=? WHERE id=? AND role=?',[self::password($pass),$student,'student']);return ['password'=>$pass];}
 public function createAssignment(array $u,array $v):array{$this->teacher($u);$class=self::text($v['class_id']??'');$this->classFor($u,$class);$kind=$v['kind']??'project';if(!in_array($kind,['quiz','project'],true))throw new ClassroomError('Nepoznata vrsta zadatka.');$questions=[];if($kind==='quiz'){if(!is_array($v['questions']??null)||count($v['questions'])<1||count($v['questions'])>30)throw new ClassroomError('Provjera sadrži 1–30 pitanja.');foreach($v['questions'] as $q){$answer=self::number($q['answer']??null);if($answer===null)throw new ClassroomError('Svako pitanje treba brojčani odgovor.');$points=(float)($q['points']??10);$tolerance=(float)($q['tolerance']??1e-6);if(!is_finite($points)||$points<1||$points>100||!is_finite($tolerance)||$tolerance<0||$tolerance>.01)throw new ClassroomError('Neispravni bodovi ili tolerancija.');$questions[]=['prompt'=>self::text($q['prompt']??'',2000),'answer'=>$answer,'points'=>$points,'tolerance'=>$tolerance,'explanation'=>self::text($q['explanation']??'',3000,false)];}}
  $due=(int)($v['due_at']??0);if($due!==0&&($due<=time()||$due>time()+366*86400))throw new ClassroomError('Rok mora biti u narednih 366 dana ili prazan.');$id=self::id();$this->run('INSERT INTO eldi3333_assignments VALUES(?,?,?,?,?,?,?,?,?)',[$id,$class,self::text($v['title']??'',150),self::text($v['instructions']??'',10000,false),$kind,json_encode($questions,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE),$due,0,time()]);return ['id'=>$id];}
 public function assignmentFor(array $u,string $id):array{$a=$this->run('SELECT * FROM eldi3333_assignments WHERE id=?',[$id])->fetch();if(!$a)throw new ClassroomError('Zadatak nije pronađen.',404);$this->classFor($u,$a['class_id']);$a['questions']=json_decode($a['questions'],true,512,JSON_THROW_ON_ERROR);return $a;}
 public function assignmentView(array $u,string $id):array{$a=$this->assignmentFor($u,$id);$submission=$this->run('SELECT * FROM eldi3333_submissions WHERE assignment_id=? AND user_id=?',[$id,$u['id']])->fetch();if($u['role']!=='teacher'&&!$submission)$a['questions']=array_map(fn($q)=>['prompt'=>$q['prompt'],'points'=>$q['points']],$a['questions']);if($submission)$submission['payload']=json_decode($submission['payload'],true);return ['assignment'=>$a,'submission'=>$submission?:null];}
 public function submit(array $u,string $id,array $payload):array{if($u['role']!=='student')throw new ClassroomError('Predaja je dostupna učeničkom računu.',403);$a=$this->assignmentFor($u,$id);$old=$this->run('SELECT id,score,max_score FROM eldi3333_submissions WHERE assignment_id=? AND user_id=?',[$id,$u['id']])->fetch();if($old)return $old;
  if((int)$a['closed']||($a['due_at']&&time()>(int)$a['due_at']))throw new ClassroomError('Rok je istekao ili je nastavnik zatvorio zadatak.',409);$score=0.;$max=0.;if($a['kind']==='quiz'){$answers=$payload['answers']??[];if(!is_array($answers))throw new ClassroomError('Neispravni odgovori.');$clean=[];foreach($a['questions'] as $i=>$q){$v=$answers[$i]??'';if(!is_scalar($v)||strlen((string)$v)>80)throw new ClassroomError('Odgovor je predug.');$clean[]=(string)$v;$n=self::number($v);$max+=$q['points'];if($n!==null&&abs($n-$q['answer'])<=max(1,abs($q['answer']))*$q['tolerance'])$score+=$q['points'];}$payload=['answers'=>$clean];}else{$text=self::text($payload['text']??'',15000,false);$project=$payload['project']??null;if($project!==null&&(!is_array($project)||!in_array($project['format']??'',['ELDI-33-PROJECT','ELDI-33-ASSIGNMENT'],true)))throw new ClassroomError('Prilog mora biti izvezeni ELDI JSON projekat.');if(!$text&&!$project)throw new ClassroomError('Napiši objašnjenje ili priloži projekat.');$payload=['text'=>$text,'project'=>$project];}
  $raw=json_encode($payload,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);if(strlen($raw)>2500000)throw new ClassroomError('Rad može imati najviše 2,5 MB.');$submissionId=self::id();try{$this->run('INSERT INTO eldi3333_submissions VALUES(?,?,?,?,?,?,?,?,?)',[$submissionId,$id,$u['id'],$raw,$score,$max,'','',time()]);}catch(PDOException $e){$same=$this->run('SELECT id,score,max_score FROM eldi3333_submissions WHERE assignment_id=? AND user_id=?',[$id,$u['id']])->fetch();if($same)return $same;throw $e;}return ['id'=>$submissionId,'score'=>$score,'max_score'=>$max];}
 public function dashboard(array $u):array{if($u['role']==='teacher')$classes=$this->run('SELECT * FROM eldi3333_classes WHERE owner_id=? ORDER BY created_at DESC',[$u['id']])->fetchAll();else $classes=$this->run('SELECT c.* FROM eldi3333_classes c JOIN eldi3333_enrollments e ON e.class_id=c.id WHERE e.user_id=? ORDER BY c.title',[$u['id']])->fetchAll();$assignments=[];foreach($classes as $c){$rows=$this->run('SELECT id,class_id,title,kind,due_at,closed,created_at FROM eldi3333_assignments WHERE class_id=? ORDER BY created_at DESC',[$c['id']])->fetchAll();foreach($rows as &$a){if($u['role']==='student')$a['submission']=$this->run('SELECT id,score,max_score,grade,feedback,submitted_at FROM eldi3333_submissions WHERE assignment_id=? AND user_id=?',[$a['id'],$u['id']])->fetch()?:null;else $a['submitted']=(int)$this->run('SELECT COUNT(*) FROM eldi3333_submissions WHERE assignment_id=?',[$a['id']])->fetchColumn();}unset($a);$assignments=array_merge($assignments,$rows);}return ['classes'=>$classes,'assignments'=>$assignments];}
 public function roster(array $u,string $class):array{$this->teacher($u);$this->classFor($u,$class);return $this->run('SELECT u.id,u.username,u.display_name FROM eldi3333_users u JOIN eldi3333_enrollments e ON e.user_id=u.id WHERE e.class_id=? ORDER BY u.display_name',[$class])->fetchAll();}
 public function submissions(array $u,string $id):array{$this->teacher($u);$this->assignmentFor($u,$id);return $this->run('SELECT s.id,s.user_id,s.score,s.max_score,s.grade,s.feedback,s.submitted_at,u.display_name FROM eldi3333_submissions s JOIN eldi3333_users u ON u.id=s.user_id WHERE assignment_id=? ORDER BY submitted_at',[$id])->fetchAll();}
 public function submissionFor(array $u,string $id):array{$s=$this->run('SELECT * FROM eldi3333_submissions WHERE id=?',[$id])->fetch();if(!$s)throw new ClassroomError('Predaja nije pronađena.',404);$this->assignmentFor($u,$s['assignment_id']);if($u['role']!=='teacher'&&$s['user_id']!==$u['id'])throw new ClassroomError('Nemate pristup tuđem radu.',403);$s['payload']=json_decode($s['payload'],true,512,JSON_THROW_ON_ERROR);return $s;}
 public function review(array $u,string $id,string $grade,string $feedback):void{$this->teacher($u);$this->submissionFor($u,$id);if(!in_array($grade,['','1','2','3','4','5'],true))throw new ClassroomError('Ocjena je 1–5 ili prazna.');$this->run('UPDATE eldi3333_submissions SET grade=?,feedback=? WHERE id=?',[$grade,self::text($feedback,5000,false),$id]);}
 public function close(array $u,string $id,bool $closed):void{$this->teacher($u);$this->assignmentFor($u,$id);$this->run('UPDATE eldi3333_assignments SET closed=? WHERE id=?',[$closed?1:0,$id]);}
 public function removeStudent(array $u,string $class,string $student):void{$this->teacher($u);$this->classFor($u,$class);if(!$this->run('SELECT user_id FROM eldi3333_enrollments WHERE class_id=? AND user_id=?',[$class,$student])->fetch())throw new ClassroomError('Učenik nije pronađen.',404);$this->db->beginTransaction();try{$this->run('DELETE FROM eldi3333_submissions WHERE user_id=?',[$student]);$this->run('DELETE FROM eldi3333_enrollments WHERE user_id=?',[$student]);$this->run('DELETE FROM eldi3333_users WHERE id=? AND role=?',[$student,'student']);$this->db->commit();}catch(Throwable $e){$this->db->rollBack();throw $e;}}
 public function changePassword(array $u,string $old,string $new):void{$current=$this->run('SELECT password_hash FROM eldi3333_users WHERE id=?',[$u['id']])->fetchColumn();if(!password_verify($old,$current))throw new ClassroomError('Trenutna lozinka nije tačna.',403);$this->run('UPDATE eldi3333_users SET password_hash=? WHERE id=?',[self::password($new),$u['id']]);}
}
